In [1]:
!pip install pdfplumber

Collecting pdfplumber
  Downloading pdfplumber-0.11.7-py3-none-any.whl.metadata (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 kB 1.7 MB/s eta 0:00:00
Collecting pdfminer.six==20250506 (from pdfplumber)
  Downloading pdfminer_six-20250506-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.11/dist-packages (from pdfplumber) (11.2.1)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-4.30.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.2/48.2 kB 4.8 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20250506->pdfplumber) (3.4.2)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20250506->pdfplumber) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=36.0.0->pdfminer.six==20250506->pdfplumber) (1.17.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20250506->pdfplumber) (2.22)
Downloading pdfplumber-0.11.7-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 4.0 MB/s eta 0:00:00
Downloading pdfminer_six-20250506-py3-none-any.whl (5.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 49.8 MB/s eta 0:00:00
Downloading pypdfium2-4.30.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 72.6 MB/s eta 0:00:00
Installing collected packages: pypdfium2, pdfminer.six, pdfplumber
Successfully installed pdfminer.six-20250506 pdfplumber-0.11.7 pypdfium2-4.30.1

In [2]:
import pdfplumber
import pandas as pd
import csv
from google.colab import files

In [4]:
uploaded = files.upload()

Saving PGA2025.pdf to PGA2025 (1).pdf

In [5]:
# Armazenar texto e tabelas
textos_extraidos = []
tabelas_extraidas = []

# Abrir o PDF e extrair os dados
with pdfplumber.open("PGA2025.pdf") as pdf:
    for i, page in enumerate(pdf.pages):
        print(f"\n===== Página {i+1} =====\n")

        text = page.extract_text()
        if text:
            textos_extraidos.append(text)
            print(text[:1000])  # Exibe parte do texto
        else:
            print("Nenhum texto detectado nesta página.")

        tables = page.extract_tables()
        for table in tables:
            tabelas_extraidas.append(table)
            print("\nTabela(s) encontrada(s):")
            for row in table:
                print(row)

===== Página 1 =====

PLANO DE GESTÃO ANUAL
PGA 2025
V04
Estruturado em uma única etapa, contendo 2 anexos:
PLANEJAMENTO PELA EQUIPE GESTORA DA UE
• Anexo 1 – Lista de equipamentos necessários aos projetos
• Anexo 2 – Lista de Ações/Projetos referentes à CPA (Origem 3: Gestão Tática – CPA)
IDENTIFICAÇÃO DA UNIDADE
Unidade código F301 Fatec Votorantim
Diretor(a) Prof. Dr. Mauro Tomazela
PLANEJAMENTO PELA EQUIPE GESTORA DA UE
(Administração da Faculdade - Deliberação CEETEPS 31/2016)
ANÁLISE DO CENÁRIO
Descrever de forma breve e objetiva o cenário da Unidade perante sua missão como Unidade de Ensino na localidade em que
se encontra (é este cenário que se pretende melhorar).
Votorantim, um município da região metropolitana de Sorocaba, no interior de São Paulo, inaugurou em 2022 a Fatec
Votorantim, que ofereceu à comunidade 80 vagas semestrais, distribuídas entre os seguintes cursos:
Controle de Obras: 40 vagas (noturno)
Desenvolvimento de Software Multiplataforma: 40 vagas (noturno)
A partir do segundo semest

Tabela(s) encontrada(s):
['PLANO DE GESTÃO ANUAL']
['PGA 2025']
['V04']

Tabela(s) encontrada(s):
['', 'IDENTIFICAÇÃO DA UNIDADE', None, None, '']
['Unidade', None, 'código F301', 'Fatec Votorantim', None]
['Diretor(a)', None, 'Prof. Dr. Mauro Tomazela', None, None]

Tabela(s) encontrada(s):
['', 'ANÁLISE DO CENÁRIO', '']
[None, 'Descrever de forma breve e objetiva o cenário da Unidade perante sua missão como Unidade de Ensino na localidade em que', None]
[None, 'se encontra (é este cenário que se pretende melhorar).', None]
['Votorantim, um município da região metropolitana de Sorocaba, no interior de São Paulo, inaugurou em 2022 a Fatec\nVotorantim, que ofereceu à comunidade 80 vagas semestrais, distribuídas entre os seguintes cursos:\nControle de Obras: 40 vagas (noturno)\nDesenvolvimento de Software Multiplataforma: 40 vagas (noturno)\nA partir do segundo semestre de 2023, ambos os cursos reduziram sua oferta para 35 vagas cada. Essa mudança foi\nnecessária devido às limitações de capacidade física das salas de aula e laboratórios.\nNo primeiro semestre de 2024, a instituição expandiu seu catálogo acadêmico para incluir o Curso de Ciência de Dados para\nNegócios, também com 35 vagas semestrais, além dos já existentes.\nÉ importante destacar que a cidade de Votorantim apresenta um grau de urbanização 96,2 (%) (SEADE 2022), população da\ncidade estimada em 124.468 (IBGE 2021), PIB per capta R$ 28.587 (SEADE 2020), com IDH 0,767 (IBGE 2010) um dos\nmelhores índices, tem como orçamento vigente R$ 617.500,000, conta com aproximadamente 5.298 MEIs, 902 empresas de\ngrande e médio porte, 402 empresas de pequeno porte, 2.253 microempresas e 470 profissionais liberais (Secretaria de\nFinanças de Votorantim – SEF). Além disso, possuí, aproximadamente, 39.725 imóveis construídos, 1.492 ruas, 203\nloteamentos e 127 condomínios (Secretaria de Finanças de Votorantim – SEF).\nImportante salientar que, a cidade de Votorantim faz parte da RMS (Região Metropolitana de Sorocaba). Neste contexto, a\nRegião Administrativa de Sorocaba (RAS) ocupa a maior área do Estado de São Paulo (16,5%). E entre os municípios com\nmaior índice populacional estão: Sorocaba, Salto de Pirapora e Votorantim, que somam mais de 500 hab/km². A população\nprojetada nesta região é de quase 2,6 milhões de habitantes, ou seja, 6,7% do total do Estado. A economia da RAS está\nfortemente estruturada na atividade industrial, contando com diversos seguimentos, além do têxtil, tradicional na região\n(Segundo dados da Pesquisa de Atividade Econômica Paulista - PAEP).\nVotorantim conta ainda com uma ampla rede hoteleira, shopping center e estrutura comercial variada, abriga empresas como:\nControlflex, SOal, Grupo Votorantim, Suzano Papel e Celulose, Vitopel, Alpina Têxtil, Pipocas Clac, FLS midth, Bamberg,\nHoffen Bier, Emphasis, Bandeiras – Centro Empresarial, entre outras.\nCom a aprovação do projeto de lei 635/2018 na Assembleia Legislativa de São Paulo, Votorantim foi classificada pelo Governo\ndo Estado de São Paulo, como Município de Interesse Turístico (MIT). Com isso, a cidade tem acesso a recursos exclusivos\npara investimento na infraestrutura, serviços e equipamentos turísticos, com impacto direto no fomento e ampliação das\natividades econômicas, como geração de emprego, renda e mais qualidade de vida aos votorantinenses.\nNeste contexto, o Governo do Estado de São Paulo, por intermédio do Centro Estadual de Educação Tecnológica Paula Souza e\no Município de Votorantim uniram-se para a implantação da Fatec Votorantim, que oferece cursos superiores de tecnologia\ngratuitos para os habitantes de Votorantim e região de abrangência, a fim de atender o mercado de trabalho diversificado de\nVotorantim e a economia do município que gira, principalmente, em torno da extração e o beneficiamento do cimento (Cimento\nVotorantim), além da indústria; agropecuária; cultivo de hortifrutigranjeiros, comércio e serviços.', None, None]

Tabela(s) encontrada(s):
['', 'APONTAMENTO DE SITUAÇÕES-PROBLEMA MAIS RELEVANTES', None, None, None, None, '']
[None, 'Fontes: relatório CPA, análise de processos críticos da UE, relatório de atendimento e ocorrências Hórus, relatório NDE,', None, None, None, None, None]
[None, 'relatório de representação discente (DA, Atlética, representantes de turma), relatório CIPA, entre outros.', None, None, None, None, None]
['1', None, 'cat 0.1.01 - Metodologia de ensino, desempenho\nde alunos, evasão', '', '5', 'cat 0.1.07 - Comunicação com a comunidade\nacadêmica', None]
['2', None, 'cat 0.1.02 - Manutenção e conservação predial', None, '6', 'cat 0.1.08 - Participação da comunidade e sociedade', None]
['3', None, 'cat 0.1.04 - Infraestrutura laboratorial e ambientes de\nensino', None, '7', 'cat 0.1.11 - Segurança pessoal e patrimonial', None]
['4', None, 'cat 0.1.05 - Materiais, equipamentos e mobiliários', None, '8', 'cat 0.1.99 - Outra', None]
['Outra – Especificar: Internet deficitária', None, None, None, None, None, None]

===== Página 2 =====

Objetivos Institucionais – CPS (Plano de Metas)
1) Atender às demandas sociais e do mercado de trabalho.
2) Obter a satisfação dos públicos que se relacionam com o Centro Paula Souza (stakeholders).
3) Alcançar e manter o grau de excelência em seus processos de ensino e aprendizagem.
4) Assegurar a perenidade do crescimento da instituição com recursos financeiros disponíveis.
5) Garantir celeridade e efetividade na prestação de serviços.
6) Formar profissionais atualizados em tecnologias e processos produtivos, capazes de atuar no desenvolvimento tecnológico e inovação.
7) Promover a cultura de inovação e empreendedorismo.
8) Aumentar a eficiência, a produtividade e a competitividade da instituição.
9) Ampliar a oferta da Educação Profissional.
10) Resolução Conjunta SOG/SFP/SG-3, de 28-12-2022 - Bonificação por Resultados – BR das Secretarias de Estado, Procuradoria Geral do Estado,
Controladoria Geral do Estado e das Autarquias, de que trata a LC 1361-2021
Objetivos Institucionais –

Tabela(s) encontrada(s):
['', 'Objetivos Institucionais – CPS (Plano de Metas)', '']
['1) Atender às demandas sociais e do mercado de trabalho.\n2) Obter a satisfação dos públicos que se relacionam com o Centro Paula Souza (stakeholders).\n3) Alcançar e manter o grau de excelência em seus processos de ensino e aprendizagem.\n4) Assegurar a perenidade do crescimento da instituição com recursos financeiros disponíveis.\n5) Garantir celeridade e efetividade na prestação de serviços.\n6) Formar profissionais atualizados em tecnologias e processos produtivos, capazes de atuar no desenvolvimento tecnológico e inovação.\n7) Promover a cultura de inovação e empreendedorismo.\n8) Aumentar a eficiência, a produtividade e a competitividade da instituição.\n9) Ampliar a oferta da Educação Profissional.\n10) Resolução Conjunta SOG/SFP/SG-3, de 28-12-2022 - Bonificação por Resultados – BR das Secretarias de Estado, Procuradoria Geral do Estado,\nControladoria Geral do Estado e das Autarquias, de que trata a LC 1361-2021', None, None]
['', 'Objetivos Institucionais – Cesu (Plano de Metas)', '']
['A. Integrar as diferentes modalidades de ensino, otimizando itinerários e tempo para a formação profissional.\nB. Inovar processos de ensino e aprendizagem para manter excelência diante do mercado.\nC. Ampliar a capacidade de criar e atualizar cursos em parceria com o mercado.\nD. Expandir e ampliar a capacidade de articulação com Governos e Setores Produtivos.\nE. Promover a captação de recursos extras e não orçamentários.', None, None]

===== Página 3 =====

ESTRUTURAÇÃO DAS AÇÕES/PROJETOS
01 - Didático-pedagógico
Ações associadas ao PPC/PE de CSTs e Disciplinas: CST (implantação, alteração, readequação, reestruturação),
prática pedagógica (PE, PA), projeto interdisciplinar/ integrador, extensão curricularizada.
AÇÃO/PROJETO (Tema) 101 - cat 1.04 - Biblioteca Ativa e aquisição de bibliografias
Origem (prioridade): 3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebSAI, RAAI)
Planejamento/ organização/ instalação de infraestrutura e mobiliários / organização de acesso
O que será feito:
lógico ao acervo/ compra e catalogação.
Por que será feito: Para incentivar o uso da biblioteca da unidade e atendimento de demandas legais
<nome> Júlia Cristina Gütschow Sampaio Qde CH/sem: 5 Tipo: H - Hora <não
Responsável:
tipificada>
Colaborador(a): <nome> nn Qde CH/sem: nn Tipo: Escolher um item.
Colaborador(a): <nome> nn Qde CH/sem: nn Tipo: Escolher um item.
Período de execução: Data inicial: 17/02/2025 Data final: 19/12/2025
Etapas do processo: 01- Planejam

Tabela(s) encontrada(s):
['01 - Didático-pedagógico']
['Ações associadas ao PPC/PE de CSTs e Disciplinas: CST (implantação, alteração, readequação, reestruturação),']
['prática pedagógica (PE, PA), projeto interdisciplinar/ integrador, extensão curricularizada.']

Tabela(s) encontrada(s):
['AÇÃO/PROJETO (Tema)', None, '101 - cat 1.04 - Biblioteca Ativa e aquisição de bibliografias', None, None, None, None, None, None, None, None, None]
['Origem (prioridade):', None, '3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebSAI, RAAI)', None, None, None, None, None, None, None, None, None]
['', None, 'Planejamento/ organização/ instalação de infraestrutura e mobiliários / organização de acesso\nlógico ao acervo/ compra e catalogação.', None, None, None, None, None, None, None, None, None]
['O que será feito:', None, None, None, None, None, None, None, None, None, None, None]
['', None, None, None, None, None, None, None, None, None, None, None]
['Por que será feito:', None, 'Para incentivar o uso da biblioteca da unidade e atendimento de demandas legais', None, None, None, None, None, None, None, None, None]
['', '<nome> Júlia Cristina Gütschow Sampaio', None, None, None, 'Qde CH/sem:', None, None, '5', 'Tipo:', 'H - Hora <não\ntipificada>', None]
['Responsável:', None, None, None, None, None, None, None, None, None, None, None]
[None, None, None, None, None, '', None, None, None, '', None, None]
['', None, None, None, None, None, None, None, None, None, None, None]
['Colaborador(a):', '<nome> nn', None, None, None, 'Qde CH/sem:', None, None, 'nn', 'Tipo:', 'Escolher um item.', None]
['Colaborador(a):', '<nome> nn', None, None, None, 'Qde CH/sem:', None, None, 'nn', 'Tipo:', 'Escolher um item.', None]
['Período de execução:', None, 'Data inicial:', None, '17/02/2025', None, 'Data final:', None, None, None, '19/12/2025', None]
['Etapas do processo:', None, '01- Planejamento e levantamento das ações a serem desenvolvidas', None, None, None, None, None, None, None, '17/02', '19/12']
['', None, '02- Definição da lista dos livros de acordo com o PPC dos cursos', None, None, None, None, None, None, None, '24/02', '14/03']
['', None, '03- Envio da lista de livros para compra na CESU', None, None, None, None, None, None, None, '17/03', '28/03']
['', None, '04- Aquisição da bibliografia básica e complementar', None, None, None, None, None, None, None, '17/02', '19/12']
['', None, '05- Promover ações para incentivo ao uso da biblioteca', None, None, None, None, None, None, None, '17/02', '19/12']
['', None, '06- Digitação do acervo da biblioteca recebido', None, None, None, None, None, None, None, '17/02', '19/12']
['', None, '07- Digitação do acervo da biblioteca recebido', None, None, None, None, None, None, None, '17/02', '19/12']
['', None, '08- nn', None, None, None, None, None, None, None, 'dd/mm', 'dd/mm']
['Custo R$ (se houver):', None, 'A ser definido', 'Fonte(s) dos recursos:', None, None, None, 'Centro Paula Souza (Licitação)', None, None, None, None]
['Situação problema:', None, 'cat 0.1.01 - Metodologia de ensino, desempenho de alunos, evasão', None, None, None, None, None, None, None, None, None]
['(a ser resolvida/mitigada)', None, 'cat 0.1.03 - Infraestrutura predial (espaços, sistemas)', None, None, None, None, None, None, None, None, None]

Tabela(s) encontrada(s):
['', None, '102 - cat 1.06 - Ações pedagógicas: visitas técnicas, projetos integradores/interdisciplinares, dias de campo,\nfeira das profissões, cursos extracurriculares para alunos.', None, None, None, None, None, None, None, None, None]
['AÇÃO/PROJETO (Tema)', None, None, None, None, None, None, None, None, None, None, None]
['', None, None, None, None, None, None, None, None, None, None, None]
['Origem (prioridade):', None, '3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebSAI, RAAI)', None, None, None, None, None, None, None, None, None]
['O que será feito:', None, 'Participação em visitas técnicas a empresas locais e presença em feiras de profissões.', None, None, None, None, None, None, None, None, None]
['', None, 'Os estudantes terão a oportunidade de adquirir conhecimentos práticos aplicados, enquanto\ntambém contribuem para a divulgação da FATEC Votorantim e de seus cursos. Isso não apenas\npermite que os alunos se familiarizem com o mercado, mas também facilita sua visibilidade junto\nàs empresas locais.', None, None, None, None, None, None, None, None, None]
['Por que será feito:', None, None, None, None, None, None, None, None, None, None, None]
['', None, None, None, None, None, None, None, None, None, None, None]
['Responsável:', '<nome> Dilermano Piva Júnior', None, None, None, 'Qde CH/sem:', None, None, '02', 'Tipo:', 'HA - Hora Atividade', None]
['Colaborador(a):', '<nome> Angelina V. S. Melaré', None, None, None, 'Qde CH/sem:', None, None, '02', 'Tipo:', 'HA - Hora Atividade', None]
['Colaborador(a):', '<nome> Lígia C. P. Agasi', None, None, None, 'Qde CH/sem:', None, None, '02', 'Tipo:', 'HA - Hora Atividade', None]
['Período de execução:', None, 'Data inicial:', None, '03/02/2025', None, 'Data final:', None, None, None, '19/12/2025', None]
['Etapas do processo:', None, '01- Consultar os professores sobre a viabilidade de visitas técnicas', None, None, None, None, None, None, None, '03/02', '19/12']
['', None, '02- Fazer o contato e levantamento de empresas regionais para visita', None, None, None, None, None, None, None, '03/02', '19/12']
['', None, '03- Confirmar os professores encarregados das visitas técnicas', None, None, None, None, None, None, None, '03/02', '19/12']
['', None, '04- Realizar agendamento com as empresas', None, None, None, None, None, None, None, '03/02', '19/12']
['', None, '05- Verificar datas de feiras de profissões presenciais e on-line', None, None, None, None, None, None, None, '03/02', '19/12']
['', None, '06- Realizar visitas técnicas', None, None, None, None, None, None, None, '03/02', '19/12']
['', None, '07- Participar de feiras de profissões presenciais e online', None, None, None, None, None, None, None, '03/02', '19/12']
['', None, '08- nn', None, None, None, None, None, None, None, 'dd/mm', 'dd/mm']
['Custo R$ (se houver):', None, 'Não haverá custos', 'Fonte(s) dos recursos:', None, None, None, 'Não haverá custos', None, None, None, None]
['Situação problema:', None, 'cat 0.1.01 - Metodologia de ensino, desempenho de alunos, evasão', None, None, None, None, None, None, None, None, None]
['(a ser resolvida/mitigada)', None, 'cat 0.1.08 - Participação da comunidade e sociedade', None, None, None, None, None, None, None, None, None]

===== Página 4 =====

103 - cat 1.06 - Ações pedagógicas: visitas técnicas, projetos integradores/interdisciplinares, dias de campo,
AÇÃO/PROJETO (Tema)
feira das profissões, cursos extracurriculares para alunos.
Origem (prioridade): 3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebSAI, RAAI)
O que será feito: Implementação de programas de capacitação extracurricular para os estudantes
Para que os alunos tenham acesso a capacitações que os ajudarão a adquirir as habilidades
Por que será feito:
necessárias conforme especificado no Projeto Pedagógico do Curso (PPC).
Responsável: <nome> Angelina V. S. Melaré Qde CH/sem: 02 Tipo: HA - Hora Atividade
Colaborador(a): <nome> Dilermano Piva Júnior Qde CH/sem: 02 Tipo: HA - Hora Atividade
Colaborador(a): <nome> Lígia C. P. Agasi Qde CH/sem: 02 Tipo: HA - Hora Atividade
Período de execução: Data inicial: 03/02/2025 Data final: 19/12/2025
Etapas do processo: 01- Planejar eventos voltados para capacitação 03/02 19/12
02- Criação de formulários de inscrição 03/02 19/12
03-

Tabela(s) encontrada(s):
['', None, '103 - cat 1.06 - Ações pedagógicas: visitas técnicas, projetos integradores/interdisciplinares, dias de campo,\nfeira das profissões, cursos extracurriculares para alunos.', None, None, None, None, None, None, None, None, None]
['AÇÃO/PROJETO (Tema)', None, None, None, None, None, None, None, None, None, None, None]
['', None, None, None, None, None, None, None, None, None, None, None]
['Origem (prioridade):', None, '3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebSAI, RAAI)', None, None, None, None, None, None, None, None, None]
['O que será feito:', None, 'Implementação de programas de capacitação extracurricular para os estudantes', None, None, None, None, None, None, None, None, None]
['', None, 'Para que os alunos tenham acesso a capacitações que os ajudarão a adquirir as habilidades\nnecessárias conforme especificado no Projeto Pedagógico do Curso (PPC).', None, None, None, None, None, None, None, None, None]
['Por que será feito:', None, None, None, None, None, None, None, None, None, None, None]
['', None, None, None, None, None, None, None, None, None, None, None]
['Responsável:', '<nome> Angelina V. S. Melaré', None, None, None, 'Qde CH/sem:', None, None, '02', 'Tipo:', 'HA - Hora Atividade', None]
['Colaborador(a):', '<nome> Dilermano Piva Júnior', None, None, None, 'Qde CH/sem:', None, None, '02', 'Tipo:', 'HA - Hora Atividade', None]
['Colaborador(a):', '<nome> Lígia C. P. Agasi', None, None, None, 'Qde CH/sem:', None, None, '02', 'Tipo:', 'HA - Hora Atividade', None]
['Período de execução:', None, 'Data inicial:', None, '03/02/2025', None, 'Data final:', None, None, None, '19/12/2025', None]
['Etapas do processo:', None, '01- Planejar eventos voltados para capacitação', None, None, None, None, None, None, None, '03/02', '19/12']
['', None, '02- Criação de formulários de inscrição', None, None, None, None, None, None, None, '03/02', '19/12']
['', None, '03- Divulgação dos formulários a comunidade docente e discente', None, None, None, None, None, None, None, '03/02', '19/12']
['', None, '04- Acompanhar a participação efetiva dos inscritos', None, None, None, None, None, None, None, '03/02', '19/12']
['', None, '05- Aquisição de materiais e insumos para os cursos extracurriculares', None, None, None, None, None, None, None, '03/02', '19/12']
['', None, '06- nn', None, None, None, None, None, None, None, 'dd/mm', 'dd/mm']
['', None, '07- nn', None, None, None, None, None, None, None, 'dd/mm', 'dd/mm']
['', None, '08- nn', None, None, None, None, None, None, None, 'dd/mm', 'dd/mm']
['Custo R$ (se houver):', None, 'A ser definido', 'Fonte(s) dos recursos:', None, None, None, 'DMPP', None, None, None, None]

In [6]:
# Exportar o texto extraído para um arquivo
with open("texto_extraido.txt", "w", encoding="utf-8") as f:
    for texto in textos_extraidos:
        f.write(texto + "\n\n")
print("Arquivo de texto exportado com sucesso!")

Arquivo de texto exportado com sucesso!

In [7]:
# Exportar a primeira tabela para CSV
if tabelas_extraidas:
    with open("tabela_exemplo.csv", "w", newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        for row in tabelas_extraidas[0]:
            writer.writerow(row)
    print("Tabela exportada para 'tabela_exemplo.csv'.")
else:
    print("Nenhuma tabela encontrada para exportar.")

Tabela exportada para 'tabela_exemplo.csv'.

In [8]:
# Visualizar tabelas como DataFrame
for i, tabela in enumerate(tabelas_extraidas):
    print(f"\nTabela {i+1}")
    df = pd.DataFrame(tabela)
    display(df)

Tabela 1

                       0
0  PLANO DE GESTÃO ANUAL
1               PGA 2025
2                    V04

Tabela 2

,0,1,2,3,4
0,,IDENTIFICAÇÃO DA UNIDADE,None,None,
1,Unidade,None,código F301,Fatec Votorantim,None
2,Diretor(a),None,Prof. Dr. Mauro Tomazela,None,None

Tabela 3

,0,1,2
0,,ANÁLISE DO CENÁRIO,
1,None,Descrever de forma breve e objetiva o cenário ...,None
2,None,se encontra (é este cenário que se pretende me...,None
3,"Votorantim, um município da região metropolita...",None,None

Tabela 4

,0,1,2,3,4,5,6
0,,APONTAMENTO DE SITUAÇÕES-PROBLEMA MAIS RELEVANTES,None,None,None,None,
1,None,"Fontes: relatório CPA, análise de processos cr...",None,None,None,None,None
2,None,"relatório de representação discente (DA, Atlét...",None,None,None,None,None
3,1,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",,5,cat 0.1.07 - Comunicação com a comunidade\naca...,None
4,2,None,cat 0.1.02 - Manutenção e conservação predial,None,6,cat 0.1.08 - Participação da comunidade e soci...,None
5,3,None,cat 0.1.04 - Infraestrutura laboratorial e amb...,None,7,cat 0.1.11 - Segurança pessoal e patrimonial,None
6,4,None,"cat 0.1.05 - Materiais, equipamentos e mobiliá...",None,8,cat 0.1.99 - Outra,None
7,Outra – Especificar: Internet deficitária,None,None,None,None,None,None

Tabela 5

,0,1,2
0,,Objetivos Institucionais – CPS (Plano de Metas),
1,1) Atender às demandas sociais e do mercado de...,None,None
2,,Objetivos Institucionais – Cesu (Plano de Metas),
3,A. Integrar as diferentes modalidades de ensin...,None,None

Tabela 6

                                                   0
0                           01 - Didático-pedagógico
1  Ações associadas ao PPC/PE de CSTs e Disciplin...
2  prática pedagógica (PE, PA), projeto interdisc...

Tabela 7

/usr/local/lib/python3.11/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,101 - cat 1.04 - Biblioteca Ativa e aquisição ...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
2,,None,Planejamento/ organização/ instalação de infra...,None,None,None,None,None,None,None,None,None
3,O que será feito:,None,None,None,None,None,None,None,None,None,None,None
4,,None,None,None,None,None,None,None,None,None,None,None
5,Por que será feito:,None,Para incentivar o uso da biblioteca da unidade...,None,None,None,None,None,None,None,None,None
6,,<nome> Júlia Cristina Gütschow Sampaio,None,None,None,Qde CH/sem:,None,None,5,Tipo:,H - Hora <não\ntipificada>,None
7,Responsável:,None,None,None,None,None,None,None,None,None,None,None
8,None,None,None,None,None,,None,None,None,,None,None
9,,None,None,None,None,None,None,None,None,None,None,None
10,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
11,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
12,Período de execução:,None,Data inicial:,None,17/02/2025,None,Data final:,None,None,None,19/12/2025,None
13,Etapas do processo:,None,01- Planejamento e levantamento das ações a se...,None,None,None,None,None,None,None,17/02,19/12
14,,None,02- Definição da lista dos livros de acordo co...,None,None,None,None,None,None,None,24/02,14/03
15,,None,03- Envio da lista de livros para compra na CESU,None,None,None,None,None,None,None,17/03,28/03
16,,None,04- Aquisição da bibliografia básica e complem...,None,None,None,None,None,None,None,17/02,19/12
17,,None,05- Promover ações para incentivo ao uso da bi...,None,None,None,None,None,None,None,17/02,19/12
18,,None,06- Digitação do acervo da biblioteca recebido,None,None,None,None,None,None,None,17/02,19/12
19,,None,07- Digitação do acervo da biblioteca recebido,None,None,None,None,None,None,None,17/02,19/12
20,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
21,Custo R$ (se houver):,None,A ser definido,Fonte(s) dos recursos:,None,None,None,Centro Paula Souza (Licitação),None,None,None,None
22,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
23,(a ser resolvida/mitigada),None,"cat 0.1.03 - Infraestrutura predial (espaços, ...",None,None,None,None,None,None,None,None,None

Tabela 8

,0,1,2,3,4,5,6,7,8,9,10,11
0,,None,102 - cat 1.06 - Ações pedagógicas: visitas té...,None,None,None,None,None,None,None,None,None
1,AÇÃO/PROJETO (Tema),None,None,None,None,None,None,None,None,None,None,None
2,,None,None,None,None,None,None,None,None,None,None,None
3,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
4,O que será feito:,None,Participação em visitas técnicas a empresas lo...,None,None,None,None,None,None,None,None,None
5,,None,Os estudantes terão a oportunidade de adquirir...,None,None,None,None,None,None,None,None,None
6,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
7,,None,None,None,None,None,None,None,None,None,None,None
8,Responsável:,<nome> Dilermano Piva Júnior,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
9,Colaborador(a):,<nome> Angelina V. S. Melaré,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
10,Colaborador(a):,<nome> Lígia C. P. Agasi,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
11,Período de execução:,None,Data inicial:,None,03/02/2025,None,Data final:,None,None,None,19/12/2025,None
12,Etapas do processo:,None,01- Consultar os professores sobre a viabilida...,None,None,None,None,None,None,None,03/02,19/12
13,,None,02- Fazer o contato e levantamento de empresas...,None,None,None,None,None,None,None,03/02,19/12
14,,None,03- Confirmar os professores encarregados das ...,None,None,None,None,None,None,None,03/02,19/12
15,,None,04- Realizar agendamento com as empresas,None,None,None,None,None,None,None,03/02,19/12
16,,None,05- Verificar datas de feiras de profissões pr...,None,None,None,None,None,None,None,03/02,19/12
17,,None,06- Realizar visitas técnicas,None,None,None,None,None,None,None,03/02,19/12
18,,None,07- Participar de feiras de profissões presenc...,None,None,None,None,None,None,None,03/02,19/12
19,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
20,Custo R$ (se houver):,None,Não haverá custos,Fonte(s) dos recursos:,None,None,None,Não haverá custos,None,None,None,None
21,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
22,(a ser resolvida/mitigada),None,cat 0.1.08 - Participação da comunidade e soci...,None,None,None,None,None,None,None,None,None

Tabela 9

,0,1,2,3,4,5,6,7,8,9,10,11
0,,None,103 - cat 1.06 - Ações pedagógicas: visitas té...,None,None,None,None,None,None,None,None,None
1,AÇÃO/PROJETO (Tema),None,None,None,None,None,None,None,None,None,None,None
2,,None,None,None,None,None,None,None,None,None,None,None
3,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
4,O que será feito:,None,Implementação de programas de capacitação extr...,None,None,None,None,None,None,None,None,None
5,,None,Para que os alunos tenham acesso a capacitaçõe...,None,None,None,None,None,None,None,None,None
6,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
7,,None,None,None,None,None,None,None,None,None,None,None
8,Responsável:,<nome> Angelina V. S. Melaré,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
9,Colaborador(a):,<nome> Dilermano Piva Júnior,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
10,Colaborador(a):,<nome> Lígia C. P. Agasi,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
11,Período de execução:,None,Data inicial:,None,03/02/2025,None,Data final:,None,None,None,19/12/2025,None
12,Etapas do processo:,None,01- Planejar eventos voltados para capacitação,None,None,None,None,None,None,None,03/02,19/12
13,,None,02- Criação de formulários de inscrição,None,None,None,None,None,None,None,03/02,19/12
14,,None,03- Divulgação dos formulários a comunidade do...,None,None,None,None,None,None,None,03/02,19/12
15,,None,04- Acompanhar a participação efetiva dos insc...,None,None,None,None,None,None,None,03/02,19/12
16,,None,05- Aquisição de materiais e insumos para os c...,None,None,None,None,None,None,None,03/02,19/12
17,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
18,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
19,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
20,Custo R$ (se houver):,None,A ser definido,Fonte(s) dos recursos:,None,None,None,DMPP,None,None,None,None
21,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
22,(a ser resolvida/mitigada),None,cat 0.1.99 - Outra,None,None,None,None,None,None,None,None,None

Tabela 10

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,104 - cat 1.03 - COIL/PCI e Escola de Inovadores,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Incentivar a participação no projeto “Escola d...,None,None,None,None,None,None,None,None,None
3,,None,Para que os alunos possam ampliar o conhecimen...,None,None,None,None,None,None,None,None,None
4,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
5,,None,None,None,None,None,None,None,None,None,None,None
6,Responsável:,<nome> Angelina S. V. Milaré,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
7,Colaborador(a):,<nome> Dilermando Piva Júnior,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
8,,<nome> Rosana Bertila,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HAE - Hora Atividade\nEspecífica,None
9,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
10,None,None,None,None,None,,None,None,None,,None,None
11,,None,None,None,None,None,None,None,None,None,None,None
12,Período de execução:,None,Data inicial:,None,03/02/2025,None,Data final:,None,None,None,19/12/2025,None
13,Etapas do processo:,None,01- Agendar palestra com a Agente Regional do ...,None,None,None,None,None,None,None,03/02,19/12
14,,None,02- Divulgar e motivar a participação dos alun...,None,None,None,None,None,None,None,03/02,19/12
15,,None,03- Realizar a inscrição dos alunos,None,None,None,None,None,None,None,03/02,19/12
16,,None,04- Incentivar a participação continuada dos a...,None,None,None,None,None,None,None,03/02,19/12
17,,None,05- Acompanhar a participação dos alunos,None,None,None,None,None,None,None,03/02,19/12
18,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
19,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
20,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
21,Custo R$ (se houver):,None,Não haverá custos,Fonte(s) dos recursos:,None,None,None,Não haverá custos,None,None,None,None
22,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
23,(a ser resolvida/mitigada),None,cat 0.1.08 - Participação da comunidade e soci...,None,None,None,None,None,None,None,None,None

Tabela 11

,0,1,2,3,4,5,6
0,AÇÃO/PROJETO (Tema),None,105 - cat 1.12 - Orientação profissional para ...,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None
2,,None,Estabelecimento e organização do núcleo de emp...,None,None,None,None
3,O que será feito:,None,None,None,None,None,None
4,,None,None,None,None,None,None
5,,None,Facilitar oportunidades de emprego e reintegra...,None,None,None,None
6,Por que será feito:,None,None,None,None,None,None
7,,None,None,None,None,None,None
8,,<nome> Maria Eliana Gomes Cardim de Q Guimarães,None,Qde CH/sem:,08,Tipo:,HAE - Hora Atividade\nEspecífica
9,Responsável:,None,None,None,None,None,None
10,None,None,None,,None,,None
11,,None,None,None,None,None,None
12,,<nome> Juliana Ribeiro de Lima,None,Qde CH/sem:,05,Tipo:,HAE - Hora Atividade\nEspecífica
13,Colaborador(a):,None,None,None,None,None,None
14,None,None,None,,None,,None
15,,None,None,None,None,None,None
16,Colaborador(a):,<nome> nn,None,Qde CH/sem:,nn,Tipo:,Escolher um item.

Tabela 12

,0,1,2,3,4,5,6,7
0,Período de execução:,Data inicial:,None,03/02/2025,Data final:,None,19/12/2025,None
1,,01- Análise do PPC dos cursos e aprovação da p...,None,None,None,None,03/02,19/12
2,Etapas do processo:,None,None,None,None,None,None,None
3,,None,None,None,None,None,None,None
4,,02- Levantamento de perfil e motivações,None,None,None,None,03/02,19/12
5,,03- Desenvolvimento de currículo,None,None,None,None,03/02,19/12
6,,04- Curso de capacitação para os alunos,None,None,None,None,03/02,19/12
7,,05- Desenvolvimento de relatório de acompanham...,None,None,None,None,03/02,19/12
8,,06- nn,None,None,None,None,dd/mm,dd/mm
9,,07- nn,None,None,None,None,dd/mm,dd/mm
10,,08- nn,None,None,None,None,dd/mm,dd/mm
11,Custo R$ (se houver):,Não haverá custos,Fonte(s) dos recursos:,None,None,Não haverá custos,None,None
12,Situação problema:,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None
13,(a ser resolvida/mitigada),Escolher um item.,None,None,None,None,None,None

Tabela 13

,0,1,2,3,4,5,6,7,8,9,10,11
0,,None,106 - cat 1.06 - Ações pedagógicas: visitas té...,None,None,None,None,None,None,None,None,None
1,AÇÃO/PROJETO (Tema),None,None,None,None,None,None,None,None,None,None,None
2,,None,None,None,None,None,None,None,None,None,None,None
3,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None,None,None,None
4,,None,Acompanhamento e auxílio no desenvolvimento de...,None,None,None,None,None,None,None,None,None
5,O que será feito:,None,None,None,None,None,None,None,None,None,None,None
6,,None,None,None,None,None,None,None,None,None,None,None
7,,None,Oferecer suporte para esclarecimento de dúvida...,None,None,None,None,None,None,None,None,None
8,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
9,,None,None,None,None,None,None,None,None,None,None,None
10,Responsável:,<nome> Angelina V. S. Melaré,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
11,,<nome> Ricardo Roberto Leme,None,None,None,Qde CH/sem:,None,None,04,Tipo:,HAE - Hora Atividade\nEspecífica,None
12,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
13,None,None,None,None,None,,None,None,None,,None,None
14,,None,None,None,None,None,None,None,None,None,None,None
15,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
16,Período de execução:,None,Data inicial:,None,03/02/2025,None,Data final:,None,None,None,19/12/2025,None
17,Etapas do processo:,None,01- Divulgação aos alunos,None,None,None,None,None,None,None,03/02,19/12
18,,None,02- Acompanhamento semanal das atividades dese...,None,None,None,None,None,None,None,03/02,19/12
19,,None,03- Desenvolvimento de documentação do projeto...,None,None,None,None,None,None,None,03/02,19/12
20,,None,04- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
21,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
22,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
23,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
24,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
25,Custo R$ (se houver):,None,Não haverá custos,Fonte(s) dos recursos:,None,None,None,Não haverá custos,None,None,None,None
26,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
27,(a ser resolvida/mitigada),None,cat 0.1.99 - Outra,None,None,None,None,None,None,None,None,None

Tabela 14

,0,1,2,3,4,5,6,7,8,9
0,AÇÃO/PROJETO (Tema),None,107 - cat 1.05 - Monitoria em disciplina do curso,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None
2,,None,Disponibilizar um monitor para as disciplinas ...,None,None,None,None,None,None,None
3,O que será feito:,None,None,None,None,None,None,None,None,None
4,,None,None,None,None,None,None,None,None,None
5,Por que será feito:,None,Para esclarecer dúvidas e apoiar os alunos com...,None,None,None,None,None,None,None
6,Responsável:,<nome> Lígia Conceição Pereira Agasi,None,None,Qde CH/sem:,None,02,Tipo:,HA - Hora Atividade,None
7,Colaborador(a):,<nome> Angelina V. S. Melaré,None,None,Qde CH/sem:,None,02,Tipo:,HA - Hora Atividade,None
8,,<nome> Adriana Barros/Laísa Gamito,None,None,Qde CH/sem:,None,02,Tipo:,H - Hora <não\ntipificada>,None
9,Colaborador(a):,None,None,None,None,None,None,None,None,None
10,None,None,None,None,,None,None,,None,None
11,,None,None,None,None,None,None,None,None,None
12,Período de execução:,None,Data inicial:,03/02/2025,None,Data final:,None,None,19/12/2025,None
13,,None,01- Os professores responsáveis deverão fornec...,None,None,None,None,None,03/02,19/12
14,Etapas do processo:,None,None,None,None,None,None,None,None,None
15,,None,None,None,None,None,None,None,None,None
16,,None,02- Comunicar aos alunos os horários de oferec...,None,None,None,None,None,03/02,19/12
17,,None,03- Os professores e a coordenação deverão mot...,None,None,None,None,None,03/02,19/12
18,,None,None,None,None,None,None,None,None,None
19,,None,None,None,None,None,None,None,None,None
20,,None,04- Os monitores deverão gerar e resolver list...,None,None,None,None,None,03/02,19/12
21,,None,05- Atender os alunos com dificuldades semanal...,None,None,None,None,None,03/02,19/12
22,,None,06- nn,None,None,None,None,None,dd/mm,dd/mm
23,,None,07- nn,None,None,None,None,None,dd/mm,dd/mm
24,,None,08- nn,None,None,None,None,None,dd/mm,dd/mm

Tabela 15

,0,1,2,3
0,Custo R$ (se houver):,25% da HA para cada monitor,Fonte(s) dos recursos:,CESU
1,Situação problema:,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None
2,(a ser resolvida/mitigada),cat 0.1.99 - Outra,None,None

Tabela 16

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,108 - cat.1.99 - Outra,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"1-Regulação - Notificação de órgão (MEC, CEE, ...",None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Processo de Avaliação da CPA,None,None,None,None,None,None,None,None,None
3,,None,Com o objetivo de conduzir um processo abrange...,None,None,None,None,None,None,None,None,None
4,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
5,,None,None,None,None,None,None,None,None,None,None,None
6,,<nome> Diego Aparecido Carvalho Albuquerque,None,None,None,Qde CH/sem:,None,None,11,Tipo:,HAE - Hora Atividade\nEspecífica,None
7,Responsável:,None,None,None,None,None,None,None,None,None,None,None
8,None,None,None,None,None,,None,None,None,,None,None
9,,None,None,None,None,None,None,None,None,None,None,None
10,Colaborador(a):,<nome> Angelina S. V. Melaré / Dilermando Piva...,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
11,,<nome> Administrativo/Direção,None,None,None,Qde CH/sem:,None,None,02,Tipo:,H - Hora <não\ntipificada>,None
12,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
13,None,None,None,None,None,,None,None,None,,None,None
14,,None,None,None,None,None,None,None,None,None,None,None
15,Período de execução:,None,Data inicial:,None,03/02/2025,None,Data final:,None,None,None,19/12/2025,None
16,,None,"01- Divulgação e esclarecimento aos docentes, ...",None,None,None,None,None,None,None,03/02,19/12
17,Etapas do processo:,None,None,None,None,None,None,None,None,None,None,None
18,,None,None,None,None,None,None,None,None,None,None,None
19,,None,02- Análise das avaliações anteriores,None,None,None,None,None,None,None,03/02,19/12
20,,None,03- Análise das metas,None,None,None,None,None,None,None,03/02,19/12
21,,None,04- Geração de relatórios e gráficos,None,None,None,None,None,None,None,03/02,19/12
22,,None,05- Consolidar um programa de sensibilização e...,None,None,None,None,None,None,None,03/02,19/12
23,,None,None,None,None,None,None,None,None,None,None,None
24,,None,None,None,None,None,None,None,None,None,None,None
25,,None,06- Rever a forma e frequência de divulgação d...,None,None,None,None,None,None,None,03/02,19/12
26,,None,None,None,None,None,None,None,None,None,None,None
27,,None,None,None,None,None,None,None,None,None,None,None
28,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
29,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
30,Custo R$ (se houver):,None,Não haverá custos,Fonte(s) dos recursos:,None,None,None,Não haverá custos,None,None,None,None
31,Situação problema:,None,cat 0.1.10 - Gestão da unidade de ensino e dos...,None,None,None,None,None,None,None,None,None
32,(a ser resolvida/mitigada),None,cat 0.1.99 - Outra,None,None,None,None,None,None,None,None,None

Tabela 17

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,109 - cat 1.01 - Adequação/reestruturação de P...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"1-Regulação - Notificação de órgão (MEC, CEE, ...",None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Análise e reestruturação do PPC do curso para ...,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,Para atender exigências legais.,None,None,None,None,None,None,None,None,None
4,Responsável:,<nome> Coordenadores,None,None,None,Qde CH/sem:,None,None,06,Tipo:,HA - Hora Atividade,None
5,,<nome> Representantes do NDE dos cursos,None,None,None,Qde CH/sem:,None,None,06,Tipo:,H - Hora <não\ntipificada>,None
6,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
7,None,None,None,None,None,,None,None,None,,None,None
8,,None,None,None,None,None,None,None,None,None,None,None
9,,<nome> Juliana Tonon,None,None,None,Qde CH/sem:,None,None,06,Tipo:,H - Hora <não\ntipificada>,None
10,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
11,None,None,None,None,None,,None,None,None,,None,None
12,,None,None,None,None,None,None,None,None,None,None,None
13,Período de execução:,None,Data inicial:,None,10/03/2025,None,Data final:,None,None,None,19/12/2025,None
14,Etapas do processo:,None,01- Análise do PPC do curso,None,None,None,None,None,None,None,10/03,19/12
15,,None,02- Reuniões com os NDE e professores,None,None,None,None,None,None,None,10/03,19/12
16,,None,03- Reestruturação do PPC,None,None,None,None,None,None,None,10/03,19/12
17,,None,04- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
18,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
19,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
20,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
21,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
22,Custo R$ (se houver):,None,Não haverá custos,Fonte(s) dos recursos:,None,None,None,Não haverá custos,None,None,None,None
23,Situação problema:,None,cat 0.1.10 - Gestão da unidade de ensino e dos...,None,None,None,None,None,None,None,None,None
24,(a ser resolvida/mitigada),None,cat 0.1.99 - Outra,None,None,None,None,None,None,None,None,None

Tabela 18

                      0                                                  1
0   AÇÃO/PROJETO (Tema)  110 - cat 1.08 - Eventos e ações para aperfeiç...
1  Origem (prioridade):                                            6-Outra

Tabela 19

,0,1,2,3,4,5,6,7,8,9,10,11
0,,None,Promover capacitações para os docentes abordan...,None,None,None,None,None,None,None,None,None
1,O que será feito:,None,None,None,None,None,None,None,None,None,None,None
2,,None,None,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,Para melhoria da qualidade do ensino e para ap...,None,None,None,None,None,None,None,None,None
4,Responsável:,<nome> Direção,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
5,Colaborador(a):,<nome> Coordenação,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
6,,<nome> Juliana Tonon,None,None,None,Qde CH/sem:,None,None,02,Tipo:,H - Hora <não\ntipificada>,None
7,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
8,None,None,None,None,None,,None,None,None,,None,None
9,,None,None,None,None,None,None,None,None,None,None,None
10,Período de execução:,None,Data inicial:,None,10/03/2025,None,Data final:,None,None,None,19/12/2025,None
11,Etapas do processo:,None,01- Estudo das necessidades,None,None,None,None,None,None,None,10/03,19/12
12,,None,02- Pesquisa de cursos de capacitação,None,None,None,None,None,None,None,10/03,19/12
13,,None,03- Desenvolver capacitações aos docentes,None,None,None,None,None,None,None,10/03,19/12
14,,None,04- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
15,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
16,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
17,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
18,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
19,Custo R$ (se houver):,None,Não haverá custos,Fonte(s) dos recursos:,None,None,None,Não haverá custos,None,None,None,None
20,Situação problema:,None,cat 0.1.10 - Gestão da unidade de ensino e dos...,None,None,None,None,None,None,None,None,None
21,(a ser resolvida/mitigada),None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None

Tabela 20

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,111 - cat 1.07 - Divulgação do vestibular e aç...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None,None,None,None
2,,None,Divulgar notícias da instituição e dos cursos ...,None,None,None,None,None,None,None,None,None
3,O que será feito:,None,None,None,None,None,None,None,None,None,None,None
4,,None,None,None,None,None,None,None,None,None,None,None
5,Por que será feito:,None,Para divulgar a Fatec e seus cursos junto à co...,None,None,None,None,None,None,None,None,None
6,,<nome> Mariana Cristina Pontes Dias,None,None,None,Qde CH/sem:,None,None,05,Tipo:,H - Hora <não\ntipificada>,None
7,Responsável:,None,None,None,None,None,None,None,None,None,None,None
8,None,None,None,None,None,,None,None,None,,None,None
9,,None,None,None,None,None,None,None,None,None,None,None
10,,<nome> Laísa Gamito,None,None,None,Qde CH/sem:,None,None,05,Tipo:,H - Hora <não\ntipificada>,None
11,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
12,None,None,None,None,None,,None,None,None,,None,None
13,,None,None,None,None,None,None,None,None,None,None,None
14,,<nome> Administrativo/Coordenação/Direção,None,None,None,Qde CH/sem:,None,None,05,Tipo:,H - Hora <não\ntipificada>,None
15,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
16,None,None,None,None,None,,None,None,None,,None,None
17,,None,None,None,None,None,None,None,None,None,None,None
18,Período de execução:,None,Data inicial:,None,10/03/2025,None,Data final:,None,None,None,19/12/2025,None
19,,None,01- Manter as estratégias institucionais da un...,None,None,None,None,None,None,None,10/03,19/12
20,Etapas do processo:,None,None,None,None,None,None,None,None,None,None,None
21,,None,None,None,None,None,None,None,None,None,None,None
22,,None,02- Disponibilizar conteúdo atualizado nos mei...,None,None,None,None,None,None,None,10/03,19/12
23,,None,None,None,None,None,None,None,None,None,None,None
24,,None,None,None,None,None,None,None,None,None,None,None
25,,None,03- Análise do público das redes sociais e tra...,None,None,None,None,None,None,None,10/03,19/12
26,,None,04- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
27,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
28,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
29,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
30,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
31,Custo R$ (se houver):,None,A ser definido,Fonte(s) dos recursos:,None,None,None,Verba do vestibular (FAT),None,None,None,None
32,Situação problema:,None,cat 0.1.10 - Gestão da unidade de ensino e dos...,None,None,None,None,None,None,None,None,None
33,(a ser resolvida/mitigada),None,cat 0.1.08 - Participação da comunidade e soci...,None,None,None,None,None,None,None,None,None

Tabela 21

,0,1,2,3,4,5,6,7,8
0,AÇÃO/PROJETO (Tema),None,112 - cat 1.07 - Divulgação do vestibular e aç...,None,None,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None
2,O que será feito:,None,Divulgação do vestibular e dos seus cursos,None,None,None,None,None,None
3,Por que será feito:,None,Para divulgar o vestibular da instituição Fate...,None,None,None,None,None,None
4,,<nome> Mariana Cristina Pontes Dias,None,None,Qde CH/sem:,None,05,Tipo:,H - Hora <não\ntipificada>
5,Responsável:,None,None,None,None,None,None,None,None
6,None,None,None,None,,None,None,,None
7,,None,None,None,None,None,None,None,None
8,,<nome> Maria José Cardoso,None,None,Qde CH/sem:,None,01,Tipo:,HAE - Hora Atividade\nEspecífica
9,Colaborador(a):,None,None,None,None,None,None,None,None
10,None,None,None,None,,None,None,,None
11,,None,None,None,None,None,None,None,None
12,,<nome> Administrativo/Coordenação/Direção,None,None,Qde CH/sem:,None,05,Tipo:,H - Hora <não\ntipificada>
13,Colaborador(a):,None,None,None,None,None,None,None,None
14,None,None,None,None,,None,None,,None
15,,None,None,None,None,None,None,None,None
16,Período de execução:,None,Data inicial:,02/01/2025,None,Data final:,None,None,19/12/2025

Tabela 22

,0,1,2,3,4,5
0,,01- Manter as estratégias de divulgação de tod...,None,None,02/01,19/12
1,Etapas do processo:,None,None,None,None,None
2,,None,None,None,None,None
3,,02- Fazer controle da campanha do vestibular n...,None,None,02/01,19/12
4,,03- Realizar visitas em escolas e outros locai...,None,None,02/01,19/12
5,,04- Realizar roda de entrevistas com profissio...,None,None,02/01,19/12
6,,None,None,None,None,None
7,,None,None,None,None,None
8,,"05- Criar materiais, cards, vídeos, fotos de d...",None,None,02/01,19/12
9,,None,None,None,None,None
10,,None,None,None,None,None
11,,06- Divulgação da unidade e de seus cursos jun...,None,None,02/01,19/12
12,,None,None,None,None,None
13,,None,None,None,None,None
14,,07- nn,None,None,dd/mm,dd/mm
15,,08- nn,None,None,dd/mm,dd/mm
16,Custo R$ (se houver):,A ser definido,Fonte(s) dos recursos:,Verba do vestibular (FAT),None,None
17,Situação problema:,cat 0.1.10 - Gestão da unidade de ensino e dos...,None,None,None,None
18,(a ser resolvida/mitigada),cat 0.1.08 - Participação da comunidade e soci...,None,None,None,None

Tabela 23

/usr/local/lib/python3.11/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,101 - cat 1.04 - Biblioteca Ativa e aquisição ...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Promover o uso da biblioteca da unidade,None,None,None,None,None,None,None,None,None
3,,None,Planejamento/ organização/ instalação de infra...,None,None,None,None,None,None,None,None,None
4,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
5,,None,None,None,None,None,None,None,None,None,None,None
6,,<nome> Diego Aparecido carvalho Albuquerque,None,None,None,Qde CH/sem:,None,None,15,Tipo:,HAE - Hora Atividade\nEspecífica,None
7,Responsável:,None,None,None,None,None,None,None,None,None,None,None
8,None,None,None,None,None,,None,None,None,,None,None
9,,None,None,None,None,None,None,None,None,None,None,None
10,,<nome> Juliana Ribeiro de Lima,None,None,None,Qde CH/sem:,None,None,5,Tipo:,HAE - Hora Atividade\nEspecífica,None
11,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
12,None,None,None,None,None,,None,None,None,,None,None
13,,None,None,None,None,None,None,None,None,None,None,None
14,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
15,Período de execução:,None,Data inicial:,None,19/02/2024,None,Data final:,None,None,None,20/12/2024,None
16,Etapas do processo:,None,01- Planejamento e levantamento das ações a se...,None,None,None,None,None,None,None,19/02,23/02
17,,None,02- Definição da lista dos livros de acordo co...,None,None,None,None,None,None,None,26/02,15/03
18,,None,03- Envio da lista de livros para compra na CESU,None,None,None,None,None,None,None,18/03,28/03
19,,None,04- Dar a continuidade a Biblioteca Ativa.,None,None,None,None,None,None,None,19/02,20/12
20,,None,05- Digitação do acervo da biblioteca recebido,None,None,None,None,None,None,None,19/02,20/12
21,,None,06- Instalação de software para professor resp...,None,None,None,None,None,None,None,19/02,20/12
22,,None,None,None,None,None,None,None,None,None,None,None
23,,None,None,None,None,None,None,None,None,None,None,None
24,,None,07- nr,None,None,None,None,None,None,None,dd/mm,dd/mm
25,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
26,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
27,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
28,(a ser resolvida/mitigada),None,"cat 0.1.03 - Infraestrutura predial (espaços, ...",None,None,None,None,None,None,None,None,None

Tabela 24

,0,1,2,3,4,5,6,7,8,9,10,11
0,,None,102 - cat 1.06 - Ações pedagógicas: visitas té...,None,None,None,None,None,None,None,None,None
1,AÇÃO/PROJETO (Tema),None,None,None,None,None,None,None,None,None,None,None
2,,None,None,None,None,None,None,None,None,None,None,None
3,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
4,,None,"Visitas técnicas as empresas da região, feira ...",None,None,None,None,None,None,None,None,None
5,O que será feito:,None,None,None,None,None,None,None,None,None,None,None
6,,None,None,None,None,None,None,None,None,None,None,None
7,,None,Para que os alunos tenham contato com o conhec...,None,None,None,None,None,None,None,None,None
8,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
9,,None,None,None,None,None,None,None,None,None,None,None
10,,<nome> Dilermano Piva Júnior - Angelina V. S. ...,None,None,None,Qde CH/sem:,None,None,2,Tipo:,HA - Hora Atividade,None
11,Responsável:,None,None,None,None,None,None,None,None,None,None,None
12,None,None,None,None,None,,None,None,None,,None,None
13,,None,None,None,None,None,None,None,None,None,None,None
14,Colaborador(a):,<nome>,None,None,None,Qde CH/sem:,None,None,2,Tipo:,HA - Hora Atividade,None
15,Colaborador(a):,<nome>,None,None,None,Qde CH/sem:,None,None,2,Tipo:,HA - Hora Atividade,None
16,Período de execução:,None,Data inicial:,None,02/02/2024,None,Data final:,None,None,None,20/12/2024,None
17,Etapas do processo:,None,01- Verificar junto aos professores as possíve...,None,None,None,None,None,None,None,01/02,20/12
18,,None,02- Fazer o contato e o levantamento das empre...,None,None,None,None,None,None,None,01/02,20/12
19,,None,03- Verificar quais os professores responsávei...,None,None,None,None,None,None,None,01/02,20/12
20,,None,04- Fazer o agendamento com as empresas,None,None,None,None,None,None,None,01/02,20/12
21,,None,05- Verificar as datas das semanas de Tecnolog...,None,None,None,None,None,None,None,01/02,20/12
22,,None,06- Agendar as visitas e empresas parceiras,None,None,None,None,None,None,None,01/02,20/12
23,,None,07- Verificar a possibilidade de transporte ju...,None,None,None,None,None,None,None,01/02,20/12
24,,None,08- nn,None,None,None,None,None,None,None,01/02,20/12
25,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
26,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
27,(a ser resolvida/mitigada),None,Escolher um item.,None,None,None,None,None,None,None,None,None

Tabela 25

,0,1,2,3,4,5,6,7,8,9,10,11
0,,None,103 - cat 1.06 - Ações pedagógicas: visitas té...,None,None,None,None,None,None,None,None,None
1,AÇÃO/PROJETO (Tema),None,None,None,None,None,None,None,None,None,None,None
2,,None,None,None,None,None,None,None,None,None,None,None
3,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
4,O que será feito:,None,Participação do Hachathon entre cursos de tecn...,None,None,None,None,None,None,None,None,None
5,,None,Para que os alunos tenham maior conhecimento s...,None,None,None,None,None,None,None,None,None
6,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
7,,None,None,None,None,None,None,None,None,None,None,None
8,Responsável:,<nome> Dilermano Piva Júnior - Angelina V. S. ...,None,None,None,Qde CH/sem:,None,None,2,Tipo:,HA - Hora Atividade,None
9,Colaborador(a):,<nome>,None,None,None,Qde CH/sem:,None,None,2,Tipo:,HA - Hora Atividade,None
10,Colaborador(a):,<nome>,None,None,None,Qde CH/sem:,None,None,2,Tipo:,HA - Hora Atividade,None
11,Período de execução:,None,Data inicial:,None,02/02/2024,None,Data final:,None,None,None,20/12/2024,None
12,Etapas do processo:,None,Organizar participação em evento,None,None,None,None,None,None,None,01/02,20/12
13,,None,Definir alunos de cada curso,None,None,None,None,None,None,None,01/02,20/12
14,,None,Convidar professores para participarem,None,None,None,None,None,None,None,01/02,20/12
15,,None,Participar no dia do evento,None,None,None,None,None,None,None,01/02,10/12
16,,None,,None,None,None,None,None,None,None,,
17,,None,,None,None,None,None,None,None,None,,
18,,None,,None,None,None,None,None,None,None,,
19,,None,,None,None,None,None,None,None,None,,
20,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
21,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
22,(a ser resolvida/mitigada),None,Escolher um item.,None,None,None,None,None,None,None,None,None

Tabela 26

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,104 - cat 1.14 - Curso de Extensão,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Participação em Cursos entre Fatecs l,None,None,None,None,None,None,None,None,None
3,,None,Para que os alunos tenham maior conhecimento s...,None,None,None,None,None,None,None,None,None
4,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
5,,None,None,None,None,None,None,None,None,None,None,None
6,Responsável:,<nome> Angelina V. S. Milaré,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
7,Colaborador(a):,<nome> Dilermando Piva Júnior,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
8,Colaborador(a):,<nome> Lígia C. P. Agasi,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
9,Período de execução:,None,Data inicial:,None,05/02/2024,None,Data final:,None,None,None,20/12/2024,None
10,Etapas do processo:,None,01- Planejar e fazer parcerias de cursos entre...,None,None,None,None,None,None,None,05/02,05/08
11,,None,02- Organizar participação em eventos,None,None,None,None,None,None,None,05/02,05/08
12,,None,03- Criação de formulário de inscrição,None,None,None,None,None,None,None,15/02,20/12
13,,None,04- Divulgar formulários a comunidade docente ...,None,None,None,None,None,None,None,15/02,20/12
14,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
15,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
16,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
17,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
18,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
19,Situação problema:,None,cat 0.1.07 - Comunicação com a comunidade acad...,None,None,None,None,None,None,None,None,None
20,(a ser resolvida/mitigada),None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None

Tabela 27

,0,1,2,3,4,5,6,7,8,9
0,,None,105 - cat 1.06 - Ações pedagógicas: visitas té...,None,None,None,None,None,None,None
1,AÇÃO/PROJETO (Tema),None,None,None,None,None,None,None,None,None
2,,None,None,None,None,None,None,None,None,None
3,Origem:,None,3-Outra,None,None,None,None,None,None,None
4,O que será feito:,None,Participação do Projeto Escola de Inovadores d...,None,None,None,None,None,None,None
5,,None,Os alunos irão participar de um curso de exten...,None,None,None,None,None,None,None
6,Por que será feito:,None,None,None,None,None,None,None,None,None
7,,None,None,None,None,None,None,None,None,None
8,Responsável:,<nome> Angelina S. V. Milaré,None,None,Qde CH/sem:,None,02,Tipo:,HA - Hora Atividade,None
9,Colaborador(a):,<nome> Dilermando Piva Júnior,None,None,Qde CH/sem:,None,02,Tipo:,HA - Hora Atividade,None
10,Colaborador(a):,<nome> Lígia C. P. Agasi,None,None,Qde CH/sem:,None,02,Tipo:,HA - Hora Atividade,None
11,Período de execução:,None,Data inicial:,02/02/2024,None,Data final:,None,None,31/12/2024,None
12,Etapas do processo:,None,01- Agendar palestra com a Agente Regional do ...,None,None,None,None,None,dd/mm,dd/mm
13,,None,02- Divulgar e motivar a participação dos alun...,None,None,None,None,None,dd/mm,dd/mm
14,,None,03- Inscrição dos alunos,None,None,None,None,None,dd/mm,dd/mm

Tabela 28

,0,1,2,3,4,5
0,,04- Incentivar a participação continuada dos a...,None,None,dd/mm,dd/mm
1,,05- nn,None,None,dd/mm,dd/mm
2,,06- nn,None,None,dd/mm,dd/mm
3,,07- nn,None,None,dd/mm,dd/mm
4,,08- nn,None,None,dd/mm,dd/mm
5,Custo R$ (se houver):,nn,Fonte(s) dos recursos:,nn,None,None
6,Situação problema:,cat 0.1.13 - Relacionamento interpessoal da eq...,None,None,None,None
7,(a ser resolvida/mitigada),Escolher um item.,None,None,None,None

Tabela 29

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,106 - cat 1.12 - Orientação profissional para ...,None,None,None,None,None,None,None,None,None
1,Origem:,None,3-Outra,None,None,None,None,None,None,None,None,None
2,,None,Criação e estruturação do núcleo de empregabil...,None,None,None,None,None,None,None,None,None
3,O que será feito:,None,None,None,None,None,None,None,None,None,None,None
4,,None,None,None,None,None,None,None,None,None,None,None
5,Por que será feito:,None,"Proporcionar empregabilidade, recolocação prof...",None,None,None,None,None,None,None,None,None
6,Responsável:,<nome> Angelina S. V. Milaré,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
7,Colaborador(a):,<nome> Dilermando Piva Júnior,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
8,Colaborador(a):,<nome> Lígia C. P. Agasi,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
9,Período de execução:,None,Data inicial:,None,02/02/2024,None,Data final:,None,None,None,31/12/2024,None
10,,None,Análise do PPC dos cursos e aprovação da propo...,None,None,None,None,None,None,None,dd/mm,dd/mm
11,Etapas do processo:,None,None,None,None,None,None,None,None,None,None,None
12,,None,None,None,None,None,None,None,None,None,None,None
13,,None,Levantamento de perfil e motivações,None,None,None,None,None,None,None,dd/mm,dd/mm
14,,None,Desenvolvimento de currículo,None,None,None,None,None,None,None,dd/mm,dd/mm
15,,None,,None,None,None,None,None,None,None,,
16,,None,,None,None,None,None,None,None,None,,
17,,None,,None,None,None,None,None,None,None,,
18,,None,,None,None,None,None,None,None,None,,
19,,None,,None,None,None,None,None,None,None,,
20,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
21,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
22,(a ser resolvida/mitigada),None,Escolher um item.,None,None,None,None,None,None,None,None,None

Tabela 30

                                                   0
0  02 – Laboratórios - Ensino e Equipamentos Asso...
1  Ações para melhoramento dos laboratórios de En...
2  equipamentos, mediante instalação, manutenção,...

Tabela 31

,0,1,2,3,4,5,6,7,8,9,10,11
0,,None,201 - cat 2.03 - Ambiente multidisciplinar de ...,None,None,None,None,None,None,None,None,None
1,AÇÃO/PROJETO (Tema),None,None,None,None,None,None,None,None,None,None,None
2,,None,None,None,None,None,None,None,None,None,None,None
3,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None,None,None,None
4,O que será feito:,None,Laboratório Maker - Planejamento/ instalação d...,None,None,None,None,None,None,None,None,None
5,Por que será feito:,None,Para uso do Laboratório Maker para desenvolvim...,None,None,None,None,None,None,None,None,None
6,Responsável:,<nome> Angelina S. V. Melaré,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
7,,<nome> Juliana Lima,None,None,None,Qde CH/sem:,None,None,05,Tipo:,HAE - Hora Atividade\nEspecífica,None
8,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
9,None,None,None,None,None,,None,None,None,,None,None
10,,None,None,None,None,None,None,None,None,None,None,None
11,,<nome> Adriana Barros,None,None,None,Qde CH/sem:,None,None,02,Tipo:,H - Hora <não\ntipificada>,None
12,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
13,None,None,None,None,None,,None,None,None,,None,None
14,,None,None,None,None,None,None,None,None,None,None,None
15,Período de execução:,None,Data inicial:,None,03/02/2025,None,Data final:,None,None,None,19/12/2025,None
16,Etapas do processo:,None,01- Organização do espaço do laboratório,None,None,None,None,None,None,None,03/02,19/12
17,,None,02- Compra de insumos,None,None,None,None,None,None,None,03/02,19/12
18,,None,03- Definição de projetos a serem executados p...,None,None,None,None,None,None,None,03/02,19/12
19,,None,04- Treinamento dos docentes e auxiliar docente,None,None,None,None,None,None,None,03/02,19/12
20,,None,05- Treinamento dos discentes,None,None,None,None,None,None,None,03/02,19/12
21,,None,06- Oferecimento de cursos a comunidade,None,None,None,None,None,None,None,03/02,19/12
22,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
23,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
24,Custo R$ (se houver):,None,A ser definido,Fonte(s) dos recursos:,None,None,None,"DMPP, Centro Paula Souza (Licitação)",None,None,None,None
25,Situação problema:,None,cat 0.1.04 - Infraestrutura laboratorial e amb...,None,None,None,None,None,None,None,None,None
26,(a ser resolvida/mitigada),None,Escolher um item.,None,None,None,None,None,None,None,None,None

Tabela 32

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,202 - cat 2.01 - Laboratório físico - implanta...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Obtenção e estruturação dos Laboratórios,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,Melhoria no aprendizado e atendimento ao PPC d...,None,None,None,None,None,None,None,None,None
4,,<nome> Lígia C. P. Agasi/ Dilermando Piva Júni...,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
5,Responsável:,None,None,None,None,None,None,None,None,None,None,None
6,None,None,None,None,None,,None,None,None,,None,None
7,,None,None,None,None,None,None,None,None,None,None,None
8,,<nome> Adriana / Laísa/ Mariana/Eliana,None,None,None,Qde CH/sem:,None,None,02,Tipo:,H - Hora <não\ntipificada>,None
9,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
10,None,None,None,None,None,,None,None,None,,None,None
11,,None,None,None,None,None,None,None,None,None,None,None
12,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
13,Período de execução:,None,Data inicial:,None,03/02/2025,None,Data final:,None,None,None,19/12/2025,None
14,Etapas do processo:,None,"01- Levantamento dos equipamentos, mobiliário ...",None,None,None,None,None,None,None,03/02,19/12
15,,None,02- Atualização de necessidades para licitação...,None,None,None,None,None,None,None,03/02,19/12
16,,None,03- Encaminhamento via SEI para UGAF para aqui...,None,None,None,None,None,None,None,03/02,19/12
17,,None,04- Recebimento equipamentos,None,None,None,None,None,None,None,03/02,19/12
18,,None,05- Instalação dos equipamentos e mobiliários,None,None,None,None,None,None,None,03/02,19/12
19,,None,06- Treinamento dos docentes e auxiliar docente,None,None,None,None,None,None,None,03/02,19/12
20,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
21,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
22,Custo R$ (se houver):,None,A ser definido,Fonte(s) dos recursos:,None,None,None,UGAF/Centro Paula Souza (Licitação),None,None,None,None
23,Situação problema:,None,cat 0.1.04 - Infraestrutura laboratorial e amb...,None,None,None,None,None,None,None,None,None
24,(a ser resolvida/mitigada),None,"cat 0.1.05 - Materiais, equipamentos e mobiliá...",None,None,None,None,None,None,None,None,None

Tabela 33

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,203 - Escolher um item.,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,Escolher um item.,None,None,None,None,None,None,None,None,None
2,O que será feito:,None,nn,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,nn,None,None,None,None,None,None,None,None,None
4,Responsável:,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
5,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
6,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
7,Período de execução:,None,Data inicial:,None,dd/mm/aaaa,None,Data final:,None,None,None,dd/mm/aaaa,None
8,Etapas do processo:,None,01- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
9,,None,02- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
10,,None,03- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
11,,None,04- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
12,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
13,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
14,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
15,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
16,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
17,Situação problema:,None,Escolher um item.,None,None,None,None,None,None,None,None,None
18,(a ser resolvida/mitigada),None,Escolher um item.,None,None,None,None,None,None,None,None,None

Tabela 34

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,204 - Escolher um item.,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,Escolher um item.,None,None,None,None,None,None,None,None,None
2,O que será feito:,None,nn,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,nn,None,None,None,None,None,None,None,None,None
4,Responsável:,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
5,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
6,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
7,Período de execução:,None,Data inicial:,None,dd/mm/aaaa,None,Data final:,None,None,None,dd/mm/aaaa,None
8,Etapas do processo:,None,01- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
9,,None,02- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
10,,None,03- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
11,,None,04- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
12,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
13,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
14,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
15,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
16,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
17,Situação problema:,None,Escolher um item.,None,None,None,None,None,None,None,None,None
18,(a ser resolvida/mitigada),None,Escolher um item.,None,None,None,None,None,None,None,None,None

Tabela 35

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,201 - cat 2.01 - Laboratório físico - implanta...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None,None,None,None
2,(O que será feito:,None,Laboratório Maker- Planejamento/ instalação de...,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,Para uso do Laboratório Maker para desenvolvim...,None,None,None,None,None,None,None,None,None
4,Responsável:,<nome> Angelina S. V. Milaré,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
5,,<nome> André Almeida,None,None,None,Qde CH/sem:,None,None,03,Tipo:,HAE - Hora Atividade\nEspecífica,None
6,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
7,None,None,None,None,None,,None,None,None,,None,None
8,,None,None,None,None,None,None,None,None,None,None,None
9,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
10,Período de execução:,None,Data inicial:,None,02/02/2024,None,Data final:,None,None,None,31/12/2024,None
11,Etapas do processo:,None,01- Organização do espaço do laboratório,None,None,None,None,None,None,None,dd/mm,dd/mm
12,,None,02- Compra de insumos,None,None,None,None,None,None,None,dd/mm,dd/mm
13,,None,03- Definição de projetos a serem executados p...,None,None,None,None,None,None,None,dd/mm,dd/mm
14,,None,04- Treinamento dos docentes e Auxiliar Docente,None,None,None,None,None,None,None,dd/mm,dd/mm
15,,None,05- Treinamento dos discentes,None,None,None,None,None,None,None,dd/mm,dd/mm
16,,None,06- Oferecimentos de curso a comunidade.,None,None,None,None,None,None,None,dd/mm,dd/mm
17,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
18,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
19,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
20,Situação problema:,None,cat 0.1.04 - Infraestrutura laboratorial e amb...,None,None,None,None,None,None,None,None,None
21,(a ser resolvida/mitigada),None,cat 0.1.04 - Infraestrutura laboratorial e amb...,None,None,None,None,None,None,None,None,None

Tabela 36

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,202 - cat 2.01 - Laboratório físico - implanta...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Obtenção e Estruturação dos Laboratórios,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,Melhoria no aprendizado e atendendo ao PCC do ...,None,None,None,None,None,None,None,None,None
4,Responsável:,<nome> Angelina V. S. Milaré,None,None,None,Qde CH/sem:,None,None,40,Tipo:,HA - Hora Atividade,None
5,Colaborador(a):,<nome> Dilermando Piva Júnior,None,None,None,Qde CH/sem:,None,None,40,Tipo:,HA - Hora Atividade,None
6,Colaborador(a):,<nome> Lígia C. P. Agasi,None,None,None,Qde CH/sem:,None,None,40,Tipo:,HA - Hora Atividade,None
7,Período de execução:,None,Data inicial:,None,01/02/2024,None,Data final:,None,None,None,31/12/2024,None
8,Etapas do processo:,None,"01- Levantamento dos equipamentos, mobiliário ...",None,None,None,None,None,None,None,01/02,05/02
9,,None,02- Atualização dos Orçamentos para Licitação,None,None,None,None,None,None,None,01/02,05/02
10,,None,03- Encaminhamento a SEI e UGAF para aquisição,None,None,None,None,None,None,None,05/02,19/02
11,,None,04- Recebimento equipamentos,None,None,None,None,None,None,None,04/03,28/03
12,,None,05- Instalação dos equipamentos e mobiliários,None,None,None,None,None,None,None,04/03,28/03
13,,None,06- Treinamento dos docentes e Auxiliar docente,None,None,None,None,None,None,None,04/03,28/03
14,,None,07- Promover 50% das aulas técnica em laborató...,None,None,None,None,None,None,None,01/04,31/12
15,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
16,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,UGAF,None,None,None,None
17,Situação problema:,None,cat 0.1.04 - Infraestrutura laboratorial e amb...,None,None,None,None,None,None,None,None,None
18,(a ser resolvida/mitigada),None,"cat 0.1.05 - Materiais, equipamentos e mobiliá...",None,None,None,None,None,None,None,None,None

Tabela 37

                      0                        1
0   AÇÃO/PROJETO (Tema)  20w - Escolher um item.
1  Origem (prioridade):        Escolher um item.

Tabela 38

                      0                        1
0   AÇÃO/PROJETO (Tema)  20z - Escolher um item.
1  Origem (prioridade):        Escolher um item.

Tabela 39

                                                   0
0  03 – Pesquisa / Extensão e Equipamentos Associ...
1  Ações para melhoramento dos laboratórios que c...
2  melhoramento dos espaços de pesquisa, que incl...
3  projeto com empresa, e também prestação de ser...

Tabela 40

/usr/local/lib/python3.11/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,301 - cat 3.02 - Desenvolvimento de Projetos d...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Pesquisa de Sistemas Multiplataformas para Cid...,None,None,None,None,None,None,None,None,None
3,,None,Promover a pesquisa entre professores e alunos...,None,None,None,None,None,None,None,None,None
4,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
5,,None,None,None,None,None,None,None,None,None,None,None
6,Responsável:,<nome> Angelina V. S. Melaré,None,None,None,Qde CH/sem:,None,None,02,Tipo:,Escolher um item.,None
7,Colaborador(a):,<nome> Dilermando Piva Júnior,None,None,None,Qde CH/sem:,None,None,02,Tipo:,Escolher um item.,None
8,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
9,Período de execução:,None,Data inicial:,None,17/02/2025,None,Data final:,None,None,None,19/12/2025,None
10,Etapas do processo:,None,01- Comunicação/conscientização do corpo disce...,None,None,None,None,None,None,None,17/12,31/03
11,,None,02- Criação de equipes integradas dos cursos –...,None,None,None,None,None,None,None,17/12,31/03
12,,None,03- Definição dos temas de pesquisa de cada grupo,None,None,None,None,None,None,None,01/04,11/04
13,,None,04- Cronograma de pesquisa e Início de projeto...,None,None,None,None,None,None,None,01/04,19/12
14,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
15,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
16,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
17,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
18,Custo R$ (se houver):,None,Não haverá custos,Fonte(s) dos recursos:,None,None,None,Não haverá custos,None,None,None,None
19,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
20,(a ser resolvida/mitigada),None,cat 0.1.08 - Participação da comunidade e soci...,None,None,None,None,None,None,None,None,None

Tabela 41

/usr/local/lib/python3.11/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,302 - cat 3.02 - Desenvolvimento de Projetos d...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Pesquisa de Sistemas Multiplataformas para ate...,None,None,None,None,None,None,None,None,None
3,,None,Promover a pesquisa entre professores e alunos...,None,None,None,None,None,None,None,None,None
4,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
5,,None,None,None,None,None,None,None,None,None,None,None
6,Responsável:,<nome> Angelina V. S. Melaré,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
7,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
8,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
9,Período de execução:,None,Data inicial:,None,17/02/2025,None,Data final:,None,None,None,19/12/2025,None
10,,None,01- Comunicação/conscientização do corpo disce...,None,None,None,None,None,None,None,17/12,31/03
11,Etapas do processo:,None,None,None,None,None,None,None,None,None,None,None
12,,None,None,None,None,None,None,None,None,None,None,None
13,,None,02- Criação de equipes integradas dos cursos –...,None,None,None,None,None,None,None,17/12,31/03
14,,None,03- Definição de pesquisas de cada grupo‐ com ...,None,None,None,None,None,None,None,01/04,11/04
15,,None,04- Início de projetos de pesquisa,None,None,None,None,None,None,None,01/04,19/12
16,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
17,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
18,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
19,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
20,Custo R$ (se houver):,None,Não haverá custos,Fonte(s) dos recursos:,None,None,None,Não haverá custos,None,None,None,None
21,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
22,(a ser resolvida/mitigada),None,Escolher um item.,None,None,None,None,None,None,None,None,None

Tabela 42

/usr/local/lib/python3.11/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,303 - cat 3.02 - Desenvolvimento de Projetos d...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Monitoria de disciplinas e de Iniciação Cientí...,None,None,None,None,None,None,None,None,None
3,,None,Promover a pesquisa em conjunto com o corpo do...,None,None,None,None,None,None,None,None,None
4,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
5,,None,None,None,None,None,None,None,None,None,None,None
6,Responsável:,<nome> Angelina V. S. Melaré,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
7,Colaborador(a):,<nome> Dilermando Piva Júnior,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
8,Colaborador(a):,<nome> Lígia C. P. Agasi,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
9,Período de execução:,None,Data inicial:,None,17/02/2025,None,Data final:,None,None,None,19/12/2025,None
10,,None,01- Comunicação/conscientização do corpo disce...,None,None,None,None,None,None,None,17/02,19/12
11,Etapas do processo:,None,None,None,None,None,None,None,None,None,None,None
12,,None,None,None,None,None,None,None,None,None,None,None
13,,None,02- Criação de equipes integradas dos cursos –...,None,None,None,None,None,None,None,17/02,19/12
14,,None,03- Definição de pesquisas de cada grupo‐ com ...,None,None,None,None,None,None,None,17/02,19/12
15,,None,04- Desenvolvimento de projetos de pesquisa,None,None,None,None,None,None,None,17/02,19/12
16,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
17,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
18,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
19,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
20,Custo R$ (se houver):,None,Não haverá custos,Fonte(s) dos recursos:,None,None,None,Não haverá custos,None,None,None,None
21,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
22,(a ser resolvida/mitigada),None,cat 0.1.08 - Participação da comunidade e soci...,None,None,None,None,None,None,None,None,None

Tabela 43

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,304 - cat 3.01 - Cursos de Extensão,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Desenvolvimento de projeto de extensão para a ...,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,Promover cursos que auxiliem o crescimento da ...,None,None,None,None,None,None,None,None,None
4,Responsável:,<nome> Angelina V. S. Melaré,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
5,Colaborador(a):,<nome> Dilermando Piva Júnior,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
6,Colaborador(a):,<nome> Lígia C.P. Agasi,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
7,Período de execução:,None,Data inicial:,None,02/01/2025,None,Data final:,None,None,None,19/12/2025,None
8,Etapas do processo:,None,01- Análise de necessidades de cursos de extensão,None,None,None,None,None,None,None,02/01,19/12
9,,None,02- Criação de formulário de inscrição,None,None,None,None,None,None,None,02/01,19/12
10,,None,03- Divulgação de cursos de extensão,None,None,None,None,None,None,None,02/01,19/12
11,,None,04- Organização do curso,None,None,None,None,None,None,None,02/01,19/12
12,,None,05- Aquisição de materiais e insumos necessários,None,None,None,None,None,None,None,02/01,19/12
13,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
14,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
15,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
16,Custo R$ (se houver):,None,A ser definido,Fonte(s) dos recursos:,None,None,None,"DMPP, Centro Paula Souza (Licitação)",None,None,None,None
17,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
18,(a ser resolvida/mitigada),None,cat 0.1.08 - Participação da comunidade e soci...,None,None,None,None,None,None,None,None,None

Tabela 44

/usr/local/lib/python3.11/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,0,1,2,3,4,5,6,7,8,9
0,AÇÃO/PROJETO (Tema),None,305 - cat 3.01 - Cursos de Extensão,None,None,None,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None,None
2,O que será feito:,None,Aulas de AutoCAD,None,None,None,None,None,None,None
3,Por que será feito:,None,Oferecer uma formação de AutoCAD aos alunos,None,None,None,None,None,None,None
4,Responsável:,<nome> Lígia C. P. Agasi,None,None,Qde CH/sem:,None,02,Tipo:,HA - Hora Atividade,None
5,,<nome> Paulo Cesar Juliano,None,None,Qde CH/sem:,None,03,Tipo:,HAE - Hora Atividade\nEspecífica,None
6,Colaborador(a):,None,None,None,None,None,None,None,None,None
7,None,None,None,None,,None,None,,None,None
8,,None,None,None,None,None,None,None,None,None
9,Colaborador(a):,<nome> nn,None,None,Qde CH/sem:,None,nn,Tipo:,Escolher um item.,None
10,Período de execução:,None,Data inicial:,17/02/2025,None,Data final:,None,None,19/12/2025,None
11,Etapas do processo:,None,01- Comunicação/ Conscientização do corpo disc...,None,None,None,None,None,17/02,19/12
12,,None,02- Inscrições dos alunos e comunidade,None,None,None,None,None,17/02,19/12
13,,None,03- Início de Aulas,None,None,None,None,None,17/02,19/12
14,,None,04- Avaliação de aprendizagem,None,None,None,None,None,17/02,19/12
15,,None,05- nn,None,None,None,None,None,dd/mm,dd/mm
16,,None,06- nn,None,None,None,None,None,dd/mm,dd/mm

Tabela 45

,0,1,2,3,4,5
0,,07- nn,None,None,dd/mm,dd/mm
1,,08- nn,None,None,dd/mm,dd/mm
2,Custo R$ (se houver):,Não haverá custos,Fonte(s) dos recursos:,Não haverá custos,None,None
3,Situação problema:,cat 0.1.07 - Comunicação com a comunidade acad...,None,None,None,None
4,(a ser resolvida/mitigada),cat 0.1.08 - Participação da comunidade e soci...,None,None,None,None

Tabela 46

/usr/local/lib/python3.11/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,306 - cat 3.02 - Desenvolvimento de Projetos d...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None,None,None,None
2,O que será feito:,None,"Estudo, Pesquisa e extensão - SIMET & NEPA",None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,Estação Meteorológica instalada na Fatec Votor...,None,None,None,None,None,None,None,None,None
4,,<nome> José Carlos Ferreira,None,None,None,Qde CH/sem:,None,None,05,Tipo:,HAE - Hora Atividade\nEspecífica,None
5,Responsável:,None,None,None,None,None,None,None,None,None,None,None
6,None,None,None,None,None,,None,None,None,,None,None
7,,None,None,None,None,None,None,None,None,None,None,None
8,Colaborador(a):,<nome> Angelina Vitorino de Souza Melaré,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
9,,<nome> Rodrigo de Paula Diver,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HAE - Hora Atividade\nEspecífica,None
10,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
11,None,None,None,None,None,,None,None,None,,None,None
12,,None,None,None,None,None,None,None,None,None,None,None
13,Período de execução:,None,Data inicial:,None,17/02/2025,None,Data final:,None,None,None,19/12/2025,None
14,Etapas do processo:,None,01- Instalação e Manutenção da Estação Meteoro...,None,None,None,None,None,None,None,17/02,19/12
15,,None,02- Coleta de dados diário,None,None,None,None,None,None,None,17/02,19/12
16,,None,03- Tratamento de dados,None,None,None,None,None,None,None,17/02,19/12
17,,None,04- Pesquisa,None,None,None,None,None,None,None,17/02,19/12
18,,None,05- Estudos,None,None,None,None,None,None,None,17/02,19/12
19,,None,06- Produção de artigos em Publicações,None,None,None,None,None,None,None,17/02,19/12
20,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
21,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
22,Custo R$ (se houver):,None,Não haverá custos,Fonte(s) dos recursos:,None,None,None,Não haverá custos,None,None,None,None
23,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
24,(a ser resolvida/mitigada),None,cat 0.1.08 - Participação da comunidade e soci...,None,None,None,None,None,None,None,None,None

Tabela 47

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,307 - cat 3.02 - Desenvolvimento de Projetos d...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Pesquisa sobre Visão Computacional.,None,None,None,None,None,None,None,None,None
3,,None,Estimular a pesquisa entre o corpo docente e d...,None,None,None,None,None,None,None,None,None
4,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
5,,None,None,None,None,None,None,None,None,None,None,None
6,Responsável:,<nome> Dilermando Piva Junior,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
7,Colaborador(a):,<nome> Angelina Vitorino de Souza Melaré,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
8,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
9,Período de execução:,None,Data inicial:,None,03/02/2025,None,Data final:,None,None,None,19/12/2025,None
10,Etapas do processo:,None,01- Criação de equipes integradas dos cursos –...,None,None,None,None,None,None,None,03/02,31/03
11,,None,02- Definição de pesquisas de cada grupo‐ com ...,None,None,None,None,None,None,None,03/02,31/03
12,,None,03- Desenvolvimento de Projeto,None,None,None,None,None,None,None,01/04,19/12
13,,None,04- Aquisição de materiais e insumos necessári...,None,None,None,None,None,None,None,01/04,19/12
14,,None,None,None,None,None,None,None,None,None,None,None
15,,None,None,None,None,None,None,None,None,None,None,None
16,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
17,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
18,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
19,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
20,Custo R$ (se houver):,None,A ser definido,Fonte(s) dos recursos:,None,None,None,"DMPP, Centro Paula Souza (Licitação)",None,None,None,None
21,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
22,(a ser resolvida/mitigada),None,cat 0.1.11 - Segurança pessoal e patrimonial,None,None,None,None,None,None,None,None,None

Tabela 48

,0,1,2,3,4,5,6
0,AÇÃO/PROJETO (Tema),None,307 - cat 3.02 - Desenvolvimento de Projetos d...,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None
2,O que será feito:,None,Pesquisa de Iniciação Científica e Tecnológica...,None,None,None,None
3,,None,Incentivar os alunos do curso Controle de Obra...,None,None,None,None
4,Por que será feito:,None,None,None,None,None,None
5,,None,None,None,None,None,None
6,Responsável:,<nome> Lígia Conceição Pereira Agasi,None,Qde CH/sem:,02,Tipo:,HA - Hora Atividade

Tabela 49

,0,1,2,3,4,5,6,7,8,9,10,11
0,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
1,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
2,Período de execução:,None,Data inicial:,None,03/02/2025,None,Data final:,None,None,None,19/12/2025,None
3,,None,"01- Solicitação, pelo Comitê de Bacias do Rio ...",None,None,None,None,None,None,None,03/02,07/03
4,Etapas do processo:,None,None,None,None,None,None,None,None,None,None,None
5,,None,None,None,None,None,None,None,None,None,None,None
6,,None,02- Aproximar os alunos com demandas futuras d...,None,None,None,None,None,None,None,03/02,07/03
7,,None,03- Início da Orientação dos alunos,None,None,None,None,None,None,None,17/02,19/12
8,,None,"04- Pesquisa em livros, sites e registros acad...",None,None,None,None,None,None,None,17/02,17/04
9,,None,05- Coleta de dados e formatação da pesquisa,None,None,None,None,None,None,None,17/02,31/03
10,,None,06- Participação no evento “Semana da Água” co...,None,None,None,None,None,None,None,01/04,30/04
11,,None,None,None,None,None,None,None,None,None,None,None
12,,None,None,None,None,None,None,None,None,None,None,None
13,,None,07- Conclusão da primeira etapa da pesquisa,None,None,None,None,None,None,None,17/02,19/12
14,,None,08- Escrita de Artigos e Publicação do mesmo e...,None,None,None,None,None,None,None,17/02,19/12
15,,None,None,None,None,None,None,None,None,None,None,None
16,,None,None,None,None,None,None,None,None,None,None,None
17,Custo R$ (se houver):,None,Bolsa Monitoria,Fonte(s) dos recursos:,None,None,None,CPS,None,None,None,None
18,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
19,(a ser resolvida/mitigada),None,cat 0.1.08 - Participação da comunidade e soci...,None,None,None,None,None,None,None,None,None

Tabela 50

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,301 - cat 3.02 - Desenvolvimento de Projetos d...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Pesquisa de Sistemas Multiplataformas para Cid...,None,None,None,None,None,None,None,None,None
3,,None,Estimular a pesquisa junto ao corpo docente e ...,None,None,None,None,None,None,None,None,None
4,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
5,,None,None,None,None,None,None,None,None,None,None,None
6,Responsável:,<nome> Angelina V. S. Melaré,None,None,None,Qde CH/sem:,None,None,02,Tipo:,Escolher um item.,None
7,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
8,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
9,Período de execução:,None,Data inicial:,None,01/02/2024,None,Data final:,None,None,None,31/12/2024,None
10,,None,01- Comunicação/ Conscientização do corpo disc...,None,None,None,None,None,None,None,01/02,30/03
11,Etapas do processo:,None,None,None,None,None,None,None,None,None,None,None
12,,None,None,None,None,None,None,None,None,None,None,None
13,,None,02- Criação de equipes integradas dos cursos –...,None,None,None,None,None,None,None,01/02,30/03
14,,None,03- Definição dos temas de pesquisa de cada grupo,None,None,None,None,None,None,None,01/04,09/04
15,,None,04- Cronograma de pesquisa e Início de projeto...,None,None,None,None,None,None,None,01/04,31/12
16,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
17,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
18,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
19,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
20,Custo R$ (se houver):,None,Não há,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
21,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
22,(a ser resolvida/mitigada),None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None

Tabela 51

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,302 - cat 3.02 - Desenvolvimento de Projetos d...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None,None,None,None
2,O que será feito:,None,- Pesquisa de Sistemas Multiplataformas para a...,None,None,None,None,None,None,None,None,None
3,,None,Estimular a pesquisa junto ao corpo docente e ...,None,None,None,None,None,None,None,None,None
4,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
5,,None,None,None,None,None,None,None,None,None,None,None
6,Responsável:,<nome> Angelina V. S. Melaré,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
7,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
8,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
9,Período de execução:,None,Data inicial:,None,01/02/2024,None,Data final:,None,None,None,31/12/2024,None
10,,None,01- Comunicação/ Conscientização do corpo disc...,None,None,None,None,None,None,None,01/02,30/03
11,Etapas do processo:,None,None,None,None,None,None,None,None,None,None,None
12,,None,None,None,None,None,None,None,None,None,None,None
13,,None,02- Criação de equipes integradas dos cursos –...,None,None,None,None,None,None,None,01/02,30/03
14,,None,03- Definição de pesquisas de cada grupo‐ com ...,None,None,None,None,None,None,None,01/04,09/04
15,,None,04- Início de projetos de pesquisa,None,None,None,None,None,None,None,01/04,31/12
16,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
17,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
18,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
19,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
20,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
21,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
22,(a ser resolvida/mitigada),None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None

Tabela 52

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,303 - cat. 3.99 - Outra,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Monitoria de Disciplinas e Iniciação Científica,None,None,None,None,None,None,None,None,None
3,,None,Estimular a pesquisa junto ao corpo docente e ...,None,None,None,None,None,None,None,None,None
4,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
5,,None,None,None,None,None,None,None,None,None,None,None
6,,Angelina V. S. Milaré - Dilermando Piva Júnior...,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
7,Responsável:,None,None,None,None,None,None,None,None,None,None,None
8,None,None,None,None,None,,None,None,None,,None,None
9,,None,None,None,None,None,None,None,None,None,None,None
10,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
11,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
12,Período de execução:,None,Data inicial:,None,02/01/2024,None,Data final:,None,None,None,30/12/2024,None
13,Etapas do processo:,None,Comunicação/ Conscientização do corpo discente...,None,None,None,None,None,None,None,02/02,20/12
14,,None,projetos,None,None,None,None,None,None,None,02/02,20/12
15,,None,Criação de equipes integradas dos cursos – doc...,None,None,None,None,None,None,None,02/02,20/12
16,,None,Definição de pesquisas de cada grupo‐ com tema...,None,None,None,None,None,None,None,02/02,20/12
17,,None,Desenvolvimento de projetos de pesquisa,None,None,None,None,None,None,None,02/02,20/12
18,,None,Comunicação/ Conscientização do corpo discente...,None,None,None,None,None,None,None,02/02,20/12
19,,None,projetos,None,None,None,None,None,None,None,02/02,20/12
20,,None,Criação de equipes integradas dos cursos – doc...,None,None,None,None,None,None,None,02/02,20/12
21,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
22,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
23,(a ser resolvida/mitigada),None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None

Tabela 53

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,304 - cat 3.01 - Cursos de Extensão,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Desenvolvimento de Projeto de extensão para a ...,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,Promover cursos para auxiliar que auxiliem o c...,None,None,None,None,None,None,None,None,None
4,,Angelina V. S. Milaré - Dilermando Piva Júnior...,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
5,Responsável:,None,None,None,None,None,None,None,None,None,None,None
6,None,None,None,None,None,,None,None,None,,None,None
7,,None,None,None,None,None,None,None,None,None,None,None
8,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
9,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
10,Período de execução:,None,Data inicial:,None,02/01/2024,None,Data final:,None,None,None,30/12/2024,None
11,,None,Comunicação/ Conscientização do corpo discente...,None,None,None,None,None,None,None,dd/mm,dd/mm
12,Etapas do processo:,None,None,None,None,None,None,None,None,None,None,None
13,,None,None,None,None,None,None,None,None,None,None,None
14,,None,Criação de equipes ‐ discentes,None,None,None,None,None,None,None,dd/mm,dd/mm
15,,None,Definição das aulas,None,None,None,None,None,None,None,dd/mm,dd/mm
16,,None,Início das aulas,None,None,None,None,None,None,None,dd/mm,dd/mm
17,,None,,None,None,None,None,None,None,None,dd/mm,dd/mm
18,,None,,None,None,None,None,None,None,None,dd/mm,dd/mm
19,,None,,None,None,None,None,None,None,None,dd/mm,dd/mm
20,,None,,None,None,None,None,None,None,None,dd/mm,dd/mm
21,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
22,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
23,(a ser resolvida/mitigada),None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None

Tabela 54

                                                   0
0  04 – Atividades Formativas em Projetos (nível ...
1  Projetos institucionais formativos não especif...
2        estudantis (Baja, Aerodesign, entre outros)

Tabela 55

/usr/local/lib/python3.11/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,401 - cat 4.04 - Projetos estudantis diversos,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None,None,None,None
2,O que será feito:,None,"Promover Projetos Internacionais, exames TOIC,...",None,None,None,None,None,None,None,None,None
3,,None,Fomentar o desenvolvimento de fluência em idio...,None,None,None,None,None,None,None,None,None
4,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
5,,None,None,None,None,None,None,None,None,None,None,None
6,Responsável:,<nome> Coordenadores / Direção,None,None,None,Qde CH/sem:,None,None,02,Tipo:,Escolher um item.,None
7,Colaborador(a):,<nome> Élide Garcia Silva Vivan,None,None,None,Qde CH/sem:,None,None,02,Tipo:,Escolher um item.,None
8,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
9,Período de execução:,None,Data inicial:,None,17/02/2025,None,Data final:,None,None,None,19/12/2025,None
10,Etapas do processo:,None,01- Divulgar processos de Intercâmbios Interna...,None,None,None,None,None,None,None,17/02,19/12
11,,None,02- Promover testes de proficiência,None,None,None,None,None,None,None,17/02,19/12
12,,None,03- Propor aulas mais dinâmicas,None,None,None,None,None,None,None,17/02,19/12
13,,None,04- Auxiliar demais docentes nos Projetos Peda...,None,None,None,None,None,None,None,17/02,19/12
14,,None,05- Aquisição de materiais e insumos necessári...,None,None,None,None,None,None,None,17/02,19/12
15,,None,None,None,None,None,None,None,None,None,None,None
16,,None,None,None,None,None,None,None,None,None,None,None
17,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
18,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
19,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
20,Custo R$ (se houver):,None,A ser definido,Fonte(s) dos recursos:,None,None,None,Centro Paula Souza,None,None,None,None
21,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
22,(a ser resolvida/mitigada),None,cat 0.1.99 - Outra,None,None,None,None,None,None,None,None,None

Tabela 56

/usr/local/lib/python3.11/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,402 - cat 4.04 - Projetos estudantis diversos,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Desenvolver um Projeto Colaborativo Internacio...,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,Alunos de Controle de Obras da Fatec em diálog...,None,None,None,None,None,None,None,None,None
4,Responsável:,<nome> Lígia Conceição Pereira Agasi,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
5,,<nome> Fábio Blas Mazuelo,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HAE - Hora Atividade\nEspecífica,None
6,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
7,None,None,None,None,None,,None,None,None,,None,None
8,,None,None,None,None,None,None,None,None,None,None,None
9,,<nome> Élide Garcia Silva Vivan,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HAE - Hora Atividade\nEspecífica,None
10,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
11,None,None,None,None,None,,None,None,None,,None,None
12,,None,None,None,None,None,None,None,None,None,None,None
13,Período de execução:,None,Data inicial:,None,17/02/2025,None,Data final:,None,None,None,19/12/2025,None
14,Etapas do processo:,None,01- Reunião com ARInter e com Coordenação e Pr...,None,None,None,None,None,None,None,17/02,19/12
15,,None,02- Escolha de um tema comum de ambos os paíse...,None,None,None,None,None,None,None,17/02,19/12
16,,None,None,None,None,None,None,None,None,None,None,None
17,,None,None,None,None,None,None,None,None,None,None,None
18,,None,03- Divisão dos alunos em grupos e início de p...,None,None,None,None,None,None,None,17/02,19/12
19,,None,04- Partilhar plano de trabalho conjunto em Pa...,None,None,None,None,None,None,None,17/02,19/12
20,,None,05- Marcar reuniões no Teams entre os Grupos e...,None,None,None,None,None,None,None,17/02,19/12
21,,None,None,None,None,None,None,None,None,None,None,None
22,,None,None,None,None,None,None,None,None,None,None,None
23,,None,06- Aulas em conjunto,None,None,None,None,None,None,None,17/02,19/12
24,,None,07- Replanejamento das atividades,None,None,None,None,None,None,None,17/02,19/12
25,,None,08- Reunião no Teams para apresentação das ati...,None,None,None,None,None,None,None,17/02,19/12
26,Custo R$ (se houver):,None,Não haverá custo,Fonte(s) dos recursos:,None,None,None,Não haverá custo,None,None,None,None
27,Situação problema:,None,"cat 0.1.01 - Metodologia de ensino, desempenho...",None,None,None,None,None,None,None,None,None
28,(a ser resolvida/mitigada),None,cat 0.1.08 - Participação da comunidade e soci...,None,None,None,None,None,None,None,None,None

Tabela 57

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,403 - Escolher um item.,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,Escolher um item.,None,None,None,None,None,None,None,None,None
2,O que será feito:,None,nn,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,nn,None,None,None,None,None,None,None,None,None
4,Responsável:,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
5,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
6,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
7,Período de execução:,None,Data inicial:,None,dd/mm/aaaa,None,Data final:,None,None,None,dd/mm/aaaa,None
8,Etapas do processo:,None,01- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
9,,None,02- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
10,,None,03- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
11,,None,04- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
12,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
13,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
14,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
15,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
16,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
17,Situação problema:,None,Escolher um item.,None,None,None,None,None,None,None,None,None
18,(a ser resolvida/mitigada),None,Escolher um item.,None,None,None,None,None,None,None,None,None

Tabela 58

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,404 - Escolher um item.,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,Escolher um item.,None,None,None,None,None,None,None,None,None
2,O que será feito:,None,nn,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,nn,None,None,None,None,None,None,None,None,None
4,Responsável:,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
5,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
6,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
7,Período de execução:,None,Data inicial:,None,dd/mm/aaaa,None,Data final:,None,None,None,dd/mm/aaaa,None
8,Etapas do processo:,None,01- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
9,,None,02- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
10,,None,03- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
11,,None,04- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
12,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
13,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
14,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
15,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
16,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
17,Situação problema:,None,Escolher um item.,None,None,None,None,None,None,None,None,None
18,(a ser resolvida/mitigada),None,Escolher um item.,None,None,None,None,None,None,None,None,None

Tabela 59

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,401 - cat. 4.99 - Outra,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None,None,None,None
2,,None,Identificação da unidade da Fatec Votorantim e...,None,None,None,None,None,None,None,None,None
3,O que será feito:,None,None,None,None,None,None,None,None,None,None,None
4,,None,None,None,None,None,None,None,None,None,None,None
5,,None,"Para que todos os projetos, cursos e a unidade...",None,None,None,None,None,None,None,None,None
6,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
7,,None,None,None,None,None,None,None,None,None,None,None
8,Responsável:,Todos,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
9,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
10,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
11,Período de execução:,None,Data inicial:,None,02/01/2024,None,Data final:,None,None,None,30/12/2024,None
12,,None,Divulgação da unidade e de seus cursos junto a...,None,None,None,None,None,None,None,02/01,30/12
13,Etapas do processo:,None,None,None,None,None,None,None,None,None,None,None
14,,None,None,None,None,None,None,None,None,None,None,None
15,,None,Participação de eventos locais e regionais do ...,None,None,None,None,None,None,None,02/01,30/12
16,,None,Participação de eventos locais e regionais do ...,None,None,None,None,None,None,None,02/01,30/12
17,,None,None,None,None,None,None,None,None,None,None,None
18,,None,None,None,None,None,None,None,None,None,None,None
19,,None,Participação de eventos locais e regionais do ...,None,None,None,None,None,None,None,02/01,30/12
20,,None,Visitação a escolas/Etecs da região,None,None,None,None,None,None,None,02/01,30/12
21,,None,Parcerias com as empresas,None,None,None,None,None,None,None,02/01,30/12
22,,None,Criação de Núcleo de Comunicação para divulgaç...,None,None,None,None,None,None,None,02/01,30/12
23,,None,None,None,None,None,None,None,None,None,None,None
24,,None,None,None,None,None,None,None,None,None,None,None
25,,None,,None,None,None,None,None,None,None,dd/mm,dd/mm
26,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
27,Situação problema:,None,cat 0.1.99 - Outra,None,None,None,None,None,None,None,None,None
28,(a ser resolvida/mitigada),None,cat 0.1.99 - Outra,None,None,None,None,None,None,None,None,None

Tabela 60

                      0                        1
0   AÇÃO/PROJETO (Tema)  40y - Escolher um item.
1  Origem (prioridade):        Escolher um item.

Tabela 61

                      0                        1
0   AÇÃO/PROJETO (Tema)  40w - Escolher um item.
1  Origem (prioridade):        Escolher um item.

Tabela 62

                      0                        1
0   AÇÃO/PROJETO (Tema)  40z - Escolher um item.
1  Origem (prioridade):        Escolher um item.

Tabela 63

                                                   0
0         05 – Infraestrutura (instalações prediais)
1  Projetos de manutenção e melhoramento predial ...
2  patrimônio: Reparação predial (civil, elétrica...

Tabela 64

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,501 - cat 5.03 - Material Infraestrutura/equip...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None,None,None,None
2,,None,"Adquirir, instalar e configurar os equipamento...",None,None,None,None,None,None,None,None,None
3,O que será feito:,None,None,None,None,None,None,None,None,None,None,None
4,,None,None,None,None,None,None,None,None,None,None,None
5,,None,Visando viabilizar as atividades do setor admi...,None,None,None,None,None,None,None,None,None
6,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
7,,None,None,None,None,None,None,None,None,None,None,None
8,Responsável:,<nome> Coordenadores CDN; CO; DSM,None,None,None,Qde CH/sem:,None,None,05,Tipo:,HA - Hora Atividade,None
9,,<nome> Adriana Cristina de Barros,None,None,None,Qde CH/sem:,None,None,05,Tipo:,H - Hora <não\ntipificada>,None
10,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
11,None,None,None,None,None,,None,None,None,,None,None
12,,None,None,None,None,None,None,None,None,None,None,None
13,,<nome> Laísa Gamito,None,None,None,Qde CH/sem:,None,None,05,Tipo:,H - Hora <não\ntipificada>,None
14,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
15,None,None,None,None,None,,None,None,None,,None,None
16,,None,None,None,None,None,None,None,None,None,None,None
17,Período de execução:,None,Data inicial:,None,02/01/2025,None,Data final:,None,None,None,19/12/2025,None
18,Etapas do processo:,None,01- Especificação dos equipamentos e Mobiliários,None,None,None,None,None,None,None,02/01,19/12
19,,None,02- Solicitação de Compras (inserção no SIAF),None,None,None,None,None,None,None,22/04,19/12
20,,None,03- Adequação do pedido de compras de acordo c...,None,None,None,None,None,None,None,22/04,19/12
21,,None,04- Averiguação do processo de licitação/compra,None,None,None,None,None,None,None,22/04,19/12
22,,None,05- Aguardando entrega de material da CESU,None,None,None,None,None,None,None,22/04,19/12
23,,None,06- Implantação do projeto,None,None,None,None,None,None,None,22/04,19/12
24,,None,07- Testes e verificações,None,None,None,None,None,None,None,22/04,19/12
25,,None,08- Treinamento de Docentes e Auxiliares Docentes,None,None,None,None,None,None,None,22/04,19/12
26,Custo R$ (se houver):,None,A ser definido,Fonte(s) dos recursos:,None,None,None,"DMPP, Centro Paula Souza (Licitação)",None,None,None,None
27,Situação problema:,None,"cat 0.1.03 - Infraestrutura predial (espaços, ...",None,None,None,None,None,None,None,None,None
28,(a ser resolvida/mitigada),None,"cat 0.1.05 - Materiais, equipamentos e mobiliá...",None,None,None,None,None,None,None,None,None

Tabela 65

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,502 - cat 5.03 - Material Infraestrutura/equip...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Laboratórios dos Cursos – instalação e organiz...,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,Para possibilitar aulas práticas definidas no ...,None,None,None,None,None,None,None,None,None
4,Responsável:,<nome> Angelina V. S. Melaré,None,None,None,Qde CH/sem:,None,None,02,Tipo:,Escolher um item.,None
5,Colaborador(a):,<nome> Dilermando Piva Jr,None,None,None,Qde CH/sem:,None,None,02,Tipo:,Escolher um item.,None
6,Colaborador(a):,<nome> Ligia C. P. Agasi,None,None,None,Qde CH/sem:,None,None,02,Tipo:,Escolher um item.,None
7,Período de execução:,None,Data inicial:,None,02/01/2025,None,Data final:,None,None,None,19/12/2025,None
8,Etapas do processo:,None,01- Especificação dos equipamentos e Mobiliários,None,None,None,None,None,None,None,02/01,19/12
9,,None,02- Solicitação de Compras ( inserção no SIAF),None,None,None,None,None,None,None,22/04,19/12
10,,None,03- Adequação do pedido de compras de acordo c...,None,None,None,None,None,None,None,22/04,19/12
11,,None,04- Averiguação do processo de licitação/compra,None,None,None,None,None,None,None,22/04,19/12
12,,None,05- Início da instalação física dos equipamentos,None,None,None,None,None,None,None,22/04,19/12
13,,None,06- Adequação do prédio para as instalações fí...,None,None,None,None,None,None,None,22/04,19/12
14,,None,07- Correções/adequações da solicitação de compra,None,None,None,None,None,None,None,22/04,19/12
15,,None,08- nn,None,None,None,None,None,None,None,22/04,19/12
16,Custo R$ (se houver):,None,A ser definido,Fonte(s) dos recursos:,None,None,None,"DMPP, Centro Paula Souza (Licitação)",None,None,None,None
17,Situação problema:,None,"cat 0.1.03 - Infraestrutura predial (espaços, ...",None,None,None,None,None,None,None,None,None
18,(a ser resolvida/mitigada),None,"cat 0.1.05 - Materiais, equipamentos e mobiliá...",None,None,None,None,None,None,None,None,None

Tabela 66

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,503 - cat 5.04 - Implantação de áreas comuns,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Promover espaços de convívio e de estudo,None,None,None,None,None,None,None,None,None
3,,None,Oferecer espaços adequados para a socialização...,None,None,None,None,None,None,None,None,None
4,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
5,,None,None,None,None,None,None,None,None,None,None,None
6,,<nome> Direção,None,None,None,Qde CH/sem:,None,None,02,Tipo:,H - Hora <não\ntipificada>,None
7,Responsável:,None,None,None,None,None,None,None,None,None,None,None
8,None,None,None,None,None,,None,None,None,,None,None
9,,None,None,None,None,None,None,None,None,None,None,None
10,,<nome> Eliana Teodoro dos Santos,None,None,None,Qde CH/sem:,None,None,02,Tipo:,H - Hora <não\ntipificada>,None
11,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
12,None,None,None,None,None,,None,None,None,,None,None
13,,None,None,None,None,None,None,None,None,None,None,None
14,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
15,Período de execução:,None,Data inicial:,None,02/01/2025,None,Data final:,None,None,None,19/12/2025,None
16,Etapas do processo:,None,01- Definição do layout do espaço de convívio ...,None,None,None,None,None,None,None,02/01,19/12
17,,None,02- Definição do layout do espaço de convívio ...,None,None,None,None,None,None,None,02/01,19/12
18,,None,03- Definição do layout do espaço de convívio ...,None,None,None,None,None,None,None,02/01,19/12
19,,None,04- Definição de novas compras de mobiliários ...,None,None,None,None,None,None,None,02/01,19/12
20,,None,05- Averiguação do processo de licitação/compra,None,None,None,None,None,None,None,02/01,19/12
21,,None,06- Instalação dos mobiliários já adquiridos,None,None,None,None,None,None,None,02/01,19/12
22,,None,07- Instalação de novos mobiliários comprados,None,None,None,None,None,None,None,02/01,19/12
23,,None,08- Instalação do Wi‐Fi e acesso à Internet no...,None,None,None,None,None,None,None,02/01,19/12
24,Custo R$ (se houver):,None,A ser definido,Fonte(s) dos recursos:,None,None,None,"DMPP, Centro Paula Souza (Licitação)",None,None,None,None
25,Situação problema:,None,"cat 0.1.03 - Infraestrutura predial (espaços, ...",None,None,None,None,None,None,None,None,None
26,(a ser resolvida/mitigada),None,"cat 0.1.05 - Materiais, equipamentos e mobiliá...",None,None,None,None,None,None,None,None,None

Tabela 67

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,504 - Escolher um item.,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,Escolher um item.,None,None,None,None,None,None,None,None,None
2,O que será feito:,None,nn,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,nn,None,None,None,None,None,None,None,None,None
4,Responsável:,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
5,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
6,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
7,Período de execução:,None,Data inicial:,None,dd/mm/aaaa,None,Data final:,None,None,None,dd/mm/aaaa,None
8,Etapas do processo:,None,01- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
9,,None,02- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
10,,None,03- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
11,,None,04- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
12,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
13,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
14,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
15,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
16,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
17,Situação problema:,None,Escolher um item.,None,None,None,None,None,None,None,None,None
18,(a ser resolvida/mitigada),None,Escolher um item.,None,None,None,None,None,None,None,None,None

Tabela 68

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,501 - cat. 5.99 - Outra,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
2,,None,Compra/ instalação/ configuração/ de equipamen...,None,None,None,None,None,None,None,None,None
3,O que será feito:,None,None,None,None,None,None,None,None,None,None,None
4,,None,None,None,None,None,None,None,None,None,None,None
5,,None,Para permitir o trabalho do setor administrati...,None,None,None,None,None,None,None,None,None
6,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
7,,None,None,None,None,None,None,None,None,None,None,None
8,Responsável:,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
9,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
10,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
11,Período de execução:,None,Data inicial:,None,02/01/2024,None,Data final:,None,None,None,30/12/2024,None
12,Etapas do processo:,None,01-Aguardando entrega de material da CESU,None,None,None,None,None,None,None,01/01,31/12
13,,None,02-Implantação do projeto,None,None,None,None,None,None,None,01/01,31/12
14,,None,03-Testes e verificações,None,None,None,None,None,None,None,01/01,31/12
15,,None,04- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
16,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
17,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
18,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
19,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
20,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
21,Situação problema:,None,"cat 0.1.03 - Infraestrutura predial (espaços, ...",None,None,None,None,None,None,None,None,None
22,(a ser resolvida/mitigada),None,"cat 0.1.03 - Infraestrutura predial (espaços, ...",None,None,None,None,None,None,None,None,None

Tabela 69

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,502 - cat 5.02 - Melhoria de Laboratório,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Laboratórios dos Cursos - organização,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,Para possibilitar aulas práticas definidas no ...,None,None,None,None,None,None,None,None,None
4,,"<nome> Angelina V. S. Melar, Dilermando Piva J...",None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
5,Responsável:,None,None,None,None,None,None,None,None,None,None,None
6,None,None,None,None,None,,None,None,None,,None,None
7,,None,None,None,None,None,None,None,None,None,None,None
8,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
9,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
10,Período de execução:,None,Data inicial:,None,02/01/2024,None,Data final:,None,None,None,30/12/2024,None
11,Etapas do processo:,None,Correções/adequações da solicitação de compra,None,None,None,None,None,None,None,01/01,31/12
12,,None,Averiguação do processo de licitação/compra,None,None,None,None,None,None,None,01/01,31/12
13,,None,Início da instalação física dos equipamentos,None,None,None,None,None,None,None,01/01,31/12
14,,None,Adequação do prédio para as instalações física...,None,None,None,None,None,None,None,01/01,31/12
15,,None,Correções/adequações da solicitação de compra,None,None,None,None,None,None,None,01/01,31/12
16,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
17,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
18,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
19,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
20,Situação problema:,None,"cat 0.1.03 - Infraestrutura predial (espaços, ...",None,None,None,None,None,None,None,None,None
21,(a ser resolvida/mitigada),None,"cat 0.1.03 - Infraestrutura predial (espaços, ...",None,None,None,None,None,None,None,None,None

Tabela 70

,0,1,2,3,4,5,6
0,AÇÃO/PROJETO (Tema),None,503 - cat 5.04 - Implantação de áreas comuns,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None
2,O que será feito:,None,Promover espaços de convívio e de estudo,None,None,None,None
3,,None,Oferecer espaços adequados para a socialização...,None,None,None,None
4,Por que será feito:,None,None,None,None,None,None
5,,None,None,None,None,None,None
6,Responsável:,<nome> Diretor Mauro Tomazela,None,Qde CH/sem:,nn,Tipo:,Escolher um item.

Tabela 71

,0,1,2,3,4,5,6,7,8,9,10,11
0,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
1,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
2,Período de execução:,None,Data inicial:,None,02/01/2024,None,Data final:,None,None,None,30/12/2024,None
3,Etapas do processo:,None,Definição do layout do espaço de convívio dos ...,None,None,None,None,None,None,None,01/01,31/12
4,,None,Definição do layout do espaço de convívio dos ...,None,None,None,None,None,None,None,01/01,31/12
5,,None,Definição do layout do espaço de convívio do a...,None,None,None,None,None,None,None,01/01,31/12
6,,None,Definição de novas compras de mobiliários para...,None,None,None,None,None,None,None,01/01,31/12
7,,None,Averiguação do processo de licitação/compra,None,None,None,None,None,None,None,01/01,31/12
8,,None,Instalação dos mobiliários já adquiridos,None,None,None,None,None,None,None,01/01,31/12
9,,None,Instalação de novos mobiliários comprados,None,None,None,None,None,None,None,01/01,31/12
10,,None,Instalação do Wi‐Fi e acesso à Internet nos lo...,None,None,None,None,None,None,None,01/01,31/12
11,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
12,Situação problema:,None,"cat 0.1.03 - Infraestrutura predial (espaços, ...",None,None,None,None,None,None,None,None,None
13,(a ser resolvida/mitigada),None,"cat 0.1.03 - Infraestrutura predial (espaços, ...",None,None,None,None,None,None,None,None,None

Tabela 72

                      0                        1
0   AÇÃO/PROJETO (Tema)  50z - Escolher um item.
1  Origem (prioridade):        Escolher um item.

Tabela 73

                                                   0
0  06 - Desenvolvimento de pessoas (docentes e se...
1  Formação continuada de docentes e servidores, ...
2  atividades: Metodologias de ensino, Tecnologia...
3          computacionais) acadêmicos e pedagógicos.

Tabela 74

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,601 - cat 6.01 - Curso/Oficina/Capacitação/ Tr...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
2,,None,"Treinamento dos coordenadores, profissionais a...",None,None,None,None,None,None,None,None,None
3,O que será feito:,None,None,None,None,None,None,None,None,None,None,None
4,,None,None,None,None,None,None,None,None,None,None,None
5,Por que será feito:,None,Para que os funcionários consigam exercer suas...,None,None,None,None,None,None,None,None,None
6,Responsável:,<nome> Direção / Coordenação,None,None,None,Qde CH/sem:,None,None,05,Tipo:,HA - Hora Atividade,None
7,Colaborador(a):,<nome> Juliana Tonon Oliveira,None,None,None,Qde CH/sem:,None,None,05,Tipo:,HA - Hora Atividade,None
8,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
9,Período de execução:,None,Data inicial:,None,02/01/2025,None,Data final:,None,None,None,20/12/2025,None
10,Etapas do processo:,None,01- Capacitação dos sistemas acadêmica e admin...,None,None,None,None,None,None,None,02/01,20/12
11,,None,02- Capacitação pedagógica dos professores no ...,None,None,None,None,None,None,None,02/01,20/12
12,,None,03- Capacitação dos funcionários e docentes so...,None,None,None,None,None,None,None,02/01,20/12
13,,None,None,None,None,None,None,None,None,None,None,None
14,,None,None,None,None,None,None,None,None,None,None,None
15,,None,04- Dialogo e debates com os funcionários e do...,None,None,None,None,None,None,None,02/01,20/12
16,,None,None,None,None,None,None,None,None,None,None,None
17,,None,None,None,None,None,None,None,None,None,None,None
18,,None,05- Apresentação dos resultados da CPA 2023 ao...,None,None,None,None,None,None,None,02/01,20/12
19,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
20,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
21,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
22,Custo R$ (se houver):,None,Não haverá custos,Fonte(s) dos recursos:,None,None,None,Não haverá custos,None,None,None,None
23,Situação problema:,None,cat 0.1.10 - Gestão da unidade de ensino e dos...,None,None,None,None,None,None,None,None,None
24,(a ser resolvida/mitigada),None,cat 0.1.06 - Quantidade de professores/funcion...,None,None,None,None,None,None,None,None,None

Tabela 75

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,602 - cat. 6.99 - Outra,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Ações propostas pela CPA,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,Recomendações importantes solicitadas pela Com...,None,None,None,None,None,None,None,None,None
4,,<nome> Diego Aparecido carvalho Albuquerque,None,None,None,Qde CH/sem:,None,None,11,Tipo:,HAE - Hora Atividade\nEspecífica,None
5,Responsável:,None,None,None,None,None,None,None,None,None,None,None
6,None,None,None,None,None,,None,None,None,,None,None
7,,None,None,None,None,None,None,None,None,None,None,None
8,,<nome> Membros da CPA,None,None,None,Qde CH/sem:,None,None,05,Tipo:,H - Hora <não\ntipificada>,None
9,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
10,None,None,None,None,None,,None,None,None,,None,None
11,,None,None,None,None,None,None,None,None,None,None,None
12,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
13,Período de execução:,None,Data inicial:,None,02/01/2025,None,Data final:,None,None,None,20/12/2025,None
14,,None,01- Manter as estratégias institucionais da un...,None,None,None,None,None,None,None,02/01,20/12
15,Etapas do processo:,None,None,None,None,None,None,None,None,None,None,None
16,,None,None,None,None,None,None,None,None,None,None,None
17,,None,02- Rever a forma e frequência de divulgação d...,None,None,None,None,None,None,None,02/01,20/12
18,,None,None,None,None,None,None,None,None,None,None,None
19,,None,None,None,None,None,None,None,None,None,None,None
20,,None,03- Capacitação dos funcionários e docentes so...,None,None,None,None,None,None,None,02/01,20/12
21,,None,None,None,None,None,None,None,None,None,None,None
22,,None,None,None,None,None,None,None,None,None,None,None
23,,None,04- Rever a forma e frequência de divulgação d...,None,None,None,None,None,None,None,02/01,20/12
24,,None,None,None,None,None,None,None,None,None,None,None
25,,None,None,None,None,None,None,None,None,None,None,None
26,,None,05- Consolidar um programa de sensibilização e...,None,None,None,None,None,None,None,02/01,20/12
27,,None,None,None,None,None,None,None,None,None,None,None
28,,None,None,None,None,None,None,None,None,None,None,None
29,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
30,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
31,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
32,Custo R$ (se houver):,None,Não haverá custos,Fonte(s) dos recursos:,None,None,None,Não haverá custos,None,None,None,None
33,Situação problema:,None,cat 0.1.10 - Gestão da unidade de ensino e dos...,None,None,None,None,None,None,None,None,None
34,(a ser resolvida/mitigada),None,cat 0.1.99 - Outra,None,None,None,None,None,None,None,None,None

Tabela 76

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,603 - Escolher um item.,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,Escolher um item.,None,None,None,None,None,None,None,None,None
2,O que será feito:,None,nn,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,nn,None,None,None,None,None,None,None,None,None
4,Responsável:,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
5,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
6,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
7,Período de execução:,None,Data inicial:,None,dd/mm/aaaa,None,Data final:,None,None,None,dd/mm/aaaa,None
8,Etapas do processo:,None,01- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
9,,None,02- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
10,,None,03- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
11,,None,04- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
12,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
13,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
14,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
15,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
16,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
17,Situação problema:,None,Escolher um item.,None,None,None,None,None,None,None,None,None
18,(a ser resolvida/mitigada),None,Escolher um item.,None,None,None,None,None,None,None,None,None

Tabela 77

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,604 - Escolher um item.,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,Escolher um item.,None,None,None,None,None,None,None,None,None
2,O que será feito:,None,nn,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,nn,None,None,None,None,None,None,None,None,None
4,Responsável:,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
5,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
6,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
7,Período de execução:,None,Data inicial:,None,dd/mm/aaaa,None,Data final:,None,None,None,dd/mm/aaaa,None
8,Etapas do processo:,None,01- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
9,,None,02- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
10,,None,03- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
11,,None,04- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
12,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
13,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
14,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
15,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
16,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
17,Situação problema:,None,Escolher um item.,None,None,None,None,None,None,None,None,None
18,(a ser resolvida/mitigada),None,Escolher um item.,None,None,None,None,None,None,None,None,None

Tabela 78

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,601 - cat 6.01 - Curso/Oficina/Capacitação/ Tr...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
2,,None,"Capacitação dos coordenadores, administrativo ...",None,None,None,None,None,None,None,None,None
3,O que será feito:,None,None,None,None,None,None,None,None,None,None,None
4,,None,None,None,None,None,None,None,None,None,None,None
5,Por que será feito:,None,Para que o funcionário consiga exercer suas fu...,None,None,None,None,None,None,None,None,None
6,,"Direção: Mauro Tomazela, coordenação pedagógic...",None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
7,Responsável:,None,None,None,None,None,None,None,None,None,None,None
8,None,None,None,None,None,,None,None,None,,None,None
9,,None,None,None,None,None,None,None,None,None,None,None
10,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
11,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
12,Período de execução:,None,Data inicial:,None,02/01/2024,None,Data final:,None,None,None,30/12/2024,None
13,Etapas do processo:,None,01- Capacitação dos sistemas acadêmica e admin...,None,None,None,None,None,None,None,01/01,30/12
14,,None,02- Capacitação pedagógica dos professores no ...,None,None,None,None,None,None,None,01/01,30/12
15,,None,03- Capacitação dos funcionários e docentes so...,None,None,None,None,None,None,None,01/01,30/12
16,,None,None,None,None,None,None,None,None,None,None,None
17,,None,None,None,None,None,None,None,None,None,None,None
18,,None,04- Dialogo e debates com os funcionários e do...,None,None,None,None,None,None,None,01/01,30/12
19,,None,None,None,None,None,None,None,None,None,None,None
20,,None,None,None,None,None,None,None,None,None,None,None
21,,None,05- Apresentação dos resultados da CPA 2023 ao...,None,None,None,None,None,None,None,01/01,30/12
22,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
23,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
24,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
25,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
26,Situação problema:,None,cat 0.1.10 - Gestão da unidade de ensino e dos...,None,None,None,None,None,None,None,None,None
27,(a ser resolvida/mitigada),None,cat 0.1.10 - Gestão da unidade de ensino e dos...,None,None,None,None,None,None,None,None,None

Tabela 79

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,602 - cat. 6.99 - Outra,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,"3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...",None,None,None,None,None,None,None,None,None
2,O que será feito:,None,Ações proposta pela C.P. A,None,None,None,None,None,None,None,None,None
3,Por que será feito:,None,Recomendações importantes solicitadas pela Com...,None,None,None,None,None,None,None,None,None
4,,<nome> C.P. A,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora\nAtividade,None
5,Responsável:,None,None,None,None,None,None,None,None,None,None,None
6,None,None,None,None,None,,None,None,None,,None,None
7,,None,None,None,None,None,None,None,None,None,None,None
8,,<nome> Mariana e Laisa,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora\nAtividade,None
9,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
10,None,None,None,None,None,,None,None,None,,None,None
11,,None,None,None,None,None,None,None,None,None,None,None
12,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
13,Período de execução:,None,Data inicial:,None,02/02/2024,None,Data final:,None,None,None,31/12/2024,None
14,,None,01- Manter as estratégias institucionais da un...,None,None,None,None,None,None,None,02/02,31/12
15,Etapas do processo:,None,None,None,None,None,None,None,None,None,None,None
16,,None,None,None,None,None,None,None,None,None,None,None
17,,None,02- Disponibilizar o Regimento das Fatec na in...,None,None,None,None,None,None,None,02/02,31/12
18,,None,None,None,None,None,None,None,None,None,None,None
19,,None,None,None,None,None,None,None,None,None,None,None
20,,None,03- Rever a forma e frequência de divulgação d...,None,None,None,None,None,None,None,02/02,31/12
21,,None,None,None,None,None,None,None,None,None,None,None
22,,None,None,None,None,None,None,None,None,None,None,None
23,,None,04- Consolidar um programa de sensibilização e...,None,None,None,None,None,None,None,02/02,31/12
24,,None,None,None,None,None,None,None,None,None,None,None
25,,None,None,None,None,None,None,None,None,None,None,None
26,,None,05- nn,None,None,None,None,None,None,None,02/02,31/12
27,,None,06- nn,None,None,None,None,None,None,None,02/02,31/12
28,,None,07- nn,None,None,None,None,None,None,None,02/02,31/12
29,,None,08- nn,None,None,None,None,None,None,None,02/02,31/12
30,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
31,Situação problema:,None,Escolher um item.,None,None,None,None,None,None,None,None,None
32,(a ser resolvida/mitigada),None,Escolher um item.,None,None,None,None,None,None,None,None,None

Tabela 80

                      0                        1
0   AÇÃO/PROJETO (Tema)  60w - Escolher um item.
1  Origem (prioridade):        Escolher um item.

Tabela 81

                      0                        1
0   AÇÃO/PROJETO (Tema)  60z - Escolher um item.
1  Origem (prioridade):        Escolher um item.

Tabela 82

                                                   0
0          07 – Convênios e Parcerias Institucionais
1  Formalização do relacionamento da Unidade com ...
2  estágios, projetos com empresas. Aqui cabe ape...
3  relacionada a uma Ação/Projeto de melhoria em ...

Tabela 83

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,701 - cat 7.03 - Projetos com empresas e/ou de...,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None,None,None,None
2,Referente ao(s) projeto(s):,None,nn,None,None,None,None,None,None,None,None,None
3,,None,Contato com pelo menos duas organizações para ...,None,None,None,None,None,None,None,None,None
4,O que será feito:,None,None,None,None,None,None,None,None,None,None,None
5,,None,None,None,None,None,None,None,None,None,None,None
6,,None,Para inserir os alunos do curso no mercado de ...,None,None,None,None,None,None,None,None,None
7,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
8,,None,None,None,None,None,None,None,None,None,None,None
9,Responsável:,<nome> Angelina V. S. Melaré,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
10,Colaborador(a):,<nome> Dilermando Piva Jr / Ligia C. P. Agasi,None,None,None,Qde CH/sem:,None,None,02,Tipo:,HA - Hora Atividade,None
11,,<nome> Laísa Gamito,None,None,None,Qde CH/sem:,None,None,02,Tipo:,H - Hora <não\ntipificada>,None
12,Colaborador(a):,None,None,None,None,None,None,None,None,None,None,None
13,None,None,None,None,None,,None,None,None,,None,None
14,,None,None,None,None,None,None,None,None,None,None,None
15,Período de execução:,None,Data inicial:,None,02/01/2025,None,Data final:,None,None,None,20/12/2025,None
16,Etapas do processo:,None,01- Verificar professor responsável para contatos,None,None,None,None,None,None,None,02/01,20/12
17,,None,02- Entrar em contato para descobrir responsáv...,None,None,None,None,None,None,None,02/01,20/12
18,,None,None,None,None,None,None,None,None,None,None,None
19,,None,None,None,None,None,None,None,None,None,None,None
20,,None,03- Marcar visita / reuniões remotas com as em...,None,None,None,None,None,None,None,02/01,20/12
21,,None,04- Firmar parcerias,None,None,None,None,None,None,None,02/01,20/12
22,,None,05- Verificar professor responsável para contatos,None,None,None,None,None,None,None,02/01,20/12
23,,None,06- Entrar em contato para descobrir responsáv...,None,None,None,None,None,None,None,02/01,20/12
24,,None,None,None,None,None,None,None,None,None,None,None
25,,None,None,None,None,None,None,None,None,None,None,None
26,,None,07- Marcar visita / reuniões remotas com as em...,None,None,None,None,None,None,None,02/01,20/12
27,,None,08- Fortalecimento da parceria com a Prefeitur...,None,None,None,None,None,None,None,02/01,20/12
28,Custo R$ (se houver):,None,Não haverá custos,Fonte(s) dos recursos:,None,None,None,Não haverá custos,None,None,None,None
29,Situação problema:,None,cat 0.1.08 - Participação da comunidade e soci...,None,None,None,None,None,None,None,None,None
30,(a ser resolvida/mitigada),None,cat 0.1.99 - Outra,None,None,None,None,None,None,None,None,None

Tabela 84

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,702 - Escolher um item.,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,Escolher um item.,None,None,None,None,None,None,None,None,None
2,Referente ao(s) projeto(s):,None,nn,None,None,None,None,None,None,None,None,None
3,O que será feito:,None,nn,None,None,None,None,None,None,None,None,None
4,Por que será feito:,None,nn,None,None,None,None,None,None,None,None,None
5,Responsável:,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
6,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
7,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
8,Período de execução:,None,Data inicial:,None,dd/mm/aaaa,None,Data final:,None,None,None,dd/mm/aaaa,None
9,Etapas do processo:,None,01- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
10,,None,02- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
11,,None,03- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
12,,None,04- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
13,,None,05- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
14,,None,06- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
15,,None,07- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
16,,None,08- nn,None,None,None,None,None,None,None,dd/mm,dd/mm
17,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
18,Situação problema:,None,Escolher um item.,None,None,None,None,None,None,None,None,None
19,(a ser resolvida/mitigada),None,Escolher um item.,None,None,None,None,None,None,None,None,None

Tabela 85

,0,1,2,3,4,5,6,7,8,9,10,11
0,AÇÃO/PROJETO (Tema),None,701 - cat. 7.99 - Outra,None,None,None,None,None,None,None,None,None
1,Origem (prioridade):,None,6-Outra,None,None,None,None,None,None,None,None,None
2,Referente ao(s) projeto(s):,None,nn,None,None,None,None,None,None,None,None,None
3,,None,Contato com pelo menos duas organizações para ...,None,None,None,None,None,None,None,None,None
4,O que será feito:,None,None,None,None,None,None,None,None,None,None,None
5,,None,None,None,None,None,None,None,None,None,None,None
6,,None,Para inserir os alunos do curso no mercado de\...,None,None,None,None,None,None,None,None,None
7,Por que será feito:,None,None,None,None,None,None,None,None,None,None,None
8,,None,None,None,None,None,None,None,None,None,None,None
9,,"Angelina V. S. Melar, Dilermando Piva Jr. e Li...",None,None,None,Qde CH/sem:,None,None,04,Tipo:,HA - Hora\nAtividade,None
10,Responsável:,None,None,None,None,None,None,None,None,None,None,None
11,None,None,None,None,None,,None,None,None,,None,None
12,,None,None,None,None,None,None,None,None,None,None,None
13,,<nome> Maria José Cardozo,None,None,None,Qde CH/sem:,None,None,04,Tipo:,HAE - Hora\nAtividade\nEspecífica,None
14,Colaborador(a):,None,None,None,None,,None,None,None,,None,None
15,,None,None,None,None,None,None,None,None,None,None,None
16,Colaborador(a):,<nome> nn,None,None,None,Qde CH/sem:,None,None,nn,Tipo:,Escolher um item.,None
17,Período de execução:,None,Data inicial:,None,02/01/2024,None,Data final:,None,None,None,30/12/2024,None
18,Etapas do processo:,None,Verificar professor responsável para contatos,None,None,None,None,None,None,None,02/01,31/12
19,,None,Entrar em contato para descobrir responsáveis ...,None,None,None,None,None,None,None,02/01,31/12
20,,None,None,None,None,None,None,None,None,None,None,None
21,,None,None,None,None,None,None,None,None,None,None,None
22,,None,Marcar visita / reuniões remotas com as empresas,None,None,None,None,None,None,None,02/01,31/12
23,,None,Firmar parcerias,None,None,None,None,None,None,None,02/01,31/12
24,,None,Verificar professor responsável para contatos,None,None,None,None,None,None,None,02/01,31/12
25,,None,Entrar em contato para descobrir responsáveis ...,None,None,None,None,None,None,None,02/01,31/12
26,,None,None,None,None,None,None,None,None,None,None,None
27,,None,None,None,None,None,None,None,None,None,None,None
28,,None,Marcar visita / reuniões remotas com as empresas,None,None,None,None,None,None,None,02/01,31/12
29,,None,Fortalecimento da parceria com a Prefeitura Mu...,None,None,None,None,None,None,None,02/01,31/12
30,Custo R$ (se houver):,None,nn,Fonte(s) dos recursos:,None,None,None,nn,None,None,None,None
31,Situação problema:,None,cat 0.1.08 - Participação da comunidade e soci...,None,None,None,None,None,None,None,None,None
32,(a ser resolvida/mitigada),None,cat 0.1.08 - Participação da comunidade e soci...,None,None,None,None,None,None,None,None,None

Tabela 86

                             0                        1
0          AÇÃO/PROJETO (Tema)  70y - Escolher um item.
1         Origem (prioridade):        Escolher um item.
2  Referente ao(s) projeto(s):                       nn

Tabela 87

                                                   0
0  Anexo 1 – Lista de aquisições necessárias aos ...
1             (equipamentos, softwares, mobiliários)

Tabela 88

,0,1,2,3,4,5,6
0,Item,Projeto\n(XYY),Denominação ou especificação do equipamento,Quant.,,Preço total,
1,None,None,None,None,None,estimado,None
2,None,None,None,None,None,(R$),None
3,01,202- 501-\n502,Acess Point - Interface de Rede (1) RJ-45 Giga...,8,"R$ 13.016,96",None,None
4,02,202- 501-\n502,"Projetor Multimídia Portátil, 8.000 Lumens, LE...",9,"R$ 24.741,00",None,None
5,03,202- 501-\n502,"Televisão a cores, FULL HD 4K; conversor: digi...",8,"R$ 28.792,00",None,None
6,04,202- 501-\n502,"Tela de projeção 2,00x2,00 - retrátil",9,"R$ 8.691,39",None,None
7,05,202- 501-\n502,"Caixa de som amplificada, Bivolt, 250W RMS, En...",5,"R$ 1.675,00",None,None
8,06,202- 501-\n502,Notebook Plus Educacional,288,"R$\n1.486.386,00",None,None
9,07,202- 501-\n502,Notebook Educacional para processamento de Int...,72,"R$ 371.592,00",None,None

Tabela 89

         0
0  Projeto
1    (XYY)

Tabela 90

  0 1                                                  2 3 4
0      frequência mínima de 3200 MHz. Conector: O pad...

Tabela 91

,0,1,2,3,4
0,,,AC (Dual Band). INTERFACE BLUETOOTH: Deverá po...,,
1,08,202- 501-\n502,"Extensão elétrica 20 metros 10a cabo Pp2x1,0 r...",16,"R$ 1.583,84"
2,09,202- 501-\n502,"Filtro de linha 10 tomadas 1,2 metros 10a",16,"R$ 1.183,84"
3,10,202- 501-\n502,Carrinho estante para armazenamento e carregam...,8,"R$ 48.000,00"
4,11,202- 501-\n502,"Mesa para computador sem teclado retrátil, med...",280,"R$ 294.560,00"
5,12,202- 501-\n502,Cadeira para laboratório de informática,280,"R$ 256.200,00"
6,13,202- 501-\n502,"Quadro não magnético branco, 4,00x1,20",8,"R$ 11.384,00"
7,14,202- 501-\n502,"Quadro de aviso, madeira, revestido em fórmica...",8,"R$ 1.592,00"
8,15,202- 501-\n502,Armário de aço c/ 02 portas de abrir,8,"R$ 20.500,00"
9,16,202- 501-\n502,Conjunto de mesa e cadeira para professor,8,"R$ 7.560,00"
10,17,202- 501-\n502,"Cabo Y, 1 HDMI macho, 2 HDMI fêmea",8,"R$ 190,00"
11,18,202- 501-\n502,Mini rack de parede,8,"R$ 3.248,96"
12,19,202- 501-\n502,Conjunto didático; para uso em laboratório de ...,36,"R$ 10.796,40"

Tabela 92

,0,1,2,3,4
0,,,"podem ser usadas como pwm), portas analógicas:...",,
1,20,202- 501-\n502,Placa microprocessada; modulo esp32 wifi e blu...,36,"R$ 5.036,40"
2,21,202- 501-\n502,Componentes para circuito integrado; módulo bl...,36,"R$ 1.616,40"
3,22,202- 501-\n502,"Componentes para circuito integrado, sensor um...",36,"R$ 536,40"
4,23,202- 501-\n502,Sensor de luminosidade tsl2561; sensor eletrôn...,36,"R$ 608,40"
5,24,202- 501-\n502,Sensor eletrônico de temperatura sensor eletrô...,36,"R$ 716,40"
6,25,202- 501-\n502,Componentes para circuito integrado; sensor de...,36,"R$ 464,40"
7,26,202- 501-\n502,"Medidor de umidade do solo, módulo sensor dete...",36,"R$ 392,40"
8,27,202- 501-\n502,"Sensor eletrônico de chuva; lm393 (módulo); 3,...",36,"R$ 356,40"
9,28,202- 501-\n502,"Display, Lcd, 20 Caracteres, 2 Linhas Item BEC.",36,"R$ 4.062,96"
10,29,202- 501-\n502,Componentes para circuito integrado; módulo ad...,36,"R$ 356,40"
11,30,202- 501-\n502,Relê; tipo eletromecânico; modulo relê sla-05v...,36,"R$ 1.184,40"
12,31,202- 501-\n502,Teclado matricial de membrana com 16 teclas e ...,36,"R$ 383,40"
13,32,202- 501-\n502,Kit leitor rfid + tags (chaveiro e cartão) com...,36,"R$ 680,40"
14,33,202- 501-\n502,"Kit robótica, sensor de gás kit robótica; sens...",36,"R$ 1.328,40"
15,34,202- 501-\n502,Componentes para circuito integrado; micro ser...,36,"R$ 1.256,40"

Tabela 93

,0,1,2,3,4
0,,,"1,8kg/cm (4.8v); velocidade: 0,1 S/60graus; al...",,
1,35,202- 501-\n502,Componentes para circuito integrado; motor de ...,36,"R$ 716,40"
2,36,202- 501-\n502,"Componentes para circuito integrado, motor dc-...",36,"R$ 176,40"
3,37,202- 501-\n502,kit placa microprocessada raspberry pi 4 model...,21,"R$ 11.739,00"
4,38,202- 501-\n502,"placa microprocessada módulo câmera raspberry,...",21,"R$ 1.047,90"
5,39,202- 501-\n502,"flat cable gpio para raspberry pi3, pi3b, pi4,...",21,"R$ 1.049,79"
6,40,202- 501-\n502,Fonte de alimentação digital 15v 2a bivolt\nEs...,21,"R$ 10.196,00"
7,41,202- 501-\n502,"Placa de Ensaio Protoboard, Base Metal, Tablet...",21,"R$ 1.309,56"
8,42,202- 501-\n502,Dispositivo de Armazenamento; Cartao de Memori...,21,"R$ 2.974,02"
9,43,202- 501-\n502,"Combo Teclado e Mouse Com Fio 1,30 m Item BEC\...",21,"R$ 2.015,79"
10,44,202- 501-\n502,Estação de solda Estação de Solda Digital 110v...,2,"R$ 6.668,66"
11,45,202- 501-\n502,Ferro de solda soldador; cabo em termoplástico...,2,"R$ 65,98"

Tabela 94

,0,1,2,3,4
0,46,202- 501-\n502,"Alicate de corte pequeno- Alicate P/uso Geral,...",2,"R$ 33,98"
1,47,202- 501-\n502,Alicate de bico pequeno\nAlicate Bico Fino. Ti...,2,"R$ 38,64"
2,48,202- 501-\n502,"Kit de Ferramentas Manuais, Alicate, Aco Vanad...",1,"R$ 111,55"
3,49,202- 501-\n502,"Kit de Ferramentas Manuais, Chave de Fenda e P...",1,"R$ 63,82"
4,50,202- 501-\n502,Kit de Ferramentas para Informatica Item BEC\n...,2,"R$ 291,80"
5,51,202- 501-\n502,Alicate crimpador; confeccionado em aço oxidad...,2,"R$ 279,80"
6,52,202- 501-\n502,Testador de cabo de rede. Testador de Cabo de ...,2,"R$ 86,84"
7,53,202- 501-\n502,Multímetro; caixa em plástico resistente (abs)...,3,"R$ 1.010,70"

Tabela 95

,0,1,2,3,4
0,54,202- 501-\n502,"Multimetro Digital, de Bancada, 750vac, Alimen...",3,"R$ 2.318,97"
1,55,202- 501-\n502,"Dispositivo de Armazenamento; Pen Drive, Usb 2...",10,"R$ 198,90"
2,56,202- 501-\n502,Pendrive Usb 3.0 64gb Item BEC Item com Negoci...,10,"R$ 289,00"
3,57,202- 501-\n502,"Disco Rigido; Padrao Usb 3.0, Externo; de 02 T...",5,"R$ 2.385,00"
4,58,202- 501-\n502,"Impressora Laser; Monocromatica Duplex, Proces...",2,"R$ 3.010,30"
5,59,202- 501-\n502,Mesa para impressora,2,"R$ 1.090,00"
6,60,202- 501-\n502,Microfone; Tipo Microfone de Mao Com Fio; Padr...,2,"R$ 698,00"
7,61,202- 501-\n502,"Fone C/microfone, Headset Monoauricular, Encai...",40,"R$ 2.799,60"
8,62,202- 501-\n502,Servidor: Um processador de alto desempenho co...,1,"R$ 17.800,00"

Tabela 96

,0,1,2,3,4
0,,,menos 10000 MB/s) para processamento de dados ...,,
1,63,202- 501-\n502,"Agitador de Peneiras, Eletromecanico de Bancad...",6,"R$ 53.865,00"
2,64,202- 501-\n502,Balanca Eletronica Digital de Piso P/ Ate 200k...,2,"R$ 4.957,80"
3,65,202- 501-\n502,Balanca Eletronica Digital P/ 30 Kg e Divisao ...,2,"R$ 1.964,00"
4,66,202- 501-\n502,Balanca Precisao Eletronica Digital para Ate 1...,4,"R$ 2.978,62"
5,67,202- 501-\n502,Equipamentos para Fins Didaticos; Medidor de U...,4,"R$ 21.248,11"
6,68,202- 501-\n502,"Densimetro para Massa Especifica Com Escala 0,...",4,"R$ 140,40"
7,69,202- 501-\n502,Estufa 180 l Ate 200 Graus Celsius 220v 1900wE...,4,"R$ 21.677,04"

Tabela 97

,0,1,2,3,4
0,,,Graus Acima Da Ambiente Ate 200 Graus Celsius;...,,
1,70,202- 501-\n502,"Paquimetro, Em Aco Inoxidavel, Universal, Anal...",6,"R$ 4.212,36"
2,71,202- 501-\n502,"Termometro Digital, -50 a 150°c, Resol 0, 1°c,...",12,"R$ 2.350,80"
3,72,202- 501-\n502,"Peneira Granulometrica Redonda Astm 3, 5-tyler...",6,"R$ 2.949,90"
4,73,202- 501-\n502,Peneira Granulometrica Redonda Astm 4-tyler/me...,6,"R$ 2.949,90"
5,74,202- 501-\n502,Peneira Granulometrica Redonda Astm 10-tyler/m...,6,"R$ 2.949,90"
6,75,202- 501-\n502,Peneira Granulometrica Redonda Astm 20-tyler/m...,6,"R$ 2.949,90"
7,76,202- 501-\n502,Peneira Granulometrica Redonda Astm 40-tyler/m...,6,"R$ 2.949,90"
8,77,202- 501-\n502,Peneira Granulometrica Redonda Astm 60-tyler/m...,6,"R$ 2.949,90"
9,78,202- 501-\n502,Peneira Granulometrica Redonda Astm 100-tyler/...,6,"R$ 2.949,90"
10,79,202- 501-\n502,"Peneira Granulometrica; Tampa, Em Aco Inoxidav...",6,"R$ 1.404,00"
11,80,202- 501-\n502,"Peneira Granulometrica; Fundo, Em Aco Inoxidav...",6,"R$ 1.404,00"
12,81,202- 501-\n502,"Aparelho Casagrande Manual, Com Cortador de Go...",4,"R$ 8.418,00"

Tabela 98

,0,1,2,3,4
0,,,Determinacao do Limite de Liquidez Dos Solos; ...,,
1,82,202- 501-\n502,"Pecas, Ferramentas, Acessorios para Fins Didat...",2,"R$ 735,16"
2,83,202- 501-\n502,Cronometro; para Controle de Tempo Em Aula Pra...,4,"R$ 392,60"
3,84,202- 501-\n502,"Paquimetro, Eletronico, 0-650mmPaquimetro; Pin...",2,"R$ 19.253,96"
4,85,202- 501-\n502,"Paquimetro, Eletronico, Modelo Digital, Mostra...",4,"R$ 9.960,00"
5,86,202- 501-\n502,"Trado Holandes P/ Coleta de Amostra de Solo, A...",2,"R$ 2.970,00"
6,87,202- 501-\n502,Bussola Bruton Portatil Com Variacao de 1 - 90...,8,"R$ 4.902,00"
7,88,202- 501-\n502,Estacao Total Eletronica; para Medir Angulos e...,4,"R$ 192.200,00"
8,89,202- 501-\n502,"Trena Eletronica Laser, 0, 05 a 80m, 360°, Com...",8,"R$ 5.380,08"

Tabela 99

,0,1,2,3,4
0,,,"0,001 Metro; Leitura Em Metros e Centimetros; ...",,
1,90,202- 501-\n502,"Trena Em Fibra de Vidro Revestida Vinil, Tipo ...",8,"R$ 786,80"
2,91,202- 501-\n502,Notebooks para serem utilizados em sala de aul...,1,"R$ 5.161,00"
3,92,202- 501-\n502,Notebooks para serem utilizados no laboratório...,35,"R$ 180.635,00"
4,93,202- 501-\n502,Caixa de som amplificadora,1,"R$ 389,00"
5,94,202- 501-\n502,"TVs 65""",10,"R$ 36.550,00"
6,95,202- 501-\n502,Plataforma de carregamento de Notebook,1,"R$ 6.000,00"
7,96,202- 501-\n502,Suporte para TV,1,"R$ 1.178,00"
8,97,202- 501-\n502,Banco de Madeira Para Mesa de Desenho 61cm,40,"R$ 18.118,40"
9,98,202- 501-\n502,Conjunto de mesa e cadeira para professor,1,"R$ 1.109,00"
10,99,202- 501-\n502,"Quadro não magnético branco, 4,00x1,20 m – Pad...",1,"R$ 1.423,00"
11,100,202- 501-\n502,"Quadro de aviso, madeira, revestido em fórmica...",1,"R$ 139,40"
12,101,202- 501-\n502,Armário de aço c/ 02 portas de abrir – Padrão CPS,3,"R$ 2.547,00"
13,102,202- 501-\n502,"Cabo Y, 1 HDMI macho, 2 HDMI fêmea – Padrão CPS",2,"R$ 105,30"
14,103,202- 501-\n502,Filtro de linha - 10 tomadas - 10A,1,"R$ 89,78"
15,104,202- 501-\n502,Cavalete para Desenho; Com Tampo; Confeccionad...,40,"R$ 46.320,00"
16,105,202- 501-\n502,Medidor de Ph de Bancada; Com Compensacao de T...,5,"R$ 7.557,40"
17,106,202- 501-\n502,Agitador Magnetico Conjunto Constituido de 6 A...,5,"R$ 7.055,00"

Tabela 100

,0,1,2,3,4
0,,,2 Colunas e 1 Suporte Horizontal; Inclui: Manu...,,
1,107,202- 501-\n502,"Balanca Semianalitica, Com Software de Calibra...",1,"R$ 3.784,00"
2,108,202- 501-\n502,Barra Imantada Magnetica 15x8mm (cxd) Barra Im...,20,"R$ 240,00"
3,109,202- 501-\n502,"Bico de Bunsen, Com Regulagem de Ar e Gas, Med...",8,"R$ 853,60"
4,110,202- 501-\n502,"Chapa de Cobre, (1200x600)mm, 3, 17mm; Chapa d...",15,"R$ 7.800,00"
5,111,202- 501-\n502,"Maquina Universal de Ensaios de Compressao, Ex...",1,"R$ 190.100,00"

Tabela 101

,0,1,2,3,4
0,,,P/ Ensai de Compressao; Software P/ Controle d...,,
1,112,202- 501-\n502,Parafusadeira; Em Plastico Rigido; Tipo Parafu...,1,"R$ 343,90"
2,113,202- 501-\n502,Jogo de Chave: jogo de Chave; Tipo Phillips (c...,4,"R$ 234,40"
3,114,202- 501-\n502,Ferramentas Manuais; para Montagem e Desmontag...,2,"R$ 475,70"
4,115,202- 501-\n502,Jogo de Ferramenta; Alicates Profissionais par...,2,"R$ 257,80"
5,116,202- 501-\n502,"Pecas, Ferramentas, Acessorios para Fins Didat...",8,"R$ 28.800,00"
6,117,202- 501-\n502,"Pecas, Ferramentas, Acessorios para Fins Didat...",8,"R$ 14.824,00"
7,118,202- 501-\n502,"Pecas, Ferramentas, Acessorios para Fins Didat...",8,"R$ 58.400,00"
8,119,202- 501-\n502,"Conjunto didatico: de cinematica e dinamica, m...",8,"R$ 11.696,00"

Tabela 102

,0,1,2,3,4
0,,,"e tampa em papel ondulado kraft, 01 base metal...",,
1,120,202- 501-\n502,"Conjunto didatico: Cinematica e dinamica, tril...",8,"R$ 51.872,00"
2,121,202- 501-\n502,"Conjunto didatico: Laboratorio de fisica, de b...",8,"R$ 6.000,00"
3,122,202- 501-\n502,Conjunto didatico: Laboratorio de energia reno...,8,"R$ 46.400,00"
4,123,202- 501-\n502,Especificação Técnica: Conjunto Didatico; para...,8,"R$ 18.528,00"
5,124,202- 501-\n502,Especificação Técnica: Conjunto Didatico; para...,8,"R$ 42.400,00"
6,125,202- 501-\n502,Especificação Técnica: Equipamentos para Fins ...,8,"R$ 120.000,00"
7,126,202- 501-\n502,Luximetro; Com Escala de 0 a 400.000 Lux; Port...,8,"R$ 9.174,00"

Tabela 103

,0,1,2,3,4
0,,,Luz Led Branca e Todas As Luzes Visiveis; Alim...,,
1,127,202- 501-\n502,Conjunto Didatico; para Experimentos de Eletri...,8,"R$ 11.200,00"
2,128,202- 501-\n502,"Osciloscopio; Digital, 4 Canais de Entrada Ana...",8,"R$ 40.720,00"
3,129,202- 501-\n502,"Furadeira, Parafusadeira, Mandril 3/8 Polegada...",1,"R$ 599,80"
4,130,202- 501-\n502,Balanca de Precisao; Eletronica; Utilizado par...,1,"R$ 2.508,21"
5,131,202- 501-\n502,Termometro Laboratorial; Quimico; Escala de -1...,1,"R$ 64,44"
6,132,202- 501-\n502,Balanca Determinadora de Umidade; Determinador...,1,"R$ 4.484,00"
7,133,202- 501-\n502,Estufa de Laboratorios de Solos e Materiais Be...,1,"R$ 4.861,82"

Tabela 104

,0,1,2,3,4
0,,,Aco Inox 430; Com 3 Prateleiras Em Aco Inox 43...,,
1,134,202- 501-\n502,"Martelete Perfurador Rompedor, Potencia 850w, ...",1,"R$ 1.596,00"
2,135,202- 501-\n502,"Argamassadeira, Alum.fund.e Aco, Capac.5l, 2 V...",1,"R$ 18.920,00"
3,136,202- 501-\n502,"Carro Transporte Manual Ferro, Assoalho Chapa ...",1,"R$ 1.590,00"
4,137,202- 501-\n502,"Equipamentos para Fins Didaticos, Esclerometro...",1,"R$ 2.598,00"
5,138,202- 501-\n502,Frasco de Chapman; Composto de Dois Bulbos Com...,2,"R$ 439,66"
6,139,202- 501-\n502,Frasco Le Chatelier Em Vidro Borossilicato Com...,2,"R$ 360,00"
7,140,202- 501-\n502,"Pecas, Ferramentas, Acessorios para Fins Didat...",2,"R$ 11.574,00"
8,141,202- 501-\n502,"Termostato Digital de Controle, 10a, 220v; Ter...",2,"R$ 149,26"

Tabela 105

,0,1,2,3,4
0,142,202- 501-\n502,"Bequer de Vidro de 250ml, Com Bico, Graduado e...",5,"R$ 77,85"
1,143,202- 501-\n502,"Bequer de Vidro de 500ml, Com Bico, Graduado e...",5,"R$ 88,20"
2,144,202- 501-\n502,"Erlenmeyer de Vidro; de 1000 Ml, Graduado; Vid...",5,"R$ 196,20"
3,145,202- 501-\n502,"Funil Analitico Em Vidro; Corpo Raiado, Diamet...",5,"R$ 170,00"
4,146,202- 501-\n502,Proveta de Vidro; Com Volume de 100 Ml; Classe...,5,"R$ 157,00"

Tabela 106

,0,1,2,3,4
0,,,"Permitida de ±0,50 Ml; Distancia Limite do Fin...",,
1,147,202- 501-\n502,Proveta de Vidro; Com Volume de 10 Ml; Classe ...,5,"R$ 125,00"
2,148,202- 501-\n502,Proveta de Vidro; Com Volume de 1000 Ml; Class...,5,"R$ 725,00"
3,149,202- 501-\n502,Proveta de Vidro; Com Volume de 500 Ml; Classe...,5,"R$ 575,00"
4,150,202- 501-\n502,"Aparelho de Vicat, com agulhas para inicio e f...",5,"R$ 10.962,90"

Tabela 107

,0,1,2,3,4
0,151,202- 501-\n502,"Conjunto de Slump teste completo, Slump test (...",5,"R$ 3.027,25"
1,152,202- 501-\n502,Forma para concreto. Conjunto de forma prismát...,2,"R$ 1.712,96"
2,153,202- 501-\n502,"Kit de serviços: Colher de Pedreiro 9""canto re...",5,"R$ 595,00"
3,154,202- 501-\n502,Formas em aluminio ou zinco para agregados.,10,"R$ 789,90"
4,155,202- 501-\n502,Betoneira; Em Aco; Capacidade do Tambor: 150 L...,1,"R$ 2.853,09"
5,156,202- 501-\n502,Paquimetro; Aco Inoxidavel Temperado de Alta R...,10,"R$ 29.804,40"
6,157,202- 501-\n502,Paquimetro; Em Aco Inoxidavel Temperado de Alt...,10,"R$ 21.099,00"
7,158,202- 501-\n502,Micrometro; Arco Esmaltado; Tambor e Bainha Co...,10,"R$ 3.464,90"
8,159,202- 501-\n502,"Pecas, Ferramentas, Acessorios para Fins Didat...",8,"R$ 8.496,00"
9,160,202- 501-\n502,Balanca; Tipo Digital Eletronica; Visor Com Di...,1,"R$ 1.762,25"
10,161,202- 501-\n502,Medidor de Ph para Sol Aquosas de 0 a 14 Un Ph...,5,"R$ 5.935,15"

Tabela 108

,0,1,2,3,4
0,,,Dimensoes: 4 Baterias de 1.5v E/ou Cabo de Ali...,,
1,162,202- 501-\n502,Tubo de Ensaio; Em Vidro Neutro; Sem Orla; Ter...,40,"R$ 29,20"
2,163,202- 501-\n502,Agitador Magnetico Conjunto Constituido de 6 A...,5,"R$ 32.815,00"
3,164,202- 501-\n502,"Barra Magnetica Revestida de Teflon 10 Mm x 3,...",20,"R$ 413,60"
4,165,202- 501-\n502,"Balanca Semianalitica, Com Software de Calibra...",1,"R$ 11.767,87"
5,166,202- 501-\n502,"Espatula de Metal e Titanio, Dupla C/ 1 Ponta ...",20,"R$ 764,40"
6,167,202- 501-\n502,Proveta de Vidro 100 Ml Proveta de Vidro; Prov...,20,"R$ 313,00"

Tabela 109

,0,1,2,3,4
0,,,Especif.: Linhas Longas a Cada Dez Linhas; Ins...,,
1,168,202- 501-\n502,Bequer de Vidro Forma Baixa 100 Ml Graduado Pa...,20,"R$ 130,00"
2,169,202- 501-\n502,"Bico de Bunsen, Com Regulagem de Ar e Gas, Med...",8,"R$ 767,12"
3,170,202- 501-\n502,Insumos Uso Laboratorial Bequer Forma Baixa 15...,20,"R$ 141,60"
4,171,202- 501-\n502,"Chapa de Cobre, (1200x600)mm, 3, 17mm; Chapa d...",15,"R$ 2.998,35"
5,172,202- 501-\n502,Telas de amianto para Bico de Bunsen,8,"R$ 247,20"
6,173,202- 501-\n502,"Pano de Limpeza; Composto de 100% Algodao, Abs...",10,"R$ 28,90"
7,174,202- 501-\n502,Fio de Cobre Esmaltado; Flexivel; Sem Capa Iso...,5,"R$ 537,00"
8,175,202- 501-\n502,Alicate Amperímetro.,4,"R$ 1.119,92"
9,,,Total geral,None,"R$\n4.235.905,46"

Tabela 110

,0,1,2,3,4,5,6,7
0,Item,,Projeto,,,Denominação,,Prazo
1,None,None,(XYY),None,None,(O que será feito),None,None
2,01,101,None,None,Aumentar a demanda do uso da Biblioteca/ Bibli...,None,None,20/12/2025
3,02,102,None,None,Continuar o que já foi iniciado com a Visitaçã...,None,None,20/12/2025
4,03,103,None,None,Aumentar a Participação de Eventos entre Fatecs,None,None,20/12/2025
5,04,202,None,None,"Implantação dos Laboratórios dos cursos, promo...",None,None,20/12/2025
6,05,303,None,None,Monitoria de Iniciação Científica,None,None,20/12/2025
7,06,304,None,None,Desenvolvimento de projeto de extensão para a ...,None,None,20/12/2025
8,07,306,None,None,"Estudo, pesquisa e extensão - SIMET & NEPA",None,None,20/12/2025
9,08,307,None,None,Pesquisa sobre Visão Computacional,None,None,20/12/2025
10,09,501,None,None,"Aumento do Acesso a rede Wi‐Fi e Internet, pri...",None,None,20/12/2025
11,10,502,None,None,"Criação, configuração e adequação dos laborató...",None,None,20/12/2025
12,11,601,None,None,"Capacitação dos coordenadores, administrativo ...",None,None,20/12/2025
13,12,602,None,None,Desenvolver ações proposta pela C.P. A,None,None,20/12/2025
14,13,nnn,None,None,nn,None,None,dd/mm/aaaa
15,14,nnn,None,None,nn,None,None,dd/mm/aaaa
16,15,nnn,None,None,nn,None,None,dd/mm/aaaa
17,16,nnn,None,None,nn,None,None,dd/mm/aaaa
18,17,nnn,None,None,nn,None,None,dd/mm/aaaa
19,18,nnn,None,None,nn,None,None,dd/mm/aaaa
20,19,nnn,None,None,nn,None,None,dd/mm/aaaa
21,20,nnn,None,None,nn,None,None,dd/mm/aaaa
22,,,None,None,,None,None,

Tabela 111

,0,1,2,3,4,5,6,7,8,9,10
0,,RAF – Relatório de Assistência à Fatec,None,None,None,None,None,None,None,None,
1,,Assunto:,,,RAF – Assistência ao PGA/2024 (Plano de Gestão...,None,None,None,None,,None
2,,Atribuição:,,"DGE-0-06: Assistir às Fatecs na elaboração, na...",DGE-0-06:,None,None,None,None,None,None
3,,Data:,,de 23/04/2024\na 08/05/2024,None,,Origem:,,Cesu – Gestão Educacional\ncesu.gestaoeducacio...,None,None

Tabela 112

                                                   0
0  Referência: Assistência à elaboração e operaci...
1                     Fatec 301\nUnidade de Ensino –

Tabela 113

,0,1,2,3,4,5,6,7,8,9,10
0,,Ajustes do Plano de Gestão Anual,None,None,,,Status,,,Síntese da atividade,
1,1,1,,Ações/Projetos de Melhorias do PGA,None,None,None,None,None,None,
2,None,None,0) Revisão da folha de rosto (Cenário/ Situaçõ...,None,None,Inalterado,None,None,xx,None,None
3,None,None,1) Ajustes de projetos do Eixo 1\nDidático Ped...,None,None,Revisado,None,None,xx,None,None
4,None,None,2) Ajustes de projetos do Eixo 2\nEnsino e Equ...,None,None,Inalterado,None,None,xx,None,None
5,None,None,3) Ajustes de projetos do Eixo 3\nPesquisa/Ext...,None,None,Inalterado,None,None,xx,None,None
6,None,None,4) Ajustes de projetos do Eixo 4\nAtividades F...,None,None,Inalterado,None,None,xx,None,None
7,None,None,5) Ajustes de projetos do Eixo 5\nInfraestrutura,None,None,Inalterado,None,None,xx,None,None
8,None,None,6) Ajustes de projetos do Eixo 6\nDesenvolvime...,None,None,Inalterado,None,None,xx,None,None
9,None,None,7) Ajustes de projetos do Eixo 7\nConvênios e ...,None,None,Inalterado,None,None,xx,None,None
10,2,None,,Questões suplementares ao PGA,None,None,None,None,None,None,
11,None,None,1) Inserção do campo de GRD (Gerenciamento da\...,None,None,Inalterado,None,None,xx,None,None
12,None,None,2) Inserção da lista de equipamentos a serem\n...,None,None,Revisado,None,None,Inserção de lista atualizada CST Controle de\n...,None,None
13,None,None,3) Inserção de projetos de Inclusão,None,None,Inalterado,None,None,xx,None,None
14,None,None,4) Inserção de projetos de Sustentabilidade,None,None,Inalterado,None,None,xx,None,None
15,None,None,5) Inserção de projetos de pesquisa tecnológic...,None,None,Inalterado,None,None,xx,None,None
16,None,None,6) Análise do Engajamento da comunidade\nacadê...,None,None,Realizada,None,None,xx,None,None
17,3,None,,Análise conjunta das condições da unidade,None,None,None,None,None,None,
18,None,None,1) Verificação das condições de ensino nos\nam...,None,None,Requer melhorias para\npleno uso,None,None,Os laboratórios CST Controle de Obras não\nfor...,None,None

Tabela 114

,0,1,2,3
0,,,,mesmo motivo e CST Ciências de Dados para\nNeg...
1,,2) Verificação da Organização dos Laboratórios...,Plena organização e\ngestão laboratorial,Os laboratórios existentes estão muito\norgani...
2,,3) Verificação da quantidade de alunos que req...,Identificado quantitativo\nde alunos com\ndefi...,03 alunos
3,,4) Verificação das condições de inclusão\n(ace...,Possui elementos de\nacessibilidade em todos\n...,xx
4,,5) Verificação dos recursos de inclusão para\n...,Não possui recursos\nespecíficos de inclusão\n...,Os alunos não necessitam de recursos.

Tabela 115

,0,1,2,3,4,5,6,7,8
0,,,,,Quantidade de Ações/Projetos constantes no PGA:,,,(apenas número),
1,01,None,None,no eixo (1) Didático Pedagógico,None,None,06,None,None
2,02,None,None,no eixo (2) Ensino e Equipamentos Associados (...,None,None,04,None,None
3,03,None,None,no eixo (3) Pesquisa/Extensão e Equipamentos A...,None,None,04,None,None
4,04,None,None,no eixo (4) Atividades Formativas em Projetos,None,None,04,None,None
5,05,None,None,no eixo (5) Infraestrutura,None,None,03,None,None
6,06,None,None,no eixo (6) Desenvolvimento de pessoas,None,None,02,None,None
7,07,None,None,no eixo (7) Convênios e Parcerias Institucionais,None,None,01,None,None
8,08,None,None,total no PGA da UE (Somatória – Apenas clicar ...,None,None,,24,
9,None,None,None,None,None,None,None,,None
10,09,None,None,com uso de bolsas de Monitoria,None,None,03,None,None
11,10,None,None,com uso de bolsas de Monitoria para Pesquisa (...,None,None,06,None,None
12,11,None,None,para a Inclusão de alunos com deficiência e tr...,None,None,00,None,None
13,12,None,None,para a Sustentabilidade da UE,None,None,01,None,None

Tabela 116

,0,1,2,3,4,5,6,7,8
0,,None,None,Carga horária (horas por semana),None,None,,None,None
1,13,None,None,total de HA,None,None,162,None,None
2,14,None,None,total de HAE,None,None,27,None,None
3,15,None,None,total de HP,None,None,00,None,None
4,16,None,None,total de H,None,None,00,None,None
5,,17,,,total geral da carga horária (Somatória – Apen...,,,189,

Tabela 117

  0   1 2 3                                                  4 5 6   7 8
0    18      Total de Ações/Projetos incluídos e revisados ...      24

Tabela 118

                                0
0  Análise do cenário:\nDe acordo
1  Situações problema:\nDe acordo
2           Objetivos:\nDe acordo
3               Metas:\nDe acordo

Tabela 119

                          0     1
0              AÇÃO/PROJETO    xx
1         O que será feito:    xx
2       Por que será feito:    xx
3      Responsável(is) / CH    xx
4                      sem:  None
5      Período de execução:    xx
6       Etapas do processo:    xx
7        Custo (se houver):    xx
8    Fonte(s) dos recursos:    xx
9               Objetivo(s)    xx
10          relacionado(s):  None
11  Meta(s) relacionada(s):    xx

Tabela 120

                       0                                                  1
0                         Atenção: Re-codificação das Ações/Projetos da ...
1                   None       X para o eixo (1, 2, 3, ...) da Ação/Projeto
2                   None   Y para sequencial (01, 02, 03, ...) quantitativo
3           AÇÃO/PROJETO                                               None
4                   None                                          Exemplos:
5                                                                      None
6                   None  • Os projetos do eixo 1 (Didático Pedagógico) ...
7                   None  • Os projetos do eixo 5 (Infraestrutura) serão...
8      O que será feito:  Indicação da atividade principal da ação sem d...
9    Por que será feito:  Motivação estratégica do CPS e tática da Unida...
10                        Especificação da pessoa responsável e dos cola...
11  Responsável(is) / CH                                               None
12                  sem:                                               None
13                                                                     None
14                        Indicação com exatidão do dia (dd), mês (mm) e...
15  Período de execução:                                               None
16                                                                     None
17                        Etapas são trabalhos cabíveis à própria Unidad...
18   Etapas do processo:                                               None
19                                                                     None

Tabela 121

                         0                                                  1
0                           Desenvolvimento das atividades de ...\nDesigna...
1                           O lançamento do valor orçado/estimado deverá s...
2       Custo (se houver):                                               None
3                                                                        None
4                           Especificação da fonte como DMPP, DL, ou Licit...
5   Fonte(s) dos recursos:                                               None
6                                                                        None
7              Objetivo(s)  Pré lançados na “Folha de rosto” do PGA. Não s...
8          relacionado(s):                                               None
9  Meta(s) relacionada(s):  Pré lançadas na “Folha de rosto” do PGA. Não s...

Tabela 122

,0,1,2,3
0,Inclusão,None,None,"Estacionamento, piso tátil, rampa, corrimão, a..."
1,Sustentabilidade,None,None,"Produção ou uso de energia renovável, reuso de..."
2,,Inovação,,Projetos de pesquisa e desenvolvimento tecnoló...

Tabela 123

,0,1,2,3,4,5,6,7,8
0,,CST em xx,None,None,None,None,None,None,
1,Disciplina,Disciplina,"Classe\n(3, 4 ou 5)",,Aulas,,Laboratório,Laboratório,None
2,None,None,None,None,Práticas,None,None,None,None
3,None,None,None,None,(h),None,None,None,None
4,,None,Escolher um item.,xx,None,None,xx,None,None
5,xx,None,Escolher um item.,xx,None,None,xx,None,None
6,xx,None,Escolher um item.,xx,None,None,xx,None,None
7,xx,None,Escolher um item.,xx,None,None,xx,None,None
8,xx,None,Escolher um item.,xx,None,None,xx,None,None
9,xx,None,Escolher um item.,xx,None,None,xx,None,None
10,xx,None,Escolher um item.,xx,None,None,xx,None,None
11,xx,None,Escolher um item.,xx,None,None,xx,None,None
12,xx,None,Escolher um item.,xx,None,None,xx,None,None
13,xx,None,Escolher um item.,xx,None,None,xx,None,None
14,,None,,,None,None,,None,None
15,,None,,,None,None,,None,None
16,,None,,,None,None,,None,None

Tabela 124

             0
0       Classe
1  (3, 4 ou 5)

Tabela 125

,0,1,2,3,4,5,6,7,8
0,,CST em xx,None,None,None,None,None,None,
1,Disciplina,Disciplina,"Classe\n(3, 4 ou 5)",,Aulas,,Laboratório,Laboratório,None
2,None,None,None,None,Práticas,None,None,None,None
3,None,None,None,None,(h),None,None,None,None
4,xx,None,Escolher um item.,xx,None,None,xx,None,None
5,xx,None,Escolher um item.,xx,None,None,xx,None,None
6,xx,None,Escolher um item.,xx,None,None,xx,None,None
7,xx,None,Escolher um item.,xx,None,None,xx,None,None
8,xx,None,Escolher um item.,xx,None,None,xx,None,None
9,xx,None,Escolher um item.,xx,None,None,xx,None,None
10,xx,None,Escolher um item.,xx,None,None,xx,None,None
11,xx,None,Escolher um item.,xx,None,None,xx,None,None
12,xx,None,Escolher um item.,xx,None,None,xx,None,None
13,xx,None,Escolher um item.,xx,None,None,xx,None,None
14,,None,,,None,None,,None,None

Tabela 126

             0
0       Classe
1  (3, 4 ou 5)

Tabela 127

,0,1,2,3,4,5,6,7,8
0,,CST em xx,None,None,None,None,None,None,
1,Disciplina,Disciplina,"Classe\n(3, 4 ou 5)",,Aulas,,Laboratório,Laboratório,None
2,None,None,None,None,Práticas,None,None,None,None
3,None,None,None,None,(h),None,None,None,None
4,xx,None,Escolher um item.,xx,None,None,xx,None,None
5,xx,None,Escolher um item.,xx,None,None,xx,None,None
6,xx,None,Escolher um item.,xx,None,None,xx,None,None
7,xx,None,Escolher um item.,xx,None,None,xx,None,None
8,xx,None,Escolher um item.,xx,None,None,xx,None,None
9,xx,None,Escolher um item.,xx,None,None,xx,None,None
10,xx,None,Escolher um item.,xx,None,None,xx,None,None
11,xx,None,Escolher um item.,xx,None,None,xx,None,None
12,xx,None,Escolher um item.,xx,None,None,xx,None,None
13,xx,None,Escolher um item.,xx,None,None,xx,None,None
14,,None,,,None,None,,None,None

Tabela 128

             0
0       Classe
1  (3, 4 ou 5)

Tabela 129

,0,1,2,3,4,5,6,7,8
0,,CST em xx,None,None,None,None,None,None,
1,Disciplina,Disciplina,"Classe\n(3, 4 ou 5)",,Aulas,,Laboratório,Laboratório,None
2,None,None,None,None,Práticas,None,None,None,None
3,None,None,None,None,(h),None,None,None,None
4,xx,None,Escolher um item.,xx,None,None,xx,None,None
5,xx,None,Escolher um item.,xx,None,None,xx,None,None
6,xx,None,Escolher um item.,xx,None,None,xx,None,None
7,xx,None,Escolher um item.,xx,None,None,xx,None,None
8,xx,None,Escolher um item.,xx,None,None,xx,None,None
9,xx,None,Escolher um item.,xx,None,None,xx,None,None
10,xx,None,Escolher um item.,xx,None,None,xx,None,None
11,xx,None,Escolher um item.,xx,None,None,xx,None,None
12,xx,None,Escolher um item.,xx,None,None,xx,None,None
13,xx,None,Escolher um item.,xx,None,None,xx,None,None
14,,None,,,None,None,,None,None

Tabela 130

             0
0       Classe
1  (3, 4 ou 5)

Tabela 131

,0,1,2,3,4,5,6,7,8
0,,CST em xx,None,None,None,None,None,None,
1,Disciplina,Disciplina,"Classe\n(3, 4 ou 5)",,Aulas,,Laboratório,Laboratório,None
2,None,None,None,None,Práticas,None,None,None,None
3,None,None,None,None,(h),None,None,None,None
4,xx,None,Escolher um item.,xx,None,None,xx,None,None
5,xx,None,Escolher um item.,xx,None,None,xx,None,None
6,xx,None,Escolher um item.,xx,None,None,xx,None,None
7,xx,None,Escolher um item.,xx,None,None,xx,None,None
8,xx,None,Escolher um item.,xx,None,None,xx,None,None
9,xx,None,Escolher um item.,xx,None,None,xx,None,None
10,xx,None,Escolher um item.,xx,None,None,xx,None,None
11,xx,None,Escolher um item.,xx,None,None,xx,None,None
12,xx,None,Escolher um item.,xx,None,None,xx,None,None
13,xx,None,Escolher um item.,xx,None,None,xx,None,None
14,,None,,,None,None,,None,None

Tabela 132

             0
0       Classe
1  (3, 4 ou 5)

Tabela 133

,0,1,2,3,4,5,6,7,8
0,,CST em xx,None,None,None,None,None,None,
1,Disciplina,Disciplina,"Classe\n(3, 4 ou 5)",,Aulas,,Laboratório,Laboratório,None
2,None,None,None,None,Práticas,None,None,None,None
3,None,None,None,None,(h),None,None,None,None
4,xx,None,Escolher um item.,xx,None,None,xx,None,None
5,xx,None,Escolher um item.,xx,None,None,xx,None,None
6,xx,None,Escolher um item.,xx,None,None,xx,None,None
7,xx,None,Escolher um item.,xx,None,None,xx,None,None
8,xx,None,Escolher um item.,xx,None,None,xx,None,None
9,xx,None,Escolher um item.,xx,None,None,xx,None,None
10,xx,None,Escolher um item.,xx,None,None,xx,None,None
11,xx,None,Escolher um item.,xx,None,None,xx,None,None
12,xx,None,Escolher um item.,xx,None,None,xx,None,None
13,xx,None,Escolher um item.,xx,None,None,xx,None,None
14,,None,,,None,None,,None,None

Tabela 134

             0
0       Classe
1  (3, 4 ou 5)

Tabela 135

,0,1,2,3
0,CST em DSM,None,None,None
1,Disciplina,Classe,Aulas,Laboratório
2,,"(3, 4 ou 5)",Práticas,
3,None,,(h),None
4,Algoritmos e Lógica de Programação,4,4,4
5,Desenvolvimento Web I,4,4,4
6,Design Digital,4,4,4
7,Engenharia de Software I,4,4,2
8,Modelagem de Banco de Dados,4,4,4
9,Sistemas Operacionais e Redes de Comp.,4,4,4
10,Técnicas de Programação I,4,4,4
11,Desenvolvimento Web II,4,4,4
12,Matemática para computação,3,4,2
13,Engenharia de Software II,4,4,2
14,Banco de Dados – Relacional,4,4,4
15,Estrutura de Dados,4,4,4
16,Técnicas de Programação II,4,4,4
17,Desenvolvimento Web III,4,4,4
18,Gestão Ágil de Projetos de Software,4,4,4
19,Banco de Dados - Não Relacional,4,4,4
20,Interação Humano Computador,4,2,2
21,Integração e Entrega Contínua,4,4,4
22,Laboratório de Desenvolvimento Web,4,4,4
23,Internet das Coisas e Aplicações,4,4,4
24,Programação para Dispositivos Móveis I,4,4,4
25,Estatística Aplicada,4,2,2
26,Experiência do Usuário,4,2,2
27,Computação em Nuvem I,4,4,4
28,Aprendizagem de Máquina,4,4,4
29,Lab. de Des. para Dispositivos Móveis,4,4,4
30,Programação para Dispositivos Móveis II,4,4,4
31,Segurança no Des. de Aplicações,4,4,4
32,Computação em Nuvem II,4,4,4
33,Processamento de Linguagem Natural,4,4,4
34,Laboratório de Des. Multiplataforma,4,4,4
35,Mineração de Dados,4,4,4
36,Qualidade e Testes de Software,4,4,4
37,Ética Profissional e Patente,3,2,2
38,Álgebra Linear,3,4,2
39,Fundamentos da Redação técnica,3,2,2

Tabela 136

,0,1,2,3
0,CST em CONTROLE DE OBRAS,None,None,None
1,Disciplina,Classe,Aulas,Laboratório
2,,"(3, 4 ou 5)",Práticas,
3,None,,(h),None
4,Mecânica Clássica,5,40,Laboratório de Física x
5,Eletricidade Aplicada,5,40,Laboratório de Física
6,Introdução à Ensaios e Controle\nTecnológico,5,40,Laboratório de Física
7,Química Aplicada à Construção Civill,5,40,Laboratório de Química

Tabela 137

,0,1,2,3
0,Desenho Técnico Aplicado à Construção Civil I,5,40,Laboratório de Desenho I
1,Desenho Técnico Aplicado à Construção Civil II,4,40,Laboratório de Desenho IIx
2,Topografia,5,40,Laboratório de Solos
3,Eletrotécnica Aplicada,4,40,Laboratório de Física
4,Mecânica dos Solos e Fundações,5,40,Laboratório de Solos
5,Materiais de Construção Civil II,5,xx,Lab. de Materiais de Construção
6,Hidrologia e Hidráulica Aplicada,4,20,Laboratório de Hidráulica
7,Fundamentos de Georreferenciamento\nAplicado,4,20,Laboratório de Informática
8,Obras de Terra,4,20,Laboratório de Solos
9,Instalações Hidráulicas e Sanitárias,4,20,Laboratório de Hidráulica
10,Materiais de Construção Civil,5,40,Lab. de Materiais de Construção
11,Estradas,5,40,Laboratório de Pavimentação

Tabela 138

,0,1,2
0,Tipo do laboratório ou ambiente,CSTs que utilizam o ambiente,Localização
1,Laboratório de Informática Básica,Controle de Obras e Desenvolvimento,Na unidade
2,,de Software Multiplataforma,
3,Detalhamento,None,None
4,Laboratório multidisciplina de Informática Básica,None,None
5,Recurso,None,Quantidade
6,,None,
7,Notebooks,None,82
8,TV 65 polegadas,None,2
9,Roteador,None,2
10,Aparelho de ar-condicionado,None,2

Tabela 139

,0,1,2,3,4,5
0,,Eixo,,,Código da Ação/Projeto,
1,(1) Didático Pedagógico,None,None,xx,None,None
2,,(2) Ensino e Equipamentos Associados,,xx,None,None
3,None,(Laboratórios),None,None,None,None
4,(3) Pesquisa/Extensão e Equipamentos\nAssociados,None,None,xx,None,None
5,,(4) Atividades Formativas em Projetos,,,xx,
6,(5) Infraestrutura,None,None,xx,None,None
7,,(6) Desenvolvimento de pessoas,,,xx,
8,(7) Convênios e Parcerias Institucionais,None,None,xx,None,None

In [15]:
for i, texto in enumerate(textos_extraidos[:3]):
    print(f"\n Trecho de texto da página {i+1}:\n")
    print(texto[:1000])

 Trecho de texto da página 1:

PLANO DE GESTÃO ANUAL
PGA 2025
V04
Estruturado em uma única etapa, contendo 2 anexos:
PLANEJAMENTO PELA EQUIPE GESTORA DA UE
• Anexo 1 – Lista de equipamentos necessários aos projetos
• Anexo 2 – Lista de Ações/Projetos referentes à CPA (Origem 3: Gestão Tática – CPA)
IDENTIFICAÇÃO DA UNIDADE
Unidade código F301 Fatec Votorantim
Diretor(a) Prof. Dr. Mauro Tomazela
PLANEJAMENTO PELA EQUIPE GESTORA DA UE
(Administração da Faculdade - Deliberação CEETEPS 31/2016)
ANÁLISE DO CENÁRIO
Descrever de forma breve e objetiva o cenário da Unidade perante sua missão como Unidade de Ensino na localidade em que
se encontra (é este cenário que se pretende melhorar).
Votorantim, um município da região metropolitana de Sorocaba, no interior de São Paulo, inaugurou em 2022 a Fatec
Votorantim, que ofereceu à comunidade 80 vagas semestrais, distribuídas entre os seguintes cursos:
Controle de Obras: 40 vagas (noturno)
Desenvolvimento de Software Multiplataforma: 40 vagas (noturno)
A partir do segundo semest

 Trecho de texto da página 2:

Objetivos Institucionais – CPS (Plano de Metas)
1) Atender às demandas sociais e do mercado de trabalho.
2) Obter a satisfação dos públicos que se relacionam com o Centro Paula Souza (stakeholders).
3) Alcançar e manter o grau de excelência em seus processos de ensino e aprendizagem.
4) Assegurar a perenidade do crescimento da instituição com recursos financeiros disponíveis.
5) Garantir celeridade e efetividade na prestação de serviços.
6) Formar profissionais atualizados em tecnologias e processos produtivos, capazes de atuar no desenvolvimento tecnológico e inovação.
7) Promover a cultura de inovação e empreendedorismo.
8) Aumentar a eficiência, a produtividade e a competitividade da instituição.
9) Ampliar a oferta da Educação Profissional.
10) Resolução Conjunta SOG/SFP/SG-3, de 28-12-2022 - Bonificação por Resultados – BR das Secretarias de Estado, Procuradoria Geral do Estado,
Controladoria Geral do Estado e das Autarquias, de que trata a LC 1361-2021
Objetivos Institucionais –

 Trecho de texto da página 3:

ESTRUTURAÇÃO DAS AÇÕES/PROJETOS
01 - Didático-pedagógico
Ações associadas ao PPC/PE de CSTs e Disciplinas: CST (implantação, alteração, readequação, reestruturação),
prática pedagógica (PE, PA), projeto interdisciplinar/ integrador, extensão curricularizada.
AÇÃO/PROJETO (Tema) 101 - cat 1.04 - Biblioteca Ativa e aquisição de bibliografias
Origem (prioridade): 3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebSAI, RAAI)
Planejamento/ organização/ instalação de infraestrutura e mobiliários / organização de acesso
O que será feito:
lógico ao acervo/ compra e catalogação.
Por que será feito: Para incentivar o uso da biblioteca da unidade e atendimento de demandas legais
<nome> Júlia Cristina Gütschow Sampaio Qde CH/sem: 5 Tipo: H - Hora <não
Responsável:
tipificada>
Colaborador(a): <nome> nn Qde CH/sem: nn Tipo: Escolher um item.
Colaborador(a): <nome> nn Qde CH/sem: nn Tipo: Escolher um item.
Período de execução: Data inicial: 17/02/2025 Data final: 19/12/2025
Etapas do processo: 01- Planejam

In [17]:
print(f" Total de tabelas extraídas: {len(tabelas_extraidas)}")

# Ver os tamanhos das tabelas
for i, tabela in enumerate(tabelas_extraidas):
    print(f"Tabela {i+1} - {len(tabela)} linhas")

 Total de tabelas extraídas: 139
Tabela 1 - 3 linhas
Tabela 2 - 3 linhas
Tabela 3 - 4 linhas
Tabela 4 - 8 linhas
Tabela 5 - 4 linhas
Tabela 6 - 3 linhas
Tabela 7 - 24 linhas
Tabela 8 - 23 linhas
Tabela 9 - 23 linhas
Tabela 10 - 24 linhas
Tabela 11 - 17 linhas
Tabela 12 - 14 linhas
Tabela 13 - 28 linhas
Tabela 14 - 25 linhas
Tabela 15 - 3 linhas
Tabela 16 - 33 linhas
Tabela 17 - 25 linhas
Tabela 18 - 2 linhas
Tabela 19 - 22 linhas
Tabela 20 - 34 linhas
Tabela 21 - 17 linhas
Tabela 22 - 19 linhas
Tabela 23 - 29 linhas
Tabela 24 - 28 linhas
Tabela 25 - 23 linhas
Tabela 26 - 21 linhas
Tabela 27 - 15 linhas
Tabela 28 - 8 linhas
Tabela 29 - 23 linhas
Tabela 30 - 3 linhas
Tabela 31 - 27 linhas
Tabela 32 - 25 linhas
Tabela 33 - 19 linhas
Tabela 34 - 19 linhas
Tabela 35 - 22 linhas
Tabela 36 - 19 linhas
Tabela 37 - 2 linhas
Tabela 38 - 2 linhas
Tabela 39 - 4 linhas
Tabela 40 - 21 linhas
Tabela 41 - 23 linhas
Tabela 42 - 23 linhas
Tabela 43 - 19 linhas
Tabela 44 - 17 linhas
Tabela 45 - 5 linhas
Tabela 46 - 25 linhas
Tabela 47 - 23 linhas
Tabela 48 - 7 linhas
Tabela 49 - 20 linhas
Tabela 50 - 23 linhas
Tabela 51 - 23 linhas
Tabela 52 - 24 linhas
Tabela 53 - 24 linhas
Tabela 54 - 3 linhas
Tabela 55 - 23 linhas
Tabela 56 - 29 linhas
Tabela 57 - 19 linhas
Tabela 58 - 19 linhas
Tabela 59 - 29 linhas
Tabela 60 - 2 linhas
Tabela 61 - 2 linhas
Tabela 62 - 2 linhas
Tabela 63 - 3 linhas
Tabela 64 - 29 linhas
Tabela 65 - 19 linhas
Tabela 66 - 27 linhas
Tabela 67 - 19 linhas
Tabela 68 - 23 linhas
Tabela 69 - 22 linhas
Tabela 70 - 7 linhas
Tabela 71 - 14 linhas
Tabela 72 - 2 linhas
Tabela 73 - 4 linhas
Tabela 74 - 25 linhas
Tabela 75 - 35 linhas
Tabela 76 - 19 linhas
Tabela 77 - 19 linhas
Tabela 78 - 28 linhas
Tabela 79 - 33 linhas
Tabela 80 - 2 linhas
Tabela 81 - 2 linhas
Tabela 82 - 4 linhas
Tabela 83 - 31 linhas
Tabela 84 - 20 linhas
Tabela 85 - 33 linhas
Tabela 86 - 3 linhas
Tabela 87 - 2 linhas
Tabela 88 - 10 linhas
Tabela 89 - 2 linhas
Tabela 90 - 1 linhas
Tabela 91 - 13 linhas
Tabela 92 - 16 linhas
Tabela 93 - 12 linhas
Tabela 94 - 8 linhas
Tabela 95 - 9 linhas
Tabela 96 - 8 linhas
Tabela 97 - 13 linhas
Tabela 98 - 9 linhas
Tabela 99 - 18 linhas
Tabela 100 - 6 linhas
Tabela 101 - 9 linhas
Tabela 102 - 8 linhas
Tabela 103 - 8 linhas
Tabela 104 - 9 linhas
Tabela 105 - 5 linhas
Tabela 106 - 5 linhas
Tabela 107 - 11 linhas
Tabela 108 - 7 linhas
Tabela 109 - 10 linhas
Tabela 110 - 23 linhas
Tabela 111 - 4 linhas
Tabela 112 - 2 linhas
Tabela 113 - 19 linhas
Tabela 114 - 5 linhas
Tabela 115 - 14 linhas
Tabela 116 - 6 linhas
Tabela 117 - 1 linhas
Tabela 118 - 4 linhas
Tabela 119 - 12 linhas
Tabela 120 - 20 linhas
Tabela 121 - 10 linhas
Tabela 122 - 3 linhas
Tabela 123 - 17 linhas
Tabela 124 - 2 linhas
Tabela 125 - 15 linhas
Tabela 126 - 2 linhas
Tabela 127 - 15 linhas
Tabela 128 - 2 linhas
Tabela 129 - 15 linhas
Tabela 130 - 2 linhas
Tabela 131 - 15 linhas
Tabela 132 - 2 linhas
Tabela 133 - 15 linhas
Tabela 134 - 2 linhas
Tabela 135 - 40 linhas
Tabela 136 - 8 linhas
Tabela 137 - 12 linhas
Tabela 138 - 11 linhas
Tabela 139 - 9 linhas

In [18]:
df1 = pd.DataFrame(tabelas_extraidas[0])
df1.head(10)

                       0
0  PLANO DE GESTÃO ANUAL
1               PGA 2025
2                    V04

In [19]:
if len(tabelas_extraidas) > 1:
    df2 = pd.DataFrame(tabelas_extraidas[1])
    df2.head(10)

In [20]:
for i, tabela in enumerate(tabelas_extraidas):
    print(f"\n Estrutura da Tabela {i+1}")
    df = pd.DataFrame(tabela)
    print(df.head(5))

 Estrutura da Tabela 1
                       0
0  PLANO DE GESTÃO ANUAL
1               PGA 2025
2                    V04

 Estrutura da Tabela 2
            0                         1                         2  \
0              IDENTIFICAÇÃO DA UNIDADE                      None
1     Unidade                      None               código F301
2  Diretor(a)                      None  Prof. Dr. Mauro Tomazela

                  3     4
0              None
1  Fatec Votorantim  None
2              None  None

 Estrutura da Tabela 3
                                                   0  \
0
1                                               None
2                                               None
3  Votorantim, um município da região metropolita...

                                                   1     2
0                                 ANÁLISE DO CENÁRIO
1  Descrever de forma breve e objetiva o cenário ...  None
2  se encontra (é este cenário que se pretende me...  None
3                                               None  None

 Estrutura da Tabela 4
      0                                                  1  \
0        APONTAMENTO DE SITUAÇÕES-PROBLEMA MAIS RELEVANTES
1  None  Fontes: relatório CPA, análise de processos cr...
2  None  relatório de representação discente (DA, Atlét...
3     1                                               None
4     2                                               None

                                                   2     3     4  \
0                                               None  None  None
1                                               None  None  None
2                                               None  None  None
3  cat 0.1.01 - Metodologia de ensino, desempenho...           5
4      cat 0.1.02 - Manutenção e conservação predial  None     6

                                                   5     6
0                                               None
1                                               None  None
2                                               None  None
3  cat 0.1.07 - Comunicação com a comunidade\naca...  None
4  cat 0.1.08 - Participação da comunidade e soci...  None

 Estrutura da Tabela 5
                                                   0  \
0
1  1) Atender às demandas sociais e do mercado de...
2
3  A. Integrar as diferentes modalidades de ensin...

                                                  1     2
0   Objetivos Institucionais – CPS (Plano de Metas)
1                                              None  None
2  Objetivos Institucionais – Cesu (Plano de Metas)
3                                              None  None

 Estrutura da Tabela 6
                                                   0
0                           01 - Didático-pedagógico
1  Ações associadas ao PPC/PE de CSTs e Disciplin...
2  prática pedagógica (PE, PA), projeto interdisc...

 Estrutura da Tabela 7
                     0     1   \
0   AÇÃO/PROJETO (Tema)  None
1  Origem (prioridade):  None
2                        None
3     O que será feito:  None
4                        None

                                                  2     3     4     5     6   \
0  101 - cat 1.04 - Biblioteca Ativa e aquisição ...  None  None  None  None
1  3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...  None  None  None  None
2  Planejamento/ organização/ instalação de infra...  None  None  None  None
3                                               None  None  None  None  None
4                                               None  None  None  None  None

     7     8     9     10    11
0  None  None  None  None  None
1  None  None  None  None  None
2  None  None  None  None  None
3  None  None  None  None  None
4  None  None  None  None  None

 Estrutura da Tabela 8
                     0     1   \
0                        None
1   AÇÃO/PROJETO (Tema)  None
2                        None
3  Origem (prioridade):  None
4     O que será feito:  None

                                                  2     3     4     5     6   \
0  102 - cat 1.06 - Ações pedagógicas: visitas té...  None  None  None  None
1                                               None  None  None  None  None
2                                               None  None  None  None  None
3  3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...  None  None  None  None
4  Participação em visitas técnicas a empresas lo...  None  None  None  None

     7     8     9     10    11
0  None  None  None  None  None
1  None  None  None  None  None
2  None  None  None  None  None
3  None  None  None  None  None
4  None  None  None  None  None

 Estrutura da Tabela 9
                     0     1   \
0                        None
1   AÇÃO/PROJETO (Tema)  None
2                        None
3  Origem (prioridade):  None
4     O que será feito:  None

                                                  2     3     4     5     6   \
0  103 - cat 1.06 - Ações pedagógicas: visitas té...  None  None  None  None
1                                               None  None  None  None  None
2                                               None  None  None  None  None
3  3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...  None  None  None  None
4  Implementação de programas de capacitação extr...  None  None  None  None

     7     8     9     10    11
0  None  None  None  None  None
1  None  None  None  None  None
2  None  None  None  None  None
3  None  None  None  None  None
4  None  None  None  None  None

 Estrutura da Tabela 10
                     0     1   \
0   AÇÃO/PROJETO (Tema)  None
1  Origem (prioridade):  None
2     O que será feito:  None
3                        None
4   Por que será feito:  None

                                                  2     3     4     5     6   \
0   104 - cat 1.03 - COIL/PCI e Escola de Inovadores  None  None  None  None
1  3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...  None  None  None  None
2  Incentivar a participação no projeto “Escola d...  None  None  None  None
3  Para que os alunos possam ampliar o conhecimen...  None  None  None  None
4                                               None  None  None  None  None

     7     8     9     10    11
0  None  None  None  None  None
1  None  None  None  None  None
2  None  None  None  None  None
3  None  None  None  None  None
4  None  None  None  None  None

 Estrutura da Tabela 11
                      0     1  \
0   AÇÃO/PROJETO (Tema)  None
1  Origem (prioridade):  None
2                        None
3     O que será feito:  None
4                        None

                                                   2     3     4     5     6
0  105 - cat 1.12 - Orientação profissional para ...  None  None  None  None
1                                            6-Outra  None  None  None  None
2  Estabelecimento e organização do núcleo de emp...  None  None  None  None
3                                               None  None  None  None  None
4                                               None  None  None  None  None

 Estrutura da Tabela 12
                      0                                                  1  \
0  Período de execução:                                      Data inicial:
1                        01- Análise do PPC dos cursos e aprovação da p...
2   Etapas do processo:                                               None
3                                                                     None
4                                  02- Levantamento de perfil e motivações

      2           3            4     5           6      7
0  None  03/02/2025  Data final:  None  19/12/2025   None
1  None        None         None  None       03/02  19/12
2  None        None         None  None        None   None
3  None        None         None  None        None   None
4  None        None         None  None       03/02  19/12

 Estrutura da Tabela 13
                     0     1   \
0                        None
1   AÇÃO/PROJETO (Tema)  None
2                        None
3  Origem (prioridade):  None
4                        None

                                                  2     3     4     5     6   \
0  106 - cat 1.06 - Ações pedagógicas: visitas té...  None  None  None  None
1                                               None  None  None  None  None
2                                               None  None  None  None  None
3                                            6-Outra  None  None  None  None
4  Acompanhamento e auxílio no desenvolvimento de...  None  None  None  None

     7     8     9     10    11
0  None  None  None  None  None
1  None  None  None  None  None
2  None  None  None  None  None
3  None  None  None  None  None
4  None  None  None  None  None

 Estrutura da Tabela 14
                      0     1  \
0   AÇÃO/PROJETO (Tema)  None
1  Origem (prioridade):  None
2                        None
3     O que será feito:  None
4                        None

                                                   2     3     4     5     6  \
0  107 - cat 1.05 - Monitoria em disciplina do curso  None  None  None  None
1  3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...  None  None  None  None
2  Disponibilizar um monitor para as disciplinas ...  None  None  None  None
3                                               None  None  None  None  None
4                                               None  None  None  None  None

      7     8     9
0  None  None  None
1  None  None  None
2  None  None  None
3  None  None  None
4  None  None  None

 Estrutura da Tabela 15
                            0  \
0       Custo R$ (se houver):
1          Situação problema:
2  (a ser resolvida/mitigada)

                                                   1                       2  \
0                        25% da HA para cada monitor  Fonte(s) dos recursos:
1  cat 0.1.01 - Metodologia de ensino, desempenho...                    None
2                                 cat 0.1.99 - Outra                    None

      3
0  CESU
1  None
2  None

 Estrutura da Tabela 16
                     0     1   \
0   AÇÃO/PROJETO (Tema)  None
1  Origem (prioridade):  None
2     O que será feito:  None
3                        None
4   Por que será feito:  None

                                                  2     3     4     5     6   \
0                             108 - cat.1.99 - Outra  None  None  None  None
1  1-Regulação - Notificação de órgão (MEC, CEE, ...  None  None  None  None
2                       Processo de Avaliação da CPA  None  None  None  None
3  Com o objetivo de conduzir um processo abrange...  None  None  None  None
4                                               None  None  None  None  None

     7     8     9     10    11
0  None  None  None  None  None
1  None  None  None  None  None
2  None  None  None  None  None
3  None  None  None  None  None
4  None  None  None  None  None

 Estrutura da Tabela 17
                     0                     1   \
0   AÇÃO/PROJETO (Tema)                  None
1  Origem (prioridade):                  None
2     O que será feito:                  None
3   Por que será feito:                  None
4          Responsável:  <nome> Coordenadores

                                                  2     3     4            5   \
0  109 - cat 1.01 - Adequação/reestruturação de P...  None  None         None
1  1-Regulação - Notificação de órgão (MEC, CEE, ...  None  None         None
2  Análise e reestruturação do PPC do curso para ...  None  None         None
3                    Para atender exigências legais.  None  None         None
4                                               None  None  None  Qde CH/sem:

     6     7     8      9                    10    11
0  None  None  None   None                 None  None
1  None  None  None   None                 None  None
2  None  None  None   None                 None  None
3  None  None  None   None                 None  None
4  None  None    06  Tipo:  HA - Hora Atividade  None

 Estrutura da Tabela 18
                      0                                                  1
0   AÇÃO/PROJETO (Tema)  110 - cat 1.08 - Eventos e ações para aperfeiç...
1  Origem (prioridade):                                            6-Outra

 Estrutura da Tabela 19
                    0               1   \
0                                 None
1    O que será feito:            None
2                                 None
3  Por que será feito:            None
4         Responsável:  <nome> Direção

                                                  2     3     4            5   \
0  Promover capacitações para os docentes abordan...  None  None         None
1                                               None  None  None         None
2                                               None  None  None         None
3  Para melhoria da qualidade do ensino e para ap...  None  None         None
4                                               None  None  None  Qde CH/sem:

     6     7     8      9                    10    11
0  None  None  None   None                 None  None
1  None  None  None   None                 None  None
2  None  None  None   None                 None  None
3  None  None  None   None                 None  None
4  None  None    02  Tipo:  HA - Hora Atividade  None

 Estrutura da Tabela 20
                     0     1   \
0   AÇÃO/PROJETO (Tema)  None
1  Origem (prioridade):  None
2                        None
3     O que será feito:  None
4                        None

                                                  2     3     4     5     6   \
0  111 - cat 1.07 - Divulgação do vestibular e aç...  None  None  None  None
1                                            6-Outra  None  None  None  None
2  Divulgar notícias da instituição e dos cursos ...  None  None  None  None
3                                               None  None  None  None  None
4                                               None  None  None  None  None

     7     8     9     10    11
0  None  None  None  None  None
1  None  None  None  None  None
2  None  None  None  None  None
3  None  None  None  None  None
4  None  None  None  None  None

 Estrutura da Tabela 21
                      0                                    1  \
0   AÇÃO/PROJETO (Tema)                                 None
1  Origem (prioridade):                                 None
2     O que será feito:                                 None
3   Por que será feito:                                 None
4                        <nome> Mariana Cristina Pontes Dias

                                                   2     3            4     5  \
0  112 - cat 1.07 - Divulgação do vestibular e aç...  None         None  None
1                                            6-Outra  None         None  None
2         Divulgação do vestibular e dos seus cursos  None         None  None
3  Para divulgar o vestibular da instituição Fate...  None         None  None
4                                               None  None  Qde CH/sem:  None

      6      7                           8
0  None   None                        None
1  None   None                        None
2  None   None                        None
3  None   None                        None
4    05  Tipo:  H - Hora <não\ntipificada>

 Estrutura da Tabela 22
                     0                                                  1  \
0                       01- Manter as estratégias de divulgação de tod...
1  Etapas do processo:                                               None
2                                                                    None
3                       02- Fazer controle da campanha do vestibular n...
4                       03- Realizar visitas em escolas e outros locai...

      2     3      4      5
0  None  None  02/01  19/12
1  None  None   None   None
2  None  None   None   None
3  None  None  02/01  19/12
4  None  None  02/01  19/12

 Estrutura da Tabela 23
                     0     1   \
0   AÇÃO/PROJETO (Tema)  None
1  Origem (prioridade):  None
2     O que será feito:  None
3                        None
4   Por que será feito:  None

                                                  2     3     4     5     6   \
0  101 - cat 1.04 - Biblioteca Ativa e aquisição ...  None  None  None  None
1  3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...  None  None  None  None
2            Promover o uso da biblioteca da unidade  None  None  None  None
3  Planejamento/ organização/ instalação de infra...  None  None  None  None
4                                               None  None  None  None  None

     7     8     9     10    11
0  None  None  None  None  None
1  None  None  None  None  None
2  None  None  None  None  None
3  None  None  None  None  None
4  None  None  None  None  None

 Estrutura da Tabela 24
                     0     1   \
0                        None
1   AÇÃO/PROJETO (Tema)  None
2                        None
3  Origem (prioridade):  None
4                        None

                                                  2     3     4     5     6   \
0  102 - cat 1.06 - Ações pedagógicas: visitas té...  None  None  None  None
1                                               None  None  None  None  None
2                                               None  None  None  None  None
3  3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...  None  None  None  None
4  Visitas técnicas as empresas da região, feira ...  None  None  None  None

     7     8     9     10    11
0  None  None  None  None  None
1  None  None  None  None  None
2  None  None  None  None  None
3  None  None  None  None  None
4  None  None  None  None  None

 Estrutura da Tabela 25
                     0     1   \
0                        None
1   AÇÃO/PROJETO (Tema)  None
2                        None
3  Origem (prioridade):  None
4     O que será feito:  None

                                                  2     3     4     5     6   \
0  103 - cat 1.06 - Ações pedagógicas: visitas té...  None  None  None  None
1                                               None  None  None  None  None
2                                               None  None  None  None  None
3  3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...  None  None  None  None
4  Participação do Hachathon entre cursos de tecn...  None  None  None  None

     7     8     9     10    11
0  None  None  None  None  None
1  None  None  None  None  None
2  None  None  None  None  None
3  None  None  None  None  None
4  None  None  None  None  None

 Estrutura da Tabela 26
                     0     1   \
0   AÇÃO/PROJETO (Tema)  None
1  Origem (prioridade):  None
2     O que será feito:  None
3                        None
4   Por que será feito:  None

                                                  2     3     4     5     6   \
0                 104 - cat 1.14 - Curso de Extensão  None  None  None  None
1  3-Gestão Tática - CPA (RADE, RCEE, RLAB, RWebS...  None  None  None  None
2              Participação em Cursos entre Fatecs l  None  None  None  None
3  Para que os alunos tenham maior conhecimento s...  None  None  None  None
4                                               None  None  None  None  None

     7     8     9     10    11
0  None  None  None  None  None
1  None  None  None  None  None
2  None  None  None  None  None
3  None  None  None  None  None
4  None  None  None  None  None

 Estrutura da Tabela 27
                     0     1  \
0                       None
1  AÇÃO/PROJETO (Tema)  None
2                       None
3              Origem:  None
4    O que será feito:  None

                                                   2     3     4     5     6  \
0  105 - cat 1.06 - Ações pedagógicas: visitas té...  None  None  None  None
1                                               None  None  None  None  None
2                                               None  None  None  None  None
3                                            3-Outra  None  None  None  None

In [22]:
# Verificar se certos termos estão presentes no texto extraído
keywords = ["ação", "prioridade", "recurso", "eixo", "problema"]

for i, texto in enumerate(textos_extraidos):
    print(f"\n Página {i+1}:")
    for palavra in keywords:
        if palavra.lower() in texto.lower():
            print(f" Contém: {palavra}")

 Página 1:
 Contém: ação
 Contém: recurso
 Contém: problema

 Página 2:
 Contém: ação
 Contém: prioridade
 Contém: recurso

 Página 3:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 4:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 5:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 6:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 7:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 8:
 Contém: ação
 Contém: recurso
 Contém: problema

 Página 9:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 10:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 11:
 Contém: ação
 Contém: recurso
 Contém: problema

 Página 12:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 13:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 14:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 15:
 Contém: ação
 Contém: prioridade

 Página 16:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 17:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 18:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 19:
 Contém: ação
 Contém: recurso
 Contém: problema

 Página 20:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 21:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 22:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: eixo
 Contém: problema

 Página 23:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 24:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 25:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 26:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 27:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 28:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 29:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 30:

 Página 31:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 32:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 33:
 Contém: ação
 Contém: prioridade

 Página 34:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 35:
 Contém: ação
 Contém: prioridade
 Contém: recurso
 Contém: problema

 Página 36:
 Contém: ação
 Contém: recurso

 Página 37:
 Contém: ação
 Contém: recurso

 Página 38:
 Contém: ação

 Página 39:
 Contém: ação

 Página 40:
 Contém: ação
 Contém: eixo

 Página 41:
 Contém: ação
 Contém: problema

 Página 42:
 Contém: ação

 Página 43:
 Contém: ação

 Página 44:

 Página 45:
 Contém: eixo

 Página 46:
 Contém: ação

 Página 47:

 Página 48:

 Página 49:
 Contém: ação
 Contém: eixo

 Página 50:

 Página 51:

 Página 52:

 Página 53:

 Página 54:
 Contém: ação

 Página 55:
 Contém: ação
 Contém: eixo

 Página 56:
 Contém: ação

 Página 57:
 Contém: ação

 Página 58:
 Contém: ação
 Contém: eixo
 Contém: problema

 Página 59:
 Contém: ação
 Contém: recurso
 Contém: eixo

 Página 60:

 Página 61:
 Contém: ação
 Contém: recurso
 Contém: eixo
 Contém: problema

 Página 62:
 Contém: ação
 Contém: recurso

 Página 63:

 Página 64:

 Página 65:
 Contém: ação

 Página 66:
 Contém: ação

 Página 67:
 Contém: ação
 Contém: recurso

 Página 68:
 Contém: ação
 Contém: eixo

 Página 69:
 Contém: ação